/*eslint max-lines: 0 */
define({
	'TITLE_PROPERTIES': 'Properties',
	'CONTEXTUAL_HELP': 'Help',
	'LABEL_ID': 'ID',
	'LABEL_SELECT_FROM_PREVIOUS_PRESENTATION': 'Select from Previous Presentation',
	'LABEL_NAME': 'Name',
	'LABEL_DESCRIPTION': 'Description',
	'TITLE': 'Title',
	'IDENTIFIER': 'Identifier:',
	'LABEL_STYLE': 'Style',
	'LABEL_OPTIONS_NAMES': 'Options Names',
	'LABEL_OPTIONS_VALUES': 'Options Values',
	'BTN_SAVE': 'Save',
	'BTN_PREVIEW': 'Preview',
	'EVENT_MUST_BE_REMOVED': 'Error: This event must be removed',
	'USE_FULL_EDITOR': 'Convert to Web Form',
	'CONVERT_TO_FULL_EDITOR': 'Convert',
	'CONVERT_TO_FULL_CONFIRM_1': 'You must convert this form to open it in the Web Form editor and use its complete range of options.',
	'CONVERT_TO_FULL_CONFIRM_2': 'If you convert, your settings are saved, but you will no longer be able to open the form in the Quick Form editor. Are you sure you want to continue?',
	'ARIA_EDITING_TOOLBAR': 'Editing Toolbar',
	'BTN_REMOVE': 'Remove',
	'LABEL_EMPTY_MESSAGE': 'Empty State Message',
	'LABEL_EMPTY_MESSAGE_HELP': 'This message will display when the table is empty.',
	'NO_ROWS': 'There are no entries.',
	'LABEL_LABEL': 'Label',
	'LABEL_INLINE_HTML': 'Inline HTML',
	'LABEL_AUTOFOCUS': 'Auto Focus',
	'LABEL_DISABLED': 'Disabled',
	'LABEL_HIDE_LABELS': 'Hide Labels',
	'LABEL_HIDE_ROW_CHECKBOX': 'Hide Row Checkbox',
	'LABEL_PLACEHOLDER': 'Placeholder',
	'LABEL_HINT': 'Hint',
	'LABEL_HELP': 'Help',
	'LABEL_HIDE': 'Hide',
	'LABEL_PASSWORD': 'Password',
	'LABEL_HIDDEN': 'Hidden',
	'LABEL_STRETCH': 'Stretch',
	'AUTOMATIC_HEIGHT': 'Automatic Height',
	'AUTOMATIC_HEIGHT_HELP': 'Automatically adjust the height to fit the content.',
	'CONNECTOR_FORM_EXPRESSION': 'Form Expression',
	'LABEL_PREVENT_FREE_TEXT': 'Prevent Free Text',
	'LABEL_LAZY': 'Lazy Loading',
	'LABEL_EXPANDED': 'Expanded',
	'LABEL_INLINE': 'Inline',
	'LABEL_MAX_LENGTH': 'Max Length',
	'LABEL_MIN_LENGTH': 'Min Length',
	'LABEL_MAX_DATE': 'Max Date',
	'LABEL_MIN_DATE': 'Min Date',
	'LABEL_MAX_TIME': 'Max Time',
	'LABEL_MIN_TIME': 'Min Time',
	'LABEL_TIME_STEP': 'Time Step',
	'LABEL_DEFAULT_VALUE': 'Default Value',
	'LABEL_TEXT_VALUE': 'Default Text',
	'LABEL_CONNECTOR': 'Connector',
	'LABEL_CONNECTOR_OPERATION': 'Operation',
	'LABEL_RESOURCE_OPERATION': 'Resource',
	'STEP_1_MIN': '1 Minute',
	'STEP_5_MIN': '5 Minutes',
	'STEP_10_MIN': '10 Minutes',
	'STEP_15_MIN': '15 Minutes',
	'STEP_20_MIN': '20 Minutes',
	'STEP_30_MIN': '30 Minutes',
	'STEP_40_MIN': '40 Minutes',
	'STEP_45_MIN': '45 Minutes',
	'STEP_1_HOUR': '1 Hour',
	'STEP_90_MIN': '1.5 Hours',
	'LABEL_MAX_VALUE': 'Max',
	'LABEL_MIN_VALUE': 'Min',
	'LABEL_STEP_VALUE': 'Step',
	'LABEL_PATTERN_VALUE': 'Pattern',
	'LABEL_PATTERN_MESSAGE': 'Pattern Validation Message',
	'LABEL_AUTOCOMPLETE': 'Autocomplete',
	'LABEL_REQUIRED': 'Required',
	'LABEL_SORTED': 'Sorted',
	'LABEL_UP_DOWN_ARROW': 'Show up/down buttons',
	'LABEL_FORMAT': 'Format',
	'LABEL_IMAGE_FORMAT': 'Image Format',
	'LABEL_READONLY': 'Read Only',
	'LABEL_SET_READONLY': 'make readonly',
	'LABEL_MULTIPLE_SELECTION': 'Multiple Selection',
	'KEEP_HEADER_ON_VIEW': 'Keep Header Visible',
	'LABEL_TEXT': 'Default Text',
	'LABEL_TYPE': 'Type',
	'LABEL_OPTION_NAME': 'Option Name Type',
	'LABEL_OPTION_VALUE': 'Option Value Type',
	'LABEL_SELECTED_TAB': 'Selected Tab',
	'LABEL_MULTIPLE': 'Multiple',
	'LABEL_VALUE': 'Value',
	'LABEL_PRESENTATION': 'Presentation',
	'LABEL_ROWS': 'Rows',
	'LABEL_OPEN': 'Open',
	'LABEL_CURRENCY': 'Currency',
	'LABEL_SOURCE_URL': 'Source Url',
	'LABEL_WIDTH': 'Width',
	'LABEL_HEIGHT': 'Height',
	'URL_FORMAT_ERROR_MESSAGE': 'Incorrect embed url.',
	'GENERIC_ERROR': 'There was an error during submit.',
	'LABEL_AUTO_PLAY': 'Auto Play',
	'LABEL_ALLOW_FULLSCREEN': 'Allow Fullscreen',
	'LABEL_SHOW_CONTROLS': 'Show Controls',
	'LABEL_LOOP': 'Loop',
	'LABEL_BINDING': 'Binding',
	'IMAGE_BASE64_BINDING': 'Base64 Binding',
	'LABEL_EVENTS': 'Events',
	'CONTROL_INPUT_TEXT': 'Input text',
	'CONTROL_TEXT_AREA': 'Text Area',
	'CONTROL_BUTTON': 'Button',
	'CONTROL_SELECT': 'Select',
	'CONTROL_CHECKLIST': 'Checklist',
	'CONTROL_CHECKBOX': 'Checkbox',
	'CONTROL_RADIO_BUTTON': 'Radio Button',
	'CONTROL_NUMBER': 'Number',
	'CONTROL_SIMPLE_TEXT': 'Text',
	'CONTROL_DATE': 'Date',
	'CONTROL_TIME': 'Time',
	'CONTROL_DATE_TIME': 'Date Time',
	'CONTROL_EMAIL': 'Email',
	'CONTROL_URL': 'URL',
	'CONTROL_MESSAGE': 'Message',
	'CONTROL_LINK': 'Link',
	'CONTROL_MONEY': 'Money',
	'CONTROL_VIDEO': 'Video',
	'CONTROL_TRAIN': 'Train',
	'CONTROL_IDENTITY_BROWSER': 'Identity Browser',
	'CONTROL_PHONE': 'Phone',
	'CONTROL_IMAGE': 'Image',
	'CONTROL_PANEL': 'Panel',
	'CONTROL_SECTION': 'Section',
	'CONTROL_TAB_CONTAINER': 'Tab',
	'CONTROL_TAB': 'Tab',
	'ADD_TAB': 'Add tab',
	'SHOW_SCOPE_FILTER': 'Scope Filter',
	'TITLE_BASIC_PALETTE': 'Basic',
	'TITLE_ADVANCED_PALETTE': 'Advanced',
	'TITLE_FORMS_PALETTE': 'Forms',
	'BTN_EXTRACT': 'Extract Snippet',
	'SNIPPET_NAME': 'snippetName',
	'REMOVE_REUSABLE_COMMAND_1': 'ALL USAGES OF ',
	'REMOVE_REUSABLE_COMMAND_2': ' HAVE BEEN CONVERTED TO LOCAL',
	'EXTRACT_SNIPPET_TITLE': 'Get started creating reusable snippets',
	'EXTRACT_SNIPPET_HELP_1': 'Choose the actions, conditions, loops, connectors, and filters you want to extract, name your snippet, and click OK. Extracted actions, loops, and if blocks must be adjacent. Manage created reusable snippets from the presentations property panel.',
	'BTN_UNDO': 'Undo',
	'BTN_TRANSLATE': 'Translate',
	'BTN_REDO': 'Redo',
	'DEFAULT_CURRENCY': 'USD',
	'CURRENCY_PATTERN': '¤ ##,##0.00',
	'PHONE_FORMAT_INTERNATIONAL': 'International',
	'PHONE_FORMAT_US': 'US',
	'DEFAULT_PHONE_FORMAT': 'US',
	'FORMAT_ERROR_MESSAGE_US': 'You must enter proper phone number in US format.',
	'FORMAT_ERROR_MESSAGE_INTERNATIONAL': 'You must enter proper phone number in International format.',
	'LABEL_URL': 'Image URL',
	'LABEL_ALT_TEXT': 'Alternative text',
	'TEXT_NO_IMAGE': 'No Image',
	'LABEL_AUTO_BINDING': 'Auto Binding',
	'TITLE_FORM_DEFINITION': 'Data',
	'FORM_DEFINITION_HEADING': 'Form Data Objects',
	'DELETE_FORM_DEFINITION_TITLE': 'Delete Attribute Confirmation',
	'DELETE_FORM_DEFINITION_SUMMARY_1': 'Are you sure you want to delete the attribute {0}?',
	'DELETE_FORM_DEFINITION_SUMMARY_2': 'It\'s bound to at least one control, deleting it will clear the bindings.',
	'DELETE': 'Delete',
	'EDIT': 'Edit',
	'CREATE': 'Create',
	'UPDATE': 'Update',
	'ADD': 'Add',
	'OK': 'OK',
	'CANCEL': 'Cancel',
	'MISSING_BINDING': 'Missing binding',
	'CREATE_FORM_DEFINITION_TITLE': 'Create Attribute',
	'EDIT_FORM_DEFINITION_TITLE': 'Edit Attribute',
	'NAME': 'Name',
	'COMPACT_NAME': 'Function Name',
	'REUSABLE_EVENT_NAME': 'Snippet Name',
	'REUSABLE_EVENT_NAME_PLACEHOLDER': 'Enter Snippet Name',
	'ADJACENT_SUMMARY': 'Selected blocks must be adjacent.',
	'ADJACENT_DETAIL': 'To extract blocks they must be adjacent.',
	'TYPE': 'Type',
	'ATTRIBUTE': 'attribute',
	'LIST_OF_VALUES': 'List of values',
	'INVALID_FORM_DEFINITION_NAME': 'Invalid Attribute Name',
	'INVALID_FORM_DEFINITION_NAME_DESCRIPTION': 'An Attribute name can only start with a lowerCase letter, and can only contain, letters, digits and underscores',
	'INVALID_FORM_DEFINITION_NAME_DUPLICATED': 'Attribute name, with same or different case, already exists',
	'INVALID_FORM_DEFINITION_NAME_XML': 'Attribute name cannot start with xml.',
	'LABEL_PREVIEW_SUBMIT_BTN': 'Submit',
	'LABEL_CLEAR_LOGS': 'Clear Logs',
	'PAYLOAD_JSON': 'Payload JSON',
	'INVALID_JSON': 'Invalid JSON',
	'LABEL_PREVIEW_CUSTOM_PAYLOAD': 'Custom Payload',
	'LABEL_PREVIEW_TRIGGER_CUSTOM_OUTCOME': 'Trigger Custom Outcome',
	'LABEL_PREVIEW_CUSTOM_OUTCOME': 'Custom Outcome',
	'VALIDATION_ERROR': 'Validation Error',
	'OUTCOME': 'Outcome',
	'LOG': 'Log',
	'FILTER_LOGS': 'Filter Logs',
	'RELOAD_PAYLOAD': 'Reload With Payload',
	'OUTCOME_COLON': 'Outcome: {0}',
	'DROP_HERE': 'Drop Elements to this panel!',
	'DROP_HERE_COLUMN': 'Drop an Element to this column!',
	'DROP_HERE_SECTION': 'Drop Elements to this section!',
	'DROP_HERE_TAB': 'Drop Elements to this tab!',
	'LOAD_MORE': 'Load more ...',
	'EMPTY_SEARCH': 'There are no controls that match the search',
	'SEARCH': 'Search',
	'EMPTY_CONTROLS': 'There are no controls defined',
	'EMPTY_SEARCH_FORM': 'There are no forms that match the search',
	'EMPTY_FORMS': 'No forms are defined',
	'CONVERT_TO_CONTROLS': 'Detach',
	'FAILED_TO_LOAD_FORM_CONTENT': 'Failed to load form content',
	'LABEL_LAYOUT': 'Layout',
	'LAYOUT_HORIZONTAL': 'Horizontal',
	'LAYOUT_VERTICAL': 'Vertical',
	'LABEL_STYLE_PROPERTIES': 'Style Properties',
	'LABEL_BACKGROUND_COLOR': 'Background Color',
	'LABEL_COLOR': 'Color',
	'LABEL_FONT_SIZE': 'Font Size',
	'LABEL_FONT_SIZE_XSMALL': 'x-small',
	'LABEL_FONT_SIZE_SMALL': 'small',
	'LABEL_FONT_SIZE_NORMAL': 'normal',
	'LABEL_FONT_SIZE_LARGE': 'large',
	'LABEL_FONT_SIZE_XLARGE': 'x-large',
	'LABEL_TEXT_ALIGN': 'Text Alignment',
	'LABEL_TEXT_ALIGN_LEFT': 'Left',
	'LABEL_TEXT_ALIGN_CENTER': 'Center',
	'LABEL_TEXT_ALIGN_RIGHT': 'Right',
	'LABEL_TEXT_ALIGN_TOP': 'Top',
	'LABEL_TEXT_ALIGN_BOTTOM': 'Bottom',
	'LABEL_BORDER_WIDTH': 'Border Width',
	'LABEL_BORDER_STYLE': 'Border Style',
	'LABEL_BORDER_STYLE_DOTTED': 'Dotted',
	'LABEL_BORDER_STYLE_DASHED': 'Dashed',
	'LABEL_BORDER_STYLE_SOLID': 'Solid',
	'LABEL_RESET_TO_DEFAULT': 'Reset Inline Styles to Default',
	'BTN_UPLOAD': 'Upload',
	'LABEL_STYLESHEET': 'Stylesheet',
	'LABEL_STYLESHEETS': 'Stylesheets',
	'LABEL_IMAGE': 'Image',
	'LABEL_IMAGES': 'Images',
	'NO_STYLE': 'No style',
	'NO_SELECTION': 'No Selection',
	'LABEL_PREVIEW': 'Preview',
	'LABEL_MAX_ROWS': 'Max Rows:',
	'LABEL_MIN_ROWS': 'Min Rows:',
	'LABEL_CSS_PREVIEW': 'CSS',
	'LABEL_FORM_PREVIEW': 'Form',
	'LABEL_GENERAL': 'General',
	'LABEL_STYLING': 'Styling',
	'LABEL_SM_COL_SIZE': 'Small column size',
	'LABEL_MD_COL_SIZE': 'Medium column size',
	'LABEL_LG_COL_SIZE': 'Large column size',
	'LABEL_XL_COL_SIZE': 'Extra large column size',
	'LABEL_AUTO_COL_SIZE': 'Automatic column size',
	'LABEL_SELECTED_MEDIA': 'Displaying For:',
	'LABEL_CLASS': 'Class',
	'LABEL_PROPERTY': 'Property',
	'LABEL_MAKE_LABEL_DYNAMIC': 'Make Label Dynamic',
	'LABEL_LABEL_BINDING': 'Label Binding',
	'LABEL_VALUE_BINDING': 'Value Binding',
	'LABEL_DEFAULT_LABEL': 'Default Label',
	'LABEL_ANCHOR': 'Anchor',
	'TITLE_LOOK_UP_STYLESHEET': 'Lookup stylesheet',
	'CLEAR_STYLESHEET': 'Clear stylesheet',
	'INVALID_STYLESHEET': 'Stylesheet does not exist',
	'TITLE_LOOK_UP_IMAGE': 'Lookup image',
	'ADD_IMAGES_FROM_FILE': 'Add images from file',
	'TITLE_CLOSE_PANEL': 'Close Panel',
	'INVALID_BINDING': 'Invalid Binding',
	'INVALID_BINDING_TYPE': 'Invalid Binding Type',
	'BINDING_ERROR': 'The control has an invalid binding',
	'BINDING_WARNING': 'The control is unbound',
	'CONTROL_HAS_VALIDATION_ERROR': 'The control has validation error',
	'CONTROL_HAS_VALIDATION_WARNING': 'The control has validation warning',
	'FORM': 'Form',
	'PRESENTATION': 'Presentation',
	'PRESENTATIONS': 'Presentations',
	'DEFAULT': 'Default',
	'MAIN_PRESENTATION': 'Main',
	'DEFAULT_FORM_NAME': 'Form',
	'DEFAULT_TAG': '(Default)',
	'MAKE_DEFAULT': 'Make default',
	'MAKE_THIS_THE_DEFAULT_PRESENTATION': 'Make this the default presentation',
	'DEFAULT_PRESENTATION': 'Default presentation',
	'SWITCH_TO_THIS_PRESENTATION': 'Switch to this presentation',
	'CREATE_PRESENTATION_TITLE': 'Create Presentation',
	'SELECT_PRESENTATION_TYPE_TITLE': 'Select Presentation Type',
	'SELECT_PRESENTATION_TYPE_DECLARATION': 'After you select any of these options, you can\'t change the presentation type',
	'CUSTOMIZE_PRESENTATION': 'Customize Presentation',
	'INVALID_PRESENTATION_NAME_DUPLICATED': 'Presentation name already exists',
	'BASED_ON': 'Based on',
	'FROM_SCRATCH': '$[From scratch$]',
	'SCRATCH': 'Scratch',
	'CLONE': 'Clone',
	'CUSTOMIZE': 'Customize',
	'DELETE_DEFAULT_PRESENTATION_TITLE': 'Delete Default Presentation Confirmation',
	'DELETE_PRESENTATION_TITLE': 'Delete Presentation Confirmation',
	'DELETE_DEFAULT_PRESENTATION_SUMMARY': 'You are about to delete the Default Presentation.',
	'SELECT_DEFAULT_PRESENTATION': 'Select the new Default Presentation',
	'LIST_CUSTOMIZABLE_PRESENTATION_TOBE_DELETED': 'List of customizable presentation to be deleted',
	'MESSAGE_INVALID_URL': 'Please enter a valid URL.',
	'MESSAGE_INVALID_EMAIL': 'Please enter a valid e-mail.',
	'INVALID_STEP_VALUE_MESSAGE': 'Step should be greater than 0.',
	'BLANK_NOT_ALLOWED_MESSAGE': 'Blank values are not allowed.',
	'OPTIONS_UNEQUAL_ERROR': 'Options names and values count should be equal.',
	'OPTIONS_UNIQUE_VALUES_ERROR': 'Options values should be unique.',
	'CONTROL_NAME_EXISTS_ERROR': 'Control Name already exists in the current form.',
	'NO_EVENTS': 'No events defined',
	'ACTION': 'Action',
	'CONNECTOR_CALL': 'Connector',
	'REUSABLE_SNIPPET': 'Snippet',
	'DETACH': 'DETACH Snippet',
	'DETACH_BLOCKS_COMMAND': 'Detached Blocks',
	'CLICK_DETACH': 'Click to Detach',
	'SELECT_SNIPPET': 'Select Snippet',
	'CONTROL_NAME': 'Control',
	'WHICH': 'Which option?',
	'PROPERTY': 'Property',
	'IF': 'If',
	'ERROR_HANDLER': 'Error Handler',
	'THEN': 'Then',
	'ELSE': 'Else',
	'ELSE_ACTION': 'Else Action',
	'ELSE_IF': 'Else If',
	'AND': 'And',
	'OR': 'Or',
	'CONDITION': 'Condition',
	'PLUS_ACTION': '+ Action',
	'PLUS_IF': '+ If',
	'PLUS_THEN_IF': '+ Then if',
	'PLUS_LOOP': '+ Loop',
	'PLUS_CONNECTOR': '+ Connector',
	'PLUS_ELSE_ACTION': '+ Else Action',
	'PLUS_ELSE_IF': '+ Else If',
	'PLUS_ERROR_HANDLER': '+ Error Handler',
	'PLUS_CONDITION': '+ Condition',
	'CHOOSE_DEVICE': 'Choose any device',

	'LOOP': 'Loop',
	'DO': 'Do',
	'LOOP_SUMMARY_1_BLOCK': '1 Block',
	'LOOP_SUMMARY_BLOCKS': '{0} Blocks',
	'LOOP_INDEX': 'Index',
	'LOOP_POSITION': 'Position',
	'LOOP_VALUE': 'Value',
	'LOOP_ISFIRST': 'Is First?',
	'LOOP_ISLAST': 'Is Last?',

	'GENERIC': 'Generic',

	'LABEL_SKIP_UPON_LOAD': 'Skip Upon Load',
	'SKIP_ON_LOAD_INLINE_HELP': 'Skip the connector data call when the form loads, typically so that the call can be executed later.',
	'LABEL_IGNORE_CONNECTOR_ERROR': 'Ignore connector error',
	'IGNORE_CONNECTOR_ERROR_INLINE_HELP': 'Ignore connector error, so other actions can still execute',
	'EVENT_NAME_LABEL': 'Event Name',

	'ADD_CONTROL_COMMAND': 'Added Control',
	'TRANSLATE_COMMAND': 'Translations Updated',
	'ADD_DEFINITION_COMMAND': 'Data Attribute Added',
	'ADD_DEFINITION_FROM_CONTROL': 'Added Data Attribute From Control',
	'ADD_PRESENTATION_COMMAND': 'Added Presentation',
	'ADD_ROW_COMMAND': 'Added Row',
	'CONVERT_REUSABLES_COMMAND': 'Convert Reusables',
	'ADD_TAB_COMMAND': 'Added Tab',
	'CHANGE_DEFINITION_NAME_COMMAND': 'Data Attribute name changed',
	'CHANGE_EXPRESSION_VALUE_COMMAND': 'Connector expression value changed',
	'CHANGE_EXPRESSION_TYPE_COMMAND': 'Connector expression type changed',
	'CHANGE_CONTROL_NAME_COMMAND': 'Changed Control Name',
	'CHANGE_EVENT_COMMAND': 'Changed Event',
	'EDIT_EVENT_COMMAND': 'Edit Event',
	'CHANGE_OPTIONS_FEED_COMMAND': 'Changed Option Type',
	'CHANGE_FORM_PROPERTY_COMMAND': 'Changed Form Property',
	'CHANGE_PRESENTATION_PROPERTY_COMMAND': 'Changed Presentation Property',
	'CHANGE_PROPERTY_COMMAND': 'Changed Property',
	'CHANGE_DATA_SENSITIVITY_COMMAND': 'Data Sensitivity Changed',
	'ADD_EVENT_COMMAND': 'Added Event',
	'DELETE_EVENT_COMMAND': 'Removed Event',
	'MOVE_CONTROL_COMMAND': 'Moved Control',
	'MOVE_ROW_COMMAND': 'Moved Row',
	'REMOVE_CONTROL_COMMAND': 'Removed Control',
	'REMOVE_DEFINITION_COMMAND': 'Removed Data Attribute',
	'REMOVE_DEFINITION_FROM_CONTROL_COMMAND': 'Removed Data Attribute From Control',
	'REMOVE_PRESENTATION_COMMAND': 'Removed Presentation',
	'REMOVE_ROW_COMMAND': 'Removed Row',
	'REMOVE_TAB_COMMAND': 'Removed Tab',
	'REMOVE_REUSABLE_SNIPPET_COMMAND': 'Remove Reusable Snippet',
	'REORDER_TAB_COMMAND': 'Reordered Tab',
	'REORDER_COLUMNS_COMMAND': 'Reordered Column',
	'MOVE_ROW_TO_COLUMN_COMMAND': 'Moved Row to Column',
	'MODIFY_EVENT_IMPLEMENTATION_COMMAND': 'Changed Event Implementation',
	'RESET_STYLES_COMMAND': 'Reset Inline Styles to Default',
	'ADD_STYLESHEET_COMMAND': 'Stylesheet added',
	'UPDATE_STYLESHEET_COMMAND': 'Stylesheet updated',
	'ADD_OR_UPDATE_IMAGE_COMMAND': 'Image added',
	'CHANGE_STYLESHEET_COMMAND': 'Selected Stylesheet changed',
	'CHANGE_IMAGE_COMMAND': 'Selected Imaged changed',
	'REMOVE_STYLESHEET_COMMAND': 'Stylesheet removed',
	'REMOVE_IMAGE_COMMAND': 'Image removed',
	'FORM_INTO_CONTROL_COMMAND': 'Form reference detached',

	'ADD_BLOCK_COMMAND': 'Added Block',
	'CHANGE_ACTION_COMMAND': 'Changed Action',
	'CHANGE_CONTROL_COMMAND': 'Changed Control',
	'ADD_CONDITION_COMMAND': 'Added Condition',
	'EDIT_ACTION_COMMAND': 'Changed Value',
	'REMOVE_BLOCK_COMMAND': 'Removed Block',
	'REORDER_BLOCK_COMMAND': 'Reordered Block',
	'REMOVE_CONDITION_COMMAND': 'Removed Condition',

	'CREATE_GLOBAL_CONNECTOR_COMMAND': 'Added Global Connector',
	'REMOVE_GLOBAL_CONNECTOR_COMMAND': 'Removed Global Connector',

	'UNDONE_COMMAND': 'Undone Command: ',
	'REDONE_COMMAND': 'Redone Command: ',
	'CSS_BROWSER': 'Css Browser',
	'IMAGE_BROWSER': 'Image Browser',

	'CAN_ADD_REMOVE_ROW': 'Users can Add/Remove Rows',
	'CONTROL_TABLE_COLUMN': 'Column',
	'CONTROL_REPEATABLE_SECTION': 'Repeatable Section',
	'CONTROL_TABLE': 'Table',
	'COLUMNS': 'Columns',
	'UNKNOWN': 'Unknown',
	'REMOVE_ALL_UNKNOWN': 'Clean',

	'LABEL_ERROR_SUMMARY': 'Summary',
	'LABEL_ERROR_DETAIL': 'Detail',
	'LABEL_ERROR_MSG': 'Message',

	'EXPRESSION_TYPE': 'Expression Type',
	'ARGUMENT_TYPE': 'Argument Type',
	'LOOP_CONTROL_VARIABLE': 'Loop Control Variable',
	'SOURCE_TYPE': 'Source Type',
	'OPTIONS_TYPE_LABEL': 'Options Source',
	'TABLES_TYPE_LABEL': 'Table Source',
	'LABEL_DYNAMIC_LIST': 'List to Filter',
	'BASE64_BINDING_HELP': 'Binding Name for desired image in base64 format',
	'IMAGE_FORMAT_HELP': 'Choose among valid image formats: jpg, gif, png, svg, tiff',
	'DOCUMENT_BINDING_HELP': 'Binding Name for document reference',
	'MISSING_OPTIONS_BINDING': 'Missing Options List',
	'INVALID_OPTIONS_LIST': 'The selected element does not exist',
	'INVALID_OPTIONS_TYPE': 'The selected element is not a compatible type.',
	'INVALID_DOCUMENT_TYPE': 'The selected item is not a document reference.',
	'MISSING_LABEL_BINDING': 'Missing label mapping',
	'MISSING_VALUE_BINDING': 'Missing value mapping',
	'INVALID_MAPPING': 'The selected element does not exist in the selected options list',
	'INVALID_MAPPING_LABEL': 'The selected element cannot be assigned to the label',
	'INVALID_MAPPING_VALUE': 'The selected element cannot be assigned to the value',

	'SIMPLE_FORMS_TIPS_TITLE': 'Add a new control or panel.',
	'SIMPLE_FORMS_PLUS': 'New Panel',
	'SIMPLE_ADD_CONTROL_PLUS': 'Control',

	'FUNCTION': 'Function',
	'COMPACT_FUNCTION': 'Compact Function',
	'EXPAND': 'Expand',
	'COLLAPSE': 'Collapse',
	'CONTROL_ACTIONS': 'Control Actions',
	'STYLE_ACTIONS': 'Style Actions',
	'STATIC_FIRST_LABEL': 'Option 1',
	'STATIC_FIRST_VALUE': 'Option1',
	'STATIC_SECOND_LABEL': 'Option 2',
	'STATIC_SECOND_VALUE': 'Option2',
	'CONNECTOR_EXPRESSION_STATIC': 'Text',
	'CONNECTOR_EXPRESSION_FORM': 'Control value',
	'CHANGE_CONNECTOR_OPERATION_COMMAND': 'Change connector operation',
	'CHANGE_CONNECTOR_ID_COMMAND': 'Change connector',
	'CHANGE_CONNECTOR_RESOURCE_COMMAND': 'Change connector resource',
	'CHANGE_CONNECTOR_SKIP_COMMAND': 'Change connector skip on load',
	'CHANGE_CONNECTOR_SPINNER_COMMAND': 'Change connector prevent spinner',
	'CHANGE_CONNECTOR_IGNORE_ERROR_COMMAND': 'Change connector ignore error',
	'QUERY_PARAMS_TITLE': 'Query Parameters',
	'HEADERS_PARAMS_TITLE': 'Header Parameters',
	'TEMPLATE_PARAMS_TITLE': 'Template Parameters',
	'RESPONSE_TITLE': 'Response',
	'EMPTY_SEARCH_BUSINESS_TYPES': 'There are no business types that match the search',
	'EMPTY_BUSINESS_TYPES': 'No business types are defined',
	'TITLE_BUSINESS_TYPES_PALETTE': 'Types',
	'TRUE': 'True',
	'FALSE': 'False',
	'DATA_FROM_CONNECTOR_LABEL': 'Use Data from Connector',
	'SIMPLE': 'Simple',
	'BUSINESS': 'Business',
	'STYLESHEET_DUPLICATE_MSG': 'The stylesheet already exists, do you want to overwrite?',
	'OVERWRITE_STYLESHEET_TITLE': 'Stylesheet overwrite confirmation',
	'OVERWRITE_STYLESHEET_SUMMARY_1': 'The stylesheet already exists, do you want to overwrite?',
	'OVERWRITE_STYLESHEET_SUMMARY_2': 'This will replace the already existing stylesheet with the new one.',
	'OVERWRITE_IMAGE_TITLE': 'Image Overwrite Confirmation',
	'OVERWRITE_IMAGE_SUMMARY_1': 'The image already exists, do you want to overwrite?',
	'OVERWRITE_IMAGE_SUMMARY_2': 'This will replace the already existing image with the new one.',
	'DELETE_STYLESHEET_TITLE': 'Stylesheet delete confirmation',
	'DELETE_STYLESHEET_SUMMARY': 'Are you sure you want to delete the stylesheet?',
	'UNSAFE_CSS_TITLE': 'Unsafe CSS Detected',
	'UNSAFE_CSS_SUMMARY': 'The CSS you provided contains potentially unsafe content. For security reasons, we are unable to process or accept this CSS. Please remove any code that may pose a security risk and try again.',
	'CSS_FILE_TOO_LARGE_SUMMARY': 'We\'re sorry, but we are unable to process your uploaded stylesheet. The file size exceeds the allowed limit. Please upload a file that is smaller than {0}KB.',
	'STYLESHEETS_LIMIT_EXCEEDED_SUMMARY': 'Cannot have more than {0} stylesheets.',
	'STYLESHEET_GENERIC_ERROR': 'Unable to perform this operation. Please try again.',
	'NO_STYLESHEET_LABEL': 'No stylesheet selected',
	'CANNOT_CREATE_STYLESHEET': 'Cannot create stylesheet',
	'CANNOT_UPDATE_STYLESHEET': 'Cannot update stylesheet',
	'CANNOT_DELETE_STYLESHEET': 'Cannot delete stylesheet',
	'CREATE_STYLESHEET_HEADER': 'Create stylesheet',
	'UPDATE_STYLESHEET_HEADER': 'Update stylesheet',
	'VIEW_SWITCH_LABEL': 'Switch between views',
	'BTN_APPLY': 'Apply',
	'APPLIED_LABEL': 'Applied',
	'STYLESHEET_ACTIONS': 'Stylesheet actions',
	'STYLESHEET_INVALID_ERROR': 'Please correct the syntax errors in the stylesheet.',
	'STYLESHEET_VALID_MESSAGE': 'This stylesheet is valid, please preview the form before proceeding.',
	'DRAG_DROP': 'Just Drag & Drop',
	'EMPTY_HELP_1': 'Browse controls from the palettes, find one you need, and drag and drop it onto the central form canvas.',
	'EMPTY_HELP_2': 'Group similar controls in rows and columns and build complex layouts with panels, sections, tabs, and tables.',
	'EMPTY_HELP_3': 'Use presentations to provide different views of your form. For example, display one presentation to employees and another to approvers.',
	'EMPTY_HELP_4': 'Apply a stylesheet to your form, then customize individual controls with their own styling.',
	'EVENT_HELP_TITLE': 'Get started using events, actions, and conditions to define a control’s behavior',
	'PRESENTATION_SWITCHER_HELP': 'Switch between your form’s presentations',
	'AUTO_BINDING_HELP': 'Check to automatically create linked data attributes as you add controls, or uncheck to manually create and link data attributes',
	'EVENT_HELP_ACTION': 'What do you want to add?',
	'EVENT_HELP_1': 'Add an event to specify how and when the action should occur. For example, add an On Load event to fire when the form loads, or an On Change event to fire when users change the control’s value.',
	'EVENT_HELP_2': 'Edit the event to include conditions and actions that run in the order you set. For example, set an if/then condition to check for Cost field entries over 500, and when found, take the action of making the Justification field required.',
	'FORM_NOT_SAVED': 'Form is not saved. Are you sure that you want to close the form editor?',
	'TOGGLE_PROPERTIES': 'Toggle properties',
	'TOGGLE_PALETTE': 'Toggle palette',

	'RUN_ON_ERROR': 'Run on',
	'ALL_ERRORS': 'All Errors',
	'ERROR_401': '401 - Unauthorized',
	'ERROR_403': '403 - Forbidden',
	'ERROR_404': '404 - Not Found',
	'ERROR_408': '408 - Request Timeout',
	'ERROR_500': '500 - Internal Server Error',
	'MOVE_UP': 'Move up',
	'MOVE_DOWN': 'Move down',
	'MOVE_TOP': 'Move to top',
	'MOVE_BOTTOM': 'Move to bottom',

	'DEFAULT_SCOPE': 'Default Scope',
	'PLUS_FILTER': '+ Filter',
	'PLUS_CRITERIA': '+ Criteria',
	'CRITERIA': 'Criteria',
	'PLUS_REUSABLE': '+ Reusable Snippet',
	'PLUS_ELSE_CRITERIA': '+ Else Criteria',

	'STORE_RESPONSE_IN': 'Store response in',
	'STORE_RESULT_IN': 'Store result in',
	'WHAT_PARAMETERS': 'What parameters do you want to use?',
	'AUTOMATIC_PREVENT': 'The submit will be automatically prevented, as there are no error handlers.',
	'NOT_AUTOMATIC_PREVENT': 'The submit will NOT be automatically prevented.',

	'PRESENTATION_INLINE_HELP': 'Lists presentations defined for the form. Add or delete a presentation or change the default.',
	'STYLESHEET_INLINE_HELP': 'Displays the form’s stylesheet. Select, upload, or preview stylesheets in the CSS browser.',
	'DATA_INLINE_HELP': 'Displays the form’s data attributes. Turn on Auto Binding to automatically create and bind attributes as you add controls, or add attributes and manually bind them to controls.',
	'FORMS_PALETTE_INLINE_HELP': 'From this list of other forms created for the application, drag and drop a form to your current form to reuse as is, or click Detach to change it into separate controls.',
	'BUSINESS_TYPES_PALETTE_INLINE_HELP': 'From this list of business types created for the application, drag and drop a business type to your form to create controls based on its data attributes.',
	'FORM_NAME_INLINE_HELP': 'Name assigned to the form when it was created.',
	'DISPLAY_INLINE_HELP': 'Select sizes to visualize how the controls will fit on the form when users view it on devices of different sizes such as mobile phones and tablets.',

	'NAME_INLINE_HELP': 'Internal name for the control',
	'COMPACT_NAME_INLINE_HELP': 'Optional name for your function (max 30 characters)',
	'LABEL_INLINE_HELP': 'Control name that displays to users',
	'INLINE_HTML_INLINE_HELP': 'Check to render the label as HTML',
	'IMAGE_SOURCE': 'Source type for image',
	'IMAGE_SOURCE_LABEL': 'Image Source',
	'DESCRIPTION_INLINE_HELP': 'Control description that displays to users',
	'LINK_LABEL_INLINE_HELP': 'Control name that displays to users, defined as either a static or a dynamic value.',
	'LINK_STATIC_LABEL': 'Static',
	'LINK_DYNAMIC_LABEL': 'Dynamic',
	'BINDING_LABEL_INLINE_HELP': 'Data attribute for the control\'s label, defined either automatically when Auto Binding is enabled or manually using autocompletion.',
	'BINDING_INLINE_HELP': 'Data attribute bound to the control, either automatically when Auto Binding is enabled or manually using autocompletion',
	'DEFAULT_VALUE_INLINE_HELP': 'Value to display to users when the form loads and the current control value is empty',
	'PLACEHOLDER_INLINE_HELP': 'Hint text that displays in the control before users enter a value and describes the expected value',
	'HINT_INLINE_HELP': 'Text to display to users when they select the control',
	'HELP_INLINE_HELP': 'Text to display to users when they hover over or click the control’s help icon',
	'MIN_LENGTH_INLINE_HELP': 'Optionally enter a minimum number of characters or values users must enter into the control',
	'MAX_LENGTH_INLINE_HELP': 'Enter a maximum number of characters users can enter into the control',
	'MAX_ROWS_HELP': 'Enter the maximum number of rows this control can have',
	'PATTERN_INLINE_HELP': 'Using a regular expression, enter validation on text users enter in the control, along with a message to display if validation fails.',
	'UP_DOWN_INLINE_HELP': 'Check to display the up/down buttons used for incrementing/decrementing values.',
	'REQUIRED_INLINE_HELP': 'Check to require users to complete the control to successfully submit the form. An asterisk displays after the control to indicate that it’s required.',
	'DISABLED_INLINE_HELP': 'Check to display the control as inactive (grayed out) to users',
	'SORTED_INLINE_HELP': 'Check to display the control options sorted alphabetically',
	'READ_ONLY_INLINE_HELP': 'Check to display the control’s contents (if any) but not allow users to edit them',
	'AUTOCOMPLETE_INLINE_HELP': 'Check to display autocompletion entries when users begin typing in the control',
	'AUTO_FOCUS_INLINE_HELP': 'Check to make this control the selected control when the form loads. (If multiple controls are set to Auto Focus, the focus goes to the first control in the form.)',
	'HIDE_INLINE_HELP': 'Check to hide the control. For example, you might hide a control by default, but configure another control that when selected triggers an event that displays the hidden control.',
	'PASSWORD_INLINE_HELP': 'Check to make this control a password and mask the input characters. For example, when creating and entering passwords, users do not want their passwords to be displayed in plain text.',
	'STRETCH_INLINE_HELP': 'Check to stretch the control. The control will take up the width of the container.',
	'PREVENT_FREE_TEXT_INLINE_HELP': 'Check to prevent users from entering free text through the keyboard. When enabled, a user is able to enter a date only through the date-selection widget.',
	'ANCHOR_INLINE_HELP': 'Check to make the link point to the control selected in the Default Value field. At the bottom of a long form, for example, you might use an anchor link to return the user\'s focus to the topmost control in the form.',
	'LAZY_TAB_INLINE_HELP': 'Check to load the controls inside the tab lazy',
	'LAZY_SECTION_INLINE_HELP': 'Check to load the controls inside the section lazy (lazy sections will be collapsed by default).',
	'EVENTS_INLINE_HELP': 'Customize a control\'s behavior by adding an event that triggers conditions and actions. Define when the event occurs (example: On Change occurs when a value changes), assign it an optional name, then edit it to add conditions and actions.',
	'MULTIPLE_SELECTION_INLINE_HELP': 'Allow users to select multiple rows of table',
	'KEEP_HEADER_ON_VIEW_HELP': 'If enabled, the header will scroll, so it is always visible',

	'RESET_INLINE_STYLES_TO_DEFAULT_INLINE_HELP': 'Click to discard all styling selections made on this tab and restore settings to their default values.',
	'AUTOMATIC_COLUMN_SIZE_INLINE_HELP': 'Uncheck to specify absolute column sizes for device sizes by entering a number from 1-12, or leave checked for automatic column sizing.',

	'ROWS_INLINE_HELP': 'Specify the number of text rows to display to users (a scroll bar displays if needed)',

	'MULTIPLE_INLINE_HELP': 'Check to allow users to select more than one option in the control',
	'OPTIONS_SOURCE_INLINE_HELP': 'Specify whether the control’s options should come from static values you enter, from a list of values data attribute, or externally from a REST connector created for the application',
	'OPTIONS_NAMES_INLINE_HELP': 'Enter a label to display for each option',
	'OPTIONS_VALUES_INLINE_HELP': 'Enter an internal value for each option',
	'OPTIONS_LIST_INLINE_HELP': 'Select the list of values options source from available attributes',
	'LABEL_BINDING_INLINE_HELP': 'Select a data attribute that will be shown as the label',
	'VALUE_BINDING_INLINE_HELP': 'Select a data attribute that will be the value for the payload when selected',
	'CONNECTOR_INLINE_HELP': 'Select a connector defined for the application as a data source for the list of values control',
	'RESOURCE_INLINE_HELP': 'Select a resource in the selected connector as a data source for the list of values control',
	'OPERATION_INLINE_HELP': 'Select an operation in the selected connector as a data source for the list of values control',

	'INLINE_INLINE_HELP': 'Check to display options horizontally, or uncheck to display them vertically',

	'MIN_INLINE_HELP': 'Optionally set the minimum value users must enter into the control',
	'MAX_INLINE_HELP': 'Set the maximum value users can enter into the control',

	'MIN_DATE_INLINE_HELP': 'Set the earliest date users can select',
	'MAX_DATE_INLINE_HELP': 'Set the latest date users can select',

	'MIN_TIME_INLINE_HELP': 'Set the earliest time users can select',
	'MAX_TIME_INLINE_HELP': 'Set the latest time users can select',
	'TIME_STEP_INLINE_HELP': 'Set the value to increment when users click the control’s clock',

	'EMAIL_MIN_LENGTH_INLINE_HELP': 'Optionally set the minimum number of characters users must enter before the @ symbol for the email address',
	'EMAIL_MAX_LENGTH_INLINE_HELP': 'Set the maximum number of characters users can enter before the @ symbol for the email address',

	'TYPE_INLINE_HELP': 'Select the style and format in which the message displays, as a bold heading or as paragraph text',
	'TARGET_INLINE_HELP': 'Specify whether you want the link to open in the current tab or in a new tab',

	'CURRENCY_INLINE_HELP': 'Select a currency for users entering money values. Decimal points and commas are added if users don’t include them, and values are rounded to two decimal places.',
	'STEP_INLINE_HELP': 'Set the value to increment when users click the up or down arrow',

	'IMAGE_URL_INLINE_HELP': 'Enter a link to the image, as an absolute or relative web address',
	'ALTERNATIVE_TEXT_INLINE_HELP': 'Enter text to display if the image cannot be loaded',

	'SOURCE_URL_INLINE_HELP': 'Enter a link to the video, as a full video, embedded, or shortened web address',
	'SOURCE_URL_TITLE': 'Enter the embed link of youtube/vimeo video.',
	'ALLOW_FULLSCREEN_INLINE_HELP': 'Check to allow users to play the video in full screen',
	'LOOP_INLINE_HELP': 'Check to play the video continuously in a loop',
	'AUTO_PLAY_INLINE_HELP': 'Check to automatically start playing the video when the form loads',
	'SHOW_CONTROLS_INLINE_HELP': 'Check to display controls for users to play or pause the video',

	'FIELD': 'Field',

	'LAYOUT_INLINE_HELP': 'Select a vertical or horizontal orientation for the panel’s controls',

	'EXPANDED_INLINE_HELP': 'Check to show the section expanded when the form loads, or uncheck to show the section collapsed',

	'SELECTED_TAB_INLINE_HELP': 'Select the tab to display as selected when the form loads',

	'COLUMNS_INLINE_HELP': 'Add or remove columns for the table, and edit their labels',
	'USERS_CAN_ADD_REMOVE_ROWS_INLINE_HELP': 'Check to allow users to add or remove table rows',
	'HIDE_LABELS_INLINE_HELP': 'Check to hide the labels of controls added to the table',
	'HIDE_ROWS_INLINE_HELP': 'Check to hide the rows added to the table',
	'USE_DATA_FROM_CONNECTOR_INLINE_HELP': 'Check to populate the table from a REST connector defined for the application, then specify connector settings and map response settings.',
	'LABEL_FUNCTIONS': 'Functions',
	'FUNCTIONS_TEXT': 'Text',
	'FUNCTIONS_OTHER': 'Other',
	'FUNCTIONS_DATE': 'Date',
	'FUNCTIONS_LOGIC': 'Logic',
	'FUNCTIONS_RELATIONAL': 'Relational',
	'FUNCTIONS_MATH': 'Math',
	'FUNCTIONS_ARRAY': 'Array',
	'FUNCTIONS_INTERVAL': 'Interval',
	'FUNCTIONS_CURRENT_USER_DATA': 'Current User',
	'FUNCTIONS_OBJECTS': 'Objects',
	'FIT_SCREEN': 'Fit Screen',
	'_25_percent': '25%',
	'_50_percent': '50%',
	'_75_percent': '75%',
	'_100_percent': '100%',
	'_125_percent': '125%',
	'_150_percent': '150%',
	'PREVIEW': 'Preview',

	'SCOPE_ALL': 'All',
	'SCOPE_USER': 'User',
	'SCOPE_GROUP': 'Group',
	'SCOPE_ROLE': 'Role',
	'SCOPE_MEMBER': 'Member',
	'IDENTITY_NO_MATCHES_FOUND': 'No identity(ies) found',
	'IDENTITY_SELECT_ALL': 'Select All',
	'REST_LABEL': 'Rest',
	'SHOW_SCOPE_FILTER_INLINE_HELP': 'Allow to filter scope on identity',
	'DEFAULT_SCOPE_INLINE_HELP': 'Set the default scope for identity lookup',

	'ROW': 'Row',

	'GLOBAL_CONNECTORS': 'Global Connectors',
	'NO_GLOBAL_CONNECTORS': 'No Global Connectors',
	'GLOBAL_CONNECTORS_HELP': 'Configure a global connector to call in one or more controls in the presentation. Define the connector and its parameters, response data, and error handling, then use connector data in event actions and refresh it as needed.',
	'CONFIGURE_GLOBAL_CONNECTOR': 'Configure Global Connector',
	'REUSABLE_SNIPPETS': 'Reusable Snippets',
	'NO_REUSABLE_SNIPPETS': 'No Reusable Snippets',
	'REUSABLE_SNIPPETS_HELP': 'Configure a reusable snippet to use in one or more events in the presentation.',
	'CONFIGURE_REUSABLE_SNIPPET': 'Configure Reusable Snippet',

	'LABEL_OPTION_N': 'Option {0}',
	'LABEL_PREVENT_LOADING_SPINNER': 'Don\'t show loading spinner',
	'PREVENT_LOADING_SPINNER_INLINE_HELP': 'Check this option to avoid showing the loading spinner for this connector',

	'COMPUTED': 'Computed Value',
	'FILTER': 'Filter',
	'COMPUTED_HELP': 'Check to apply a computation to the control, then click the edit icon to define the control value to be calculated. You can define an action block on which the control value depends, and specify different functions to build complex values based on data, connector data, or control values.',
	'FILTER_HELP': 'Check to apply a filter to the control, then click on the edit icon to define the conditions for filter. You can add multiple conditions which could either be pure filter or a filter based of an if condition.',
	'FILTER_NEEDS_ARRAY': 'You can only apply filters to lists.',
	'CANNOT_FILTER_SELF': 'You cannot apply a filter to itself.',
	'PREVENT_INFINITE_LOOP': 'Source filters must be defined in a preceding block to prevent infinite loops.',
	'CONFIGURE_COMPUTED_VALUE': 'Configure Computed Value',
	'CONFIGURE_FORM_EXPRESSION': 'Configure Form Expression',
	'MIN_ROWS_HELP': 'Enter the minimum number of rows this control can have',

	'REQUEST_BODY': 'Request Body',
	'EDIT_OPTIONS': 'Edit Options',

	'TRANSLATE_DIALOG': 'Translate form',
	'EVENT_BUNDLE_KEY': 'Event: {0} - constant {1}',
	'COMPUTED_BUNDLE_KEY': '{0} computed - constant {1}',
	'CONTROL_BUNDLE_KEY': '{0} - {1}',
	'CONSTANT_TRANSLATION_METADATA_LABEL': 'Constant {0}',
	'COMPUTED_CONSTANT_TRANSLATION_METADATA_LABEL': 'Computed Constant {0}',
	'CURRENT_LANGUAGE': 'Current Language',
	'COLUMN_NAME': 'Column Name',
	'FROM_URL': 'From URL',
	'FROM_FILE': 'From File',
	'FROM_BASE64': 'From Base64',

	'EMPTY_BY_DEFAULT': 'Empty by default',
	'COPY_CONTROLS_FROM_BASE_PRESENTATION': 'Copy controls from base presentation',
	'SUBSCRIBE_CONTROLS_FROM_BASE_PRESENTATION': 'Subscribe controls from base presentation',
	'ALLOWS_ADD_EDIT_CONTROL': 'Allows Add/ Edit of control',
	'ALLOW_ONLY_CHANGE_VISBILITY_CONTROL': 'Allows only changing visibility of control',
	'USE_IT_DESING_NEW_PRESENTATION': 'Use it to design a new presentation',
	'USE_IT_COPY_PREVIOUS_PRESENTATION': 'Use it to copy previous presentation',
	'USE_IT_CUSTOMZE_PREVIOUS_PRESENTATION': 'Use when you just want to customize previous presentation',
	'OPERATOR': 'Operator',
	'FIX': 'Fix',
	'EXAMPLES': 'Examples',
	'CATEGORY': 'Category',
	'CONTEXTUAL_HELP_FAILED_TO_LOAD': 'This content is currently unavailable. Try reloading this page or check back later.',
	'CONTEXTUAL_HELP_DISCLOSURE': 'This content was translated by a machine.',
	'RETURN_TYPE': 'Return Type: ',
	'UNMARK_DATA_SENSITIVE': 'Form data is set to sensitive. Change to normal?',
	'MARK_DATA_SENSITIVE': 'Set form data to sensitive',
	'SENSITIVE_CONFIRMATION_MSG': 'Setting this form data to sensitive marks it for secure storage. Are you sure?',
	'NON_SENSITIVE_CONFIRMATION_MSG': 'Setting this form data to normal no longer marks it as sensitive. Are you sure?',
	'CONFIRM_SENSITIVE_DIALOG_TITLE': 'Mark data as sensitive',
	'CONFIRM_NON_SENSITIVE_DIALOG_TITLE': 'Change data to normal',
	'CONTROL_FILE_UPLOAD': 'File Upload',
	'LABEL_MAX_SIZE': 'Maximum Upload Size',
	'LABEL_ACCEPT': 'Accept only these file types',
	'LABEL_PRIMARY_TEXT': 'Primary Text',
	'LABEL_SECONDARY_TEXT': 'Secondary Text',
	'ACCEPT_INLINE_HELP': 'A string containing one or more unique file type specifiers, separated by commas.',
	'PRIMARY_TEXT_INLINE_HELP': 'Primary text for the file upload.',
	'SECONDARY_TEXT_INLINE_HELP': 'Secondary text for the file upload.',
	'MAX_SIZE_INLINE_HELP': 'Maximum: 2048 KB',
	'FILE_UPLOAD_PRIMARY_TEXT': 'Drag and Drop',
	'FILE_UPLOAD_SECONDARY_TEXT': 'Select files or drop them here.',
	'ARIA_UNION': 'Union Select',
	'ARIA_EXPRESSION ': 'Expression',
	'ZOOM_OPTIONS': 'Zoom options',
	'PREVIEW_LANGUAGE': 'Preview language',
	'LANGUAGES': 'Language',
	'CONTROL_FILE_MANAGER': 'File Manager',
	'CONTROL_FILE_LIST': 'File List',
	'MOCK_FILE_NAME_1': 'File1.pdf',
	'MOCK_FILE_NAME_2': 'File2.jpeg',
	'MOCK_FILE_CREATE_DATE_1': '2022-06-28T10:07:36+00:00',
	'MOCK_FILE_CREATE_DATE_2': '2022-06-29T10:07:36+00:00',
	'ALLOW_DOWNLOAD': 'Enable Download',
	'ALLOW_DELETE': 'Enable Delete',
	'FILE_NAME': 'File Name',
	'CREATED_BY': 'Created By',
	'CREATED_ON': 'Created On',
	'FILE_NO_CONNECTOR_ERROR': 'Configure the connector and resource for this control.',
	'FILE_NO_RESOURCE_ERROR': 'Configure the resource for this control.',
	'LABEL_DELETE_CONFIRMATION': 'Show Confirmation Message',
	'LABEL_REFRESH_BUTTON': 'Show Refresh Button',
	'LABEL_DATE_FORMAT': 'Date Format',
	'DATE_FORMAT_INLINE_HELP': 'Format in which created on should be displayed',
	'REFRESH_BUTTON_INLINE_HELP': 'Check to show refresh button to allow refresh list connector on click',
	'FILE_CONTEXT': 'File Context',
	'ROW_CONTEXT': 'Row Context',
	'OBJECT': 'object',
	'CONTAINER': 'Container',
	'UPLOAD': 'Upload',
	'LIST': 'List',
	'ADD_LIST': 'Add List',
	'ADD_UPLOAD': 'Add Upload',
	'NO_LIST_TAB_TITLE': 'Show a list of files',
	'NO_LIST_TAB_SUBTITLE': 'Add a list to show available or uploaded files. You can also let users download or remove files using this list.',
	'NO_UPLOAD_TAB_TITLE': 'Let users upload files',
	'NO_UPLOAD_TAB_SUBTITLE': 'Add this control to let your users upload files using drag and drop.',
	'GO_TO_CONNECTOR_TAB': 'Go to Container tab',
	'FILES_RESPONSE_ATTRIBUTE': 'Element that contains the list of files',
	'ATTRIBUTE_MAPPING': 'Attribute Mapping',
	'DOWNLOAD': 'Download',
	'FILE_NO_RESPONSE_CONFIGURED_MSG': 'Configure the response to enable this section.',
	'FILE_NO_OPERATION_CONFIGURED_MSG': 'Parameters will appear here after you select an operation.',
	'PARAMETERS': 'Parameters',
	'LABEL_MULTIPLE_UPLOAD': 'Supports multiple uploads',
	'FILES_PARAM': 'Element with list of files',
	'NO_CONNECTOR': 'No Connector?',
	'NO_RESOURCE': 'No Resource?',
	'ERROR_FETCHING_CONNECTORS': 'Failed to fetch connectors',
	'ERROR_FETCHING_RESOURCES': 'Failed to fetch resources',
	'ERROR_FETCHING_OPERATIONS': 'Failed to fetch operations',
	'ERROR_FETCHING_OPERATION_DEFINITION': 'Failed to fetch operation definition',
	'CONNECTOR_NOT_AVAILABLE': 'Could not find connector: {0}',
	'CONNECTOR_RESOURCE_NOT_AVAILABLE': 'Could not find resource: {0}',
	'CONNECTOR_OPERATION_NOT_AVAILABLE': 'Could not find operation: {0}',
	'LABEL_RESIZABLE': 'Resizable',
	'NO_VALUE_SELECTED': 'Select a value',
	'DATE_FORMAT_VALIDATION': '{0} is either an invalid or a deprecated format. Select a valid format from the dropdown',
	'REMOVE_DU_DATA_OBJECT': 'Add Document Understanding data object',
	'COPY_PAYLOAD': 'Copy payload',
	'COPY_FEEDBACK': 'Payload copied',
	'AI_SERVICES_LABEL': 'AI Services',
	'DOCUMENT_UNDERSTANDING': 'Document Understanding',
	'DOCUMENT_TYPE_LABEL': 'Document type',
	'DOCUMENT_TYPE_STEPS_LABEL': 'Steps in model creation',
	'MINIMUM_CONFIDENCE_SCORE_LABEL': 'Minimum confidence score',
	'HIDE_IMAGE_PREVIEW_LABEL': 'Hide document preview',
	'ENABLE_DOCUMENT_BINDING_LABEL': 'Persist document reference in payload',
	'DOCUMENT_BINDING_LABEL': 'Document is bound to: <b>{0}</b>',
	'SHOW_CONFIDENCE_WARNINGS_LABEL': 'Show warnings for low confidence score fields',
	'HIDE_EMPTY_CONTROLS_LABEL': 'Hide fields with no data',
	'HIDE_EMPTY_CONTROLS_INLINE_HELP': 'Hide controls (fields) that have no data when loaded via payload or connector',
	'DU_HIDE_EMPTY_CONTROLS_INLINE_HELP': 'Hide fields that have no data. This might overwrite any visibility related configuration done via events or properties for controls.',
	'HIDE_CONTROLS_ON_LOAD_LABEL': 'Hide controls on load',
	'MESSAGES_LABEL': 'Messages',
	'CHANGE_DOCUMENT_TYPE_TITLE': 'Change document type confirmation',
	'DU_IMAGE_ALT_TEXT': 'Uploaded document will show up here',
	'GENERATE_CONTROLS_BTN_LABEL': 'Generate controls',
	'GENERATED_CONTROLS_PLACEHOLDER': 'Generated controls will show up here',
	'CHANGE_DOCUMENT_TYPE_DESCRIPTION': 'Are you sure you want to change the document type?',
	'CHANGE_DOCUMENT_TYPE_DESCRIPTION_1': 'Changing document type will update the data object type and also delete the auto generated controls.',
	'DU_SUCCESS_MESSAGE_LABEL': 'Success message',
	'DU_FAILURE_MESSAGE_LABEL': 'Failure message',
	'DU_UNKNOWN_DOC_TYPE_MESSAGE_LABEL': 'When uploaded document cannot be recognized',
	'DU_MISMATCHED_DOC_TYPE_MESSAGE_LABEL': 'When uploaded document is of different type',
	'DU_LOW_CONFIDENCE_MESSAGE_LABEL': 'When confidence score is too low',
	'DU_IMAGE_SIZE_LABEL': 'Document display size',
	'DU_IMAGE_SIZE_SMALL_LABEL': 'Small',
	'DU_IMAGE_SIZE_MEDIUM_LABEL': 'Medium',
	'DU_IMAGE_SIZE_LARGE_LABEL': 'Large',
	'CREATE_DU_DATA_DEFINITION_TITLE': 'Create data definition',
	'CREATE_DU_DATA_DEFINITION_DESCRIPTION': 'Data definition for the selected document type',
	'CREATED_DU_DATA_OBJECT': 'Created data object: {0}',
	'GENERATE_CONTROLS_DU_DESCRIPTION': 'Controls generated against the created data definition',
	'PREVIEW_IMAGE': 'Preview image',
	'LABEL_DOCUMENT': 'Document',
	'DOCUMENT_TYPE_REQUIRED': 'Document type is required. Please select one from the list to proceed.',
	'DOCUMENT_TYPE_ERROR': 'Unable to fetch document types. Please try after sometime.',
	'RICH_TEXT_EDITOR': 'Rich Text Editor',
	'DIVIDER': 'Divider',
	'DOWNLOAD_ON_DEMAND_LABEL': 'Download document on demand',
	'HIDE_FILE_PICKER_LABEL': 'Hide document upload',
	'DOCUMENT_RENDERER': 'Document renderer',
	'REGENERATE_DATA_DEFINITION_DIALOG_TITLE': 'Regenerate data definition confirmation',
	'REGENERATE_DATA_DEFINITION_DESCRIPTION': 'Please confirm if you want to regenerate the data definition for this document type. This will do the following:',
	'REGENERATE_DATA_DEFINITION_LINE1': 'Update the data definition schema for the control',
	'REGENERATE_DATA_DEFINITION_LINE2': 'Update bindings for all child controls based on the updated definition.',
	'REGENERATE_DATA_DEFINITION_NOTE': 'Please note: This is an irreversible action and might introduce breaking changes at places where this data definition type is used.',
	'NO_SELECTION_LABEL': 'No selection'
});
