define({
	COMPOSER: {
		DA: {
			'ADD_BTN': 'Add',
			'EDIT_BTN': 'Edit',
			'VIEW_BTN': 'View',
			'UPDATE_BTN': 'Update',
			'ADD_DATA_OBJECT': 'Add Data Object',
			'EDIT_DATA_OBJECT': 'Edit Data Object',
			'DELETE_DATA_OBJECT': 'Delete Data Object',
			'DATA_OBJECTS': 'Data Objects',
			'DATA_OBJECT': 'Data Object',
			'PREDEFINED_VARIABLES': 'Predefined Variables',
			'PROCESS_DATA': 'Process Data',
			'SUBPROCESS_DATA': 'Subprocess Data',
			'PROCESS_INPUTS': 'Process Inputs',
			'PROCESS_OUTPUTS': 'Process Outputs',
			'BUSINESS_PARAMETERS': 'Business Parameters',
			'DATA_OBJECT_PLACEHOLDER': 'Enter the name of data object',
			'NAME': 'Name',
			'DATA_OBJECT_TYPE': 'Type',
			'BUSINESS_OBJECT': 'Business Object',
			'OK_BTN': 'OK',
			'TRANSFORMATIONS_LIST_EMPTY_TEXT': 'You haven\'t defined any actions',
			'TRANSFORMATION_NAME_ALREADY_EXISTS': 'Transformation name already exists',
			'DATA_OBJECT_HELP': 'Data objects store and organize data the process uses.',
			'DELETE_DATA_OBJECT_CONFIRMATION': 'Are you sure you want to delete \'{dataObjectName}\'?',
			'PROCESS_NAME': 'Process',
			'USER_TASK_NAME': 'User Task',
			'INPUT_NAME': 'input',
			'REMOVE': 'Remove',
			'PAYLOAD_NAME': 'Payload',
			'PAYLOAD_HELP': 'The payload defines what information a node needs to work with.',
			'INPUT_TAB_NAME': 'Input',
			'OUTPUT_TAB_NAME': 'Output',
			'DATA_ASSOCIATION': 'Data Association',
			'APPLY_BTN': 'Apply',
			'SAVE_AS_BTN': 'Save As',
			'DONT_SAVE_BTN': 'Don\'t Save',
			'SAVE_BTN': 'Save',
			'CREATE_BTN': 'Create',
			'DELETE_BTN': 'Delete',
			'CANCEL_BTN': 'Cancel',
			'CLOSE_BTN': 'Close',
			'CLEAR': 'Clear',
			'FILTER_LINK': 'Filter',
			'ACTIONS': 'Actions',
			'YES_BTN': 'Yes',
			'NO_BTN': 'No',
			'UNDO_BTN': 'Undo',
			'REDO_BTN': 'Redo',
			'AUTO_MAPPING_BTN': 'Auto Mapping',
			'NEW_ASSOCIATION': 'New Association',
			'ERROR_MSG': 'Invalid Data Object Name',
			'ERROR_LOWERCASE_DO': 'Data object name should start with lowercase alphabet',
			'ERROR_ALPHANUMERIC_UNDERSCORE': 'Data object name can only contain alphabet, number and underscore',
			'ERROR_DO_EXISTS': 'Data object name already exist',
			'ERROR_DO_EXISTS_IN_VAR': 'Data object name already in use in predefined variables',
			'TRANSFORMATIONS': 'Transformations',
			'SAVE_AS_TITLE': 'Save As',
			'LOADING': 'Loading...',
			'ALL_TRANSFORMATION_TITLE': 'All Actions',
			'NEW_NAME': 'New Name',
			'TRANSFORMATIONS_TITLE': 'Transformations',
			'SAVE_TRANSFORMATION': 'Save Transformation',
			'SAVE_TRANSFORMATION_CONFIRMATION': 'Do you want to save changes to {name}?',
			'RENAME_TRANSFORMATION_TITLE': 'Rename {name}',
			'SEARCH_PLACEHOLDER': 'Search',
			'TRANSFORMATION_INFO': '{sourceLabel} to {targetLabel}',
			'DELETE_TRANSFORMATION_CONFIRMATION': 'Are you sure you want to delete {transformationName}?',
			'TRANSFORMATION_DELETE_WARNING': '(this action cannot be undone)',
			'TRANSFORMATION_USAGE_WARNING': 'Warning: this transformation is being used in:',
			'TRANSFORMATION_ERROR_TITLE': 'Error',
			'SOURCE_TARGET_TRANSFORMATION_TITLE': '{sourceLabel} to {targetLabel} transformations',
			'SOURCE_TARGET_FILTER_TITLE': '{sourceLabel} to {targetLabel} filters',
			'TRANSFORMATION_ALREADY_OPEN': 'Transformation already open in another editor',
			'DELETE_TRANSFORMATION_TITLE': 'Delete {name}',
			'NO_TRANSFORMATION': 'No transformation',
			'USING_TRANSFORMATION': 'Using: {transformationLabel}',
			'INVALID_SELF_REFERENCE': 'Invalid transformation self reference',
			'CHANGE_LINK': 'Change',
			'DEFAULT_SET': 'Default Set',
			'APPEND_SET': 'Append Set',
			'TRANSFORMATION_SET': 'Transformation Set:',
			'DEFAULT_LINK': 'Default',
			'APPEND_LINK': 'Append',
			'TRANSFORM_LINK': 'Transform',
			'INVALID_FILTER': 'Invalid Filter',
			'CHANGE': 'Change:',
			'INVALID_EXPRESSION': 'Invalid expression',
			'TYPE_MISMATCH': 'Types do not match',
			'DATA_TYPE_LABEL': 'Data Type',
			'TRANSFORMATION_TITLE': 'Transformation',
			'NEW_TRANSFORMATION_TITLE': 'New Transformation',
			'SAVE_CHANGES_TITLE': 'Save Changes',
			'SAVE_CHANGES_MESSAGE': 'You have unsaved changes. Do you wish to save them?',
			'TO_LABEL': 'To',
			'FROM_LABEL': 'From',
			'TRANSFORMATION_HELP_TITLE': 'What is a transformation?',
			'TRANSFORMATION_HELP_BODY': 'A transformation converts types that don’t match. You can define how you want the type of one attribute to be converted to the corresponding type of the other attribute.',
			'ARROW': 'Arrow',
			'ARROW_DESCRIPTOR': 'Arrow descriptor',
			'TITLE_HELP': 'Title help',
			'AUTOCOMPLETE_HELP': 'Toggle between simple and advanced autocomplete mode with $[CTRL+SPACE$]',
			'AUTOCOMPLETE_HELP_2': 'Toggle between normal and expanded expression view with $[CTRL+ENTER$]',
			'INPUT_EXPRESSION': 'Input expression',
			'EXPRESSION_AUTO': 'Auto',
			'EXPRESSION_DATA': 'Data',
			'EXPRESSION_METHOD': 'Methods',
			'AUTOCOMPLETE_RESULTS': 'Autocomplete results',
			'AUTOCOMPLETE_NO_RESULTS': 'No results',
			'SEARCH': 'Search',
			'EXPRESSION_SEARCH_DISABLED': 'Search is not allowed here',
			'EXPRESSION_SEARCH_MINIMUM': 'Enter a minimum of 3 characters to perform the search',
			'ADVANCED_EXPRESSION_AUTO': 'Auto',
			'ADVANCED_EXPRESSION_PROCESS_DATA': 'Process',
			'ADVANCED_EXPRESSION_ACTIVITY_DATA': 'Activity',
			'ADVANCED_EXPRESSION_GLOBAL_DATA': 'Global',
			'LITERAL_MODE': 'Literal mode enabled',
			'EXPRESSION_MODE': 'Expression mode enabled',
			'DRAG_HELP': 'Drag help',
			'AUTO_MAPPING_HELP': 'Auto mapping help',
			'INPUT_OUTPUT_HELP': 'Input output help',
			'OPEN_ACTIONS_HELP': 'Open actions help',
			'EDITOR': 'Editor',
			'HEADER': 'Header',
			'EDIT_BREADCRUMB_NAME': 'Edit breadcrumb name',
			'FILTER_CONDITION': 'Condition',
			'FILTER_HELP_TITLE': 'What is a Filter?',
			'FILTER_HELP_BODY': 'Filter elements from a source array and assign those to a target array, overriding the elements that are already there. Only the elements that meet the condition defined in the filter will appear in the target array',
			'LEARN_MORE': 'Learn More',
			'DATA_ASSOCIATION_HELP_TITLE': 'How to associate data',
			'DATA_ASSOCIATION_HELP_BODY': 'Data association refers to the flow of data in elements in a process. For example, an approval human task activity needs data association for both its input and its output.',
			'DATA_ASSOCIATION_HELP_BODY_2': 'Use the Data Association editor to define input and output for flow elements that need them.',
			'DATA_ASSOCIATION_HELP_DRAG_AND_DROP': 'Create associations in the center editor between data objects you select in the left and right panes. Notice that the panes change when you switch between Input and Output tabs.',
			'DATA_ASSOCIATION_HELP_AUTO_MAPPING': 'Want to start with best guess data association? Click Auto Mapping.',
			'DATA_ASSOCIATION_HELP_TYPE': 'Be sure to click the Input and Output tabs to define mapping both to and from an element if needed.',
			'DATA_ASSOCIATION_HELP_EXP_EDITOR': 'Click the expression editor to include an expression in an association.',
			'DATA_ASSOCIATION_HELP_TRANSFORMATIONS': 'Use Actions to transform data or work with arrays in associations.',
			'DATA_TYPE_DISPLAY': '{dataTypeLabel}{arrayIndicator}',
			'DATA_OBJECT_TOOLTIP': '{dataObjectLabel} ({dataTypeDisplay})',
			'SENSITIVE_DATA_OBJECT_TOOLTIP': '{dataObjectLabel} ({dataTypeDisplay}) - sensitive',
			'UNKNOWN_TYPE': 'Unknown',
			'SIMPLE_TYPE_LABEL': 'Simple',
			'BUSINESS_TYPE_LABEL': 'Business',
			'DEFAULT_DATA_OBJECT_NAME': 'dataObject',
			'INVALID_TRANSFORMATION': 'Invalid transformation',
			'INVALID_ENUM_TRANSFORMATION': 'Only Enum to Enum transformations are valid',
			'INVALID_ENUM_ITEM': 'Invalid Enum item',
			'AUTO_MAPPING_HELP_DESCRIPTION_1': 'Auto mapping finds all the possible associations between sources and targets. The possible sources include any element or attribute that have the same or an assignable data type (i.e. Integer → Double) for the target being analyzed.',
			'AUTO_MAPPING_HELP_DESCRIPTION_2': 'After this, the associations are ordered by relevance and then only the most relevant are applied until the current artifact\'s payload is fully associated (if possible).',
			'AUTO_MAPPING_HELP_DESCRIPTION_3': 'An artifact\'s payload is fully associated when: For the Input, all the targets are associated to a source. For the output, all the sources are associated to a target.',
			'DA_TITLE_HELP_DESCRIPTION_1': 'On the input side, it needs data input into the activity (referred to as its payload).',
			'DA_TITLE_HELP_DESCRIPTION_2': 'On the output side, after the activity has just finished, it needs output from the activity to data objects, to store results for use elsewhere in the process.',
			'DA_DRAG_HELP_DESCRIPTION_1': 'You can drill down and drag and drop objects from a pane to a center editor field, or type a data object or payload name in an editor field.',
			'DA_INPUT_OUTPUT_HELP_DESCRIPTION_1': 'Notice that when the Input tab is selected, data objects display in the left pane and activity objects (payload) display in the right pane. Select the Output tab and the panes switch.',
			'DA_ACTIONS_HELP_DESCRIPTION_1': 'Use Transformations to convert types that don’t match. Use Append to append to arrays. Use Filters to filter array elements.',
			'ENTER_EXPRESSION': "Drop a data object or type an expression.",
			'VIEW_FUNCTIONS': "View functions",
			'FILTERS': "Filters"
		}
	}
});
