define({
    'ADD': 'Add',
    'DECISION': 'Decisions',
    "DESCRIPTION": "Description",
    "NAME": "Name",
    "DELETE": "Delete",
    "LABEL_IDENTIFIER": "Identifier",
    "LABEL_VERSION": "Version",
    "UPDATED_BY": "Updated by",
    "CREATED": "Created",
    "UPDATED": "Updated",
    "STATUS": "Status",
    "CREATED_BY": "Created by",
    "DECISION_DETAILS": "Decision details",
    "PLACEHOLDER_CARD_DESC": "Create a decision to automate decision logic with OIC",
    "DRAFT": "Draft",
    "CONFIGURED": "Configured",
    "ACTIVE": "Active",
    "ACTIVATED": "Active",
    "ACTIVATION": "Activation",
    "DEACTIVATION": "Deactivation",
    "ACTIVATION_IN_PROGRESS": "Activation in progress",
    "DEACTIVATION_IN_PROGRESS": "Deactivation in progress",
    "VALIDATION_IN_PROGRESS": "Validation in progress",
    "EDIT": "Edit",
    "ACTIVATE": "Activate",
    "DEACTIVATE": "Deactivate",
    "SHOW_ALL_DECISIONS": "Showing {0} decision(s)",

    "LABEL_NAME": "Name",
    "LABEL_DESCRIPTION": "Description",
    "PLACEHOLDER_NAME": "Type a name",
    "PLACEHOLDER_IDENTIFIER": "Type an identifier",
    "PLACEHOLDER_VERSION": "Type a version",
    "PLACEHOLDER_DESCRIPTION": "A brief description will help others to understand this decision",

    "CREATE_DECISION": "Create decision",
    "CLONE_DECISION": "Clone decision",
    "CREATE_VERSION": "Create new version",
    "IMPORT_DECISION": "Import decision",
    "ACTIVATE_DECISION": "Activate decision",
    "ENTER_DETAILS": "Enter details",
    "ADD_DECISION": "Add decision",
    "ADD_DETAILS": "Select an option",
    "CANCEL": "Cancel",

    'INVALID_CHARACTERS_IN_NAME_SUMMARY': 'Identifier Name has invalid characters',
    'INVALID_CHARACTERS_IN_NAME_DETAIL': 'Enter an identifier using letters (A-Z), numbers (0-9), periods (.), hyphen(-) and underscore(_). Begin the identifier with a letter (A-Z), and make sure it\'s not longer than 110 characters and should not contain consecutive hyphens(--) or underscores(__).',
    'DUPLICATE_NAME_SUMMARY': 'Name already taken',
    'DUPLICATE_NAME_DETAIL': 'Name {0} already exist. Please try with {1}',
    "DELETE_DECISION_HEADER": "Delete decision",
    "DELETE_DECISION_DESC": "Are you sure you want to delete <b>{0}</b>?",
    "DEACTIVATE_DECISION_HEADER": "Deactivate decision",
    "DEACTIVATE_DECISION_DESC": "Are you sure you want to deactivate <b>{0}</b>?",

    "DECISION_DELETE_SUCCESS": "Decision <b>{0}</b> was marked as deleted successfully.",
    "DECISION_ASSET_SUCCESS": "Decision <b>{0}</b> was <b>{1}</b> successfully.",
    "DECISION_ACTIVATE_IN_PROGRESS": "Decision <b>{0}</b> has been submitted for activation.",
    "DECISION_DEACTIVATE_IN_PROGRESS": "Decision <b>{0}</b> has been submitted for deactivation.",
    "DECISION_ACTIVATED": "Decision <b>{0}</b> has been activated.",
    "DECISION_DEACTIVATED": "Decision <b>{0}</b> has been deactivated.",
    "DECISION_ASSET_FAILED": "Failed to <b>{0}</b> decision <b>{1}</b>.",
    "DECISION_FETCH_FAILED": "Failed to fetch the decision list.",
    'INTERNAL_SERVER_ERROR_TITLE': 'Something went wrong...',
    'INTERNAL_SERVER_ERROR_DESCRIPTION': 'This issue might be temporary. Please try again later.',
    'GO_BACK_TEXT': 'Go back',
    'ACTIVATION_DEACTIVATION_TIMEOUT_DESCRIPTION': '{0} may still succeed. Wait a few minutes and reload this page to check the status of your application.',
    'DECISION_VERSION_VALIDATION_DESC': 'Enter a version number using numbers (0-9) in the following format: major.minor.patch (xx.xx.xxxx). It cannot be longer than 10 characters.',
    'VIEW_ALL_DECISIONS': 'View all {0} decision(s)',
    "DECISION_EDIT_ACTIVATED_MESSAGE": "Decision cannot be edited at this time because it is in one of the states- <b>active</b> or <b>activation in progress</b> or <b>deactivation in progress</b>. Deactivate the decision first and then edit it.",
    "DECISION_STATE": "Decision is in {0} state",
    "CLOSE": "Close",
    "VIEW_ONLY": "View only",
    "CLONED": "Cloned",
    "IMPORTED": "Imported",
    "VIEW": "View",
    "EXPORT": "Export",
    "IMPORT": "Import",
    "CREATE": "Create",
    "CLONE": "Clone",
    "VERSION": "Version",
    "UPLOAD_DMN_FILE": "Upload a .dmnx file",
    "BACK_TEXT": "Back",
    "SELECT_OR_DROP_FILE": "Select a file or drop one here",
    "NO_FILE_CHOSEN": "No file chosen",
    "INVALID_FILE_TYPE": "File type is not supported.",
    "FILE_TOO_BIG": "Selected file should be less than {0} {1}.",
    "APPLICATION_EXIST_TITLE": "Application already exist",
    "APPLICATION_EXIST_DESC": "A decision with the same name <b>{0}</b> already exists. Please try using a new application name.",
    "ACTIVATE_OVERRIDE_CONFIRMATION":"Activating decision <b>{0} ({1})</b> requires deactivating decision <b>{0} ({2})</b>.<br>Are you sure you want to deactivate decision <b>{0} ({2})</b>?"
});