define({
	'ADD': 'Add',
	'ADD_ANNOTATION': 'Add Annotation',
	'ADD_COLUMN_AFTER': 'Add Column After',
	'ADD_COLUMN_BEFORE': 'Add Column Before',
	'ADD_COMPONENT': 'Add Component',
	'ADD_CONDITION': 'Add Condition',
	'ADD_DATA_TYPE': 'Add Type Definition',
	'ADD_DECISION_LOGIC': 'Add Decision Logic',
	'ADD_DECISION_QUESTION': 'Add Question',
	'ADD_DESCRIPTION': 'Add Description',
	'ADD_ENTRY': 'Add Entry',
	'ADD_FUNCTION_PARAMETER': 'Add function parameter',
	'ADD_ITEM': 'Add item',
	'ADD_NEW_INPUT_DATA': 'Add new input data',
	'ADD_NEW_ITEM_DEFINITION': 'Add new item definition',
	'ADD_POSSIBLE_ANSWERS': 'Add possible answers',
	'ADD_ROW': 'Add row',
	'ADD_ROW_AFTER': 'Add Row After',
	'ADD_ROW_BEFORE': 'Add Row Before',
	'AFTER': 'After',
	'ALLOWED_ANSWERS': 'Allowed Answers',
	'ALL_APPLICATIONS': 'All Decision Models',
	'ALWAYS_STARTS_WITH_ALPHABET': 'Must start with an alphabet',
	'ANNOTATION': 'Annotation',
	'ANY': 'Any',
	'ANY_HITPOLICY_DESC': 'The Any hit policy is used when multiple rules can match the input, but the output value is the same for all matching rules',
	'ANY_PLACEHOLDER': 'Only - allowed in Any mode',
	'APP_NAME': 'Decision Service',
	'AUTO': 'Auto',
	'BEFORE': 'Before',
	'BETWEEN': 'between',
	'BODY': 'Body',
	'BOOLEAN': 'True or False',
	'BUILD_SIMPLE_OR_COMPLEX_DECISION': 'Build simple or complex logic using decision tables, expressions, if-then-else, and other logic types.',
	'CANCEL': 'Cancel',
	'CANT_BE_EMPTY': 'Can\'t be empty',
	'CANT_HAVE_START_NUMBER': 'Cannot start with a number',
	'CANT_REPEAT_NAME': 'Must be unique',
	'DUPLICATE_NAME': 'Must be unique, Can\'t use existing {0} name here',
	'CHANGE_BODY': 'Change body',
	'CHANGE_HIT_POLICY_VALUE': 'Change hit policy value',
	'CHANGE_VALUE': 'Change Value',
	'CLOSE': 'Close',
	'CLOSE_PANEL': 'Close Panel',
	'COLLECT_HITPOLICY_DESC': 'The Collect hit policy is used when multiple rules can match the input, and a list of output values for all the matching rules is desired',
	'COMPLEX': 'Complex',
	'COMPONENTS': 'Components',
	'CONFIG_TYPE': 'Mode',
	'CONFIRMATION_MESSAGE_DEFAULT': 'Are you sure you want to proceed with your action?',
	'CONFIRMATION_TITLE_DEFAULT': 'Please confirm your action',
	'CONSTRAINT': 'Constraint',
	'CONTEXT': 'Context',
	'CONTEXT_DESC': 'Start with a logic using collection of n pairs',
	'CONTEXT_DESC_FULL': 'Start with a logic using collection of n pairs',
	'COPY': 'Copy',
	'TEXT_COPIED': 'Text Copied',
	'COUNT_HITPOLICY_DESC': 'The Collect with count hit policy is used when multiple rules can match the input, and the count of the matching rules is desired',
	'CREATE': 'Create',
	'CREATE_A_DECISION_MODEL': 'Create a Decision Model',
	'CREATE_A_SERVICE_AS_REST': 'Create a service to expose one or more output decisions.',
	'CREATE_DECISION': 'Create Decision',
	'CREATE_DMN': 'Create a Decision Model',
	'CREATE_DMN_IMPORT': 'Create Decision Model Using Import',
	'CREATE_NEW_DECISION': 'Create a New Decision Model',
	'CREATE_NEW_TYPE': 'Create new type',
	'CTX_DESC': 'Create a list of named logic elements, where logic lower in the list may reference logic results higher in the list by name',
	'CUT': 'Cut',
	'DATA': 'Data',
	'DECISION_DEFINITION': 'Decision Definition',
	'DATA_TYPE': 'Data Type',
	'DATA_TYPES': 'Data Types',
	'DATA_TYPE_DEFINITION_EMPTY_TEXT': 'Data type definitions are used to define your input data types.',
	'DATE_TIME': 'Date and Time',
	'DURATION': 'Duration',
	'DATE_TIME_PLACEHOLDER': 'Enter a date or date and time',
	'DD_DECISIONS': 'Drag and Drop decisions from the list',
	'DD_INPUT_DATA': 'Drag and Drop Input data from the list',
	'DD_INPUT_DATA_HERE': 'Drag & Drop Input Data here',
	'DD_OUTPUT_DECISIONS': 'Drag & Drop Output Decisions here',
	'DECISIONS': 'Decisions',
	'DECISION_ICON': 'Decision Logic',
	'DECISION_MODEL': ' Decision Model',
	'DECISION_MODEL_SER': 'Decision Modeling Service',
	'DECISION_PROPERTIES': 'Decision Properties',
	'DECISION_RULE_INPUT': 'Decision Rule Input',
	'DECISION_RULE_OUTPUT': 'Decision Rule Output',
	'DECISION_SCRIPT': 'Decision Script',
	'DECISION_TABLE': 'Decision Table',
	'DECISION_TABLE_CONFIGURATION': 'Decision Table Configuration',
	'DECISION_TABLE_DESC': 'Create a table of rules with tests matching inputs on the one side, and output on the other side',
	'DECISION_TABLE_DESC_FULL': 'Start with a logic to model complex decisions in a tabular representation',
	'DECISION_TABLE_INPUT_HELP': 'A cell entry is matched when the input expression’s value matches the cell’s value.',
	'DEFINE_ATTRIBUTES': 'Define Attributes',
	'DEFINE_DATA_AND_TYPE_INPUT': 'Define the data and type input needed for your decisions.',
	'DEFINE_DATA_TYPE': 'Define Data Type',
	'DEFINE_TYPE_ATTRIBUTES': 'Define Type Attributes',
	'DELETE': 'Delete',
	'DESCRIPTION': 'Enter a description',
	'DESC_DMN': 'Description for the Decision Model',
	'DETAILS': 'Details',
	'DIFFERENT_TYPES': 'Min and max values should be of the same type.',
	'DMN': 'DMN',
	'DMN_USE_INVALID_FORMAT_NAME': 'No special characters allowed.',
	'DMN_WELCOME_MSG': 'Jump right in and start by creating new application, walk through a sample application or explore our instructional videos to learn more how decision models are designed and deployed.',
	'DONE': 'Done',
	'DT_CONFIG': 'Decision Table Configuration',
	'DUPLICATE_DECISION_NAME': 'Decision name must be unique',
	'DUPLICATE_INPUT_NAME': 'Input name must be unique',
	'DUPLICATE_NAME_HEADER': 'Duplicate Name',
	'EDIT': 'Edit',
	'VIEW': 'View',
	'EDIT_COMPONENT': 'Edit Component',
	'EDIT_DECISION': 'Edit Decision',
	'EDIT_DMN': 'Edit Decision Model',
	'EDIT_INPUT_DATA': 'Edit Input Data',
	'EDIT_ITEM_DEFINTION': 'Edit item definition',
	'EDIT_TYPE': 'Edit Type',
	'ELSE': 'else',
	'ELSE_IF': 'else if',
	'ELSE_IF_BUTTON_LABEL': 'Add Else If',
	'ELSE_IF_THEN': 'If-Then-Else',
	'ELSE_IF_THEN_DESC': 'Create logic with three logic parts: If (Boolean test), Then (result if the test is true), and Else (result if the test is not true)',
	'EMPTY_LOGIC': 'Empty Logic',
	'EMPTY_LOGIC_DESC': 'Create placeholder logic you can change and complete later',
	'ENTER_A': 'Enter a {0}',
	'ENTER_COLUMN_NAME': 'Enter column name here',
	'ENTER_COMMA_SEPERATED': 'Enter comma separated value ',
	'ENTER_EXPRESSION': 'Enter Expression',
	'ENTER_HEADER_VALUES': 'Enter Header Values',
	'ENTER_KEY_HERE': 'Enter key here',
	'ENTER_LIST_OF': 'Enter list of {0}',
	'ENTER_NAME': 'Enter name',
	'ENTER_VALUE': 'Enter value',
	'ENTER_VALUE_HERE': 'Enter value here ',
	'ENTER_VALUE_HIGH': 'Enter higher value ',
	'ENTER_VALUE_LOW': 'Enter lower value',
	'ENTER_VALUE_MATCHED': 'Enter values which matches the test',
	'ERROR': 'Error',
	'VALIDATION_ERROR': 'Validation error',
	'ERRORS_AND_WARNINGS': 'Validation errors/warnings',
	'ERROR_MESSAGE': 'Error: {errorMessage}',
	'EVERY': 'Every',
	'EXCLUSIVE': 'Exclusive',
	'EXPAND_TABLE': 'Expand Table',
	'EXPORT': 'Export',
	'EXPOSE_AS_REST_SERVICE': 'Expose your main decision and input data as a public RESTful service.',
	'EXPRESSION': 'Expression',
	'EXPRESSION_DESC': 'Start with a simple logic expression',
	'EXPRESSION_DESC_FULL': 'Start with a simple logic expression',
	'EXPR_DESC': 'Create logic that evaluates to a single value by entering text using FEEL (Friendly Enough Expression Language)',
	'FILL_IN_TEST_DATA': 'Fill in the required data fields provided below to start the test',
	'FIX_JSON_SYNTAX_ERROR': 'Please correct the sytax errors.',
	'FIRST_HITPOLICY_DESC': 'The First hit policy is used when multiple rules can match the input. The first hit by rule order is returned.',
	'FOR': 'For',
	'FUNCTION': 'Function',
	'FUNCTION_DESC': 'Create parameterized logic to apply multiple times with different parameter values',
	'FUNCTION_DESC_FULL': 'Start with a logic to model using parameter and body of a function',
	'FUNCTION_INTREPRETATION': 'This is a function expression. Please check results in the expression where it is used.',
	'GO_BACK': 'Go Back',
	'GREATER_THAN': 'greater than',
	'GREATER_THAN_EQUAL': 'greater than equals',
	'HANDS_ON_LEARN': 'Hands on the FEEL notation. Learn all the tips of this new and natural script language',
	'HELP_TEXT_ANY': 'Use this option to specify that there are no restrictions on input entries',
	'HELP_TEXT_AUTO': 'This is the default selection for a new input column',
	'HELP_TEXT_BOOLEAN': 'Use this option to permit only Boolean entries',
	'HELP_TEXT_CONSTRAINT': 'Use this option to restrict input entries to a given list of values, limit, or range',
	'HELP_TEXT_LIST_OF_DATE_TIME': 'Use this option to restrict input entries to a given list of date and time values',
	'HELP_TEXT_LIST_OF_TEXT': 'Use this option to restrict input entries to a given list of strings',
	'HIT_POLICY': 'Hit Policy',
	'IF': 'if',
	'IF_THEN_ELSE': 'If-Then-Else',
	'IN': 'in',
	'INCLUSIVE': 'Inclusive',
	'INPUT_COL_CONFIG': 'Decision Table Input',
	'INPUT_DATA': 'Input Data',
	'DATATYPES': 'Datatypes',
	'INPUT_EXPRESSION': 'Input Expression',
	'INPUT_PROPERTIES': 'Input Properties',
	'INTERNAL_SERVER_ERROR_TITLE': 'Something went wrong...',
	'INTERNAL_SERVER_ERROR_DESCRIPTION': 'This issue might be temporary. Please try again later.',
	'INVALID_FORMAT': 'Invalid format',
	'IP_DELETE_CONFIRMATION': 'Are you sure you want to delete this input data?',
	'IS_LIST': 'is List ?',
	'LABEL_ADD_INPUT_DATA': 'Add Input Data',
	'LABEL_EDIT_INPUT_DATA': 'Edit Input Data',
	'LABEL_OTHER_TYPE': 'Type Definitions',
	'LESS_THAN': 'less than',
	'LESS_THAN_EQUAL': 'less than equals',
	'LIST': 'List',
	'LIST_DESC': 'Create a list of independent logic elements whose output contains outputs of all logic elements',
	'LIST_OF_VALUES': 'list of values',
	'LOOP': 'Loop',
	'LOOP_TYPE': 'Loop type',
	'LOOP_DESC': 'Create a logic to iterate over a list and return an expression (For) or to test if every list item (Every) or at least one list item (Some) satisfies the test condition defined by an expression.',
	'MAX': 'Max',
	'MAX_HITPOLICY_DESC': 'The Collect with max hit policy is used when multiple rules can match the input, and the largest output value for all matching rules is desired',
	'MIN': 'Min',
	'MIN_HITPOLICY_DESC': 'The Collect with min hit policy is used when multiple rules can match the input, and the smallest output value for all matching rules is desired',
	'MIN_MAX_VALIDATION_ERROR': 'Cannot be greater than the maximum value.',
	'MORE': 'More',
	'MSG_DELETE_ONLY_NODE_CONFIRMATION': 'Click "Only node" to delete only this node',
	'MSG_DELETE_NODE_LOGIC_CONF': 'Click "Both node and logic" to delete this node and its logic',
	'MSG_EXISTING_DECISION_SELECTION': 'Select existing decisions from menu',
	'MSG_EXISTING_INPUTDATA_SELECTION': 'Select existing input data from menu',
	'MSG_NEW_DECISION': 'Enter name to create a new decision',
	'MSG_NEW_INPUTDATA': 'Enter name to create a new input data',
	'MULTIPLE_OUTPUT_DECISIONTABLE': 'Decision Table',
	'MULTIPLE_OUTPUT_DECISIONTABLE_DESC': 'Create a table of rules with tests matching inputs on the one side, and multiple outputs with annotations on the other side',
	'NAME': 'Name',
	'NAME_DMN': 'Name of the Decision Model',
	'NAME_OR_EXPRESSION': 'Name or Expression',
	'NEW_DMN': 'New Decision Model',
	'NOT': 'Not',
	'NO_RESULTS': 'No Results Found',
	'NUMBER_PLACEHOLDER': 'Enter a number',
	'OK': 'OK',
	'OPERATION': 'Operation',
	'OTHER_TYPE': 'Other Type',
	'OTHER_TYPES': 'Other Types',
	'OUTPUT_COL_CONFIG': 'Decision Table Output',
	'OUTPUT_DECISIONS': 'Output Decisions',
	'OUTPUT_IS': 'Output is: ',
	'PARAMETERS': 'Parameters',
	'PASTE': 'Paste',
	'PAYLOAD': 'Payload',
	'PRECONDITION_FAILED_ERROR': 'An error occurred while saving the data. Page will be reloaded to restore the state.',
	'PRIORITY_HITPOLICY_DESC': 'The Priority hit policy is used when multiple rules can match the input.The matching rule with the highest output priority is returned.The priority is defined by the order of output values in the decision table output column header',
	'PROBLEMS': 'Problems',
	'RECENT': 'Recent',
	'RELATION': 'Relation',
	'RELATION_DESC': 'Create a relational table where each cell contains a logic element',
	'REMOVE_COLUMN': 'Remove Column',
	'REMOVE_DECISION': 'Remove Decisions',
	'REMOVE_INPUT_DATA': 'Remove Input Data',
	'REMOVE_ITEM': 'Remove Item',
	'REMOVE_PARAMETER': 'Remove Parameter',
	'REMOVE_ROW': 'Remove Row',
	'REMOVE_SERVICE': 'Remove Service',
	'REQUEST_PAYLOAD': 'Request Payload',
	'RESERVED_WORD': 'Can\'t be a reserved word',
	'RESERVED_WORDS_NOT_ALLOWED': 'Reserved words({0}) are not allowed',
	'RESPONSE_PAYLOAD': 'Response Payload',
	'RESULTS': 'Results',
	'RETURN': 'return',
	'RULE_OUTPUT_HELP': 'An output cell entry is matched when all input cells in its row match.',
	'RULE_TEST_HELP': 'Enter values to match with the test expression.',
	'SAMPLE_DATA': 'Sample Data',
	'SATISFIES': 'Satisfies',
	'SAVE': 'Save',
	'SAVED_AT': 'Last Saved: {0}',
	'SAVING': 'Saving...',
	'SCRIPT': 'Script',
	'SELECT_DECISION_LOGIC': 'Select the decision logic',
	'SELECT_TYPE': 'Select type',
	'SELECT_MODE': 'Select mode',
	'SELECT_MAX_VAL': 'Select maximum value',
	'SELECT_MIN_VAL': 'Select minimum value',
	'SELECT_ALLOWED_VALUE': 'Select Allowed Value',
	'SELECT_TYPED_DEF': 'Select Typed Definition',
	'SELECT_RANGE_OPER_TYPE': 'Select range operaton type',
	'SERVICE': 'Service',
	'SERVICE_PAYLOAD_SUB_PANEL': 'Service Payload',
	'SERVICES_PROPERTIES': 'Services',
	'SERVICES_SUB_PANEL': 'Add Decision Service',
	'SINGLE_VALUE': 'Value',
	'SOME': 'Some',
	'START_TEST': 'Start Test',
	'SWITCH_TO_DURATION_MODE': 'Switch to duration mode',
	'SWITCH_TO_DATE_AND_TIME_MODE': 'Switch to date and time mode',
	'SUM_HITPOLICY_DESC': 'The Collect with sum hit policy is used when multiple rules can match the input, and the sum of the output values for all the matching rules is desired',
	'TABLE_ACTIONS': 'Table Actions',
	'TEST_PROPERTIES': 'Test Decision Model',
	'PALETTE_PROPERTIES': 'Palette',
	'TEXT_PLACEHOLDER': 'Enter unquoted text',
	'THEN': 'then',
	'TITLE_ADD_NEW_SERVICE': 'Add new service',
	'TITLE_ALLOWED_ANSWER': 'Allowed Answers',
	'TITLE_ALLOWED_VALUES': 'Allowed Values',
	'TITLE_DELETE_CONF': 'Delete Confirmation',
	'TITLE_DESCRIPTION': 'Description',
	'TITLE_DIAGRAM_PALETTE': 'Diagram palette',
	'TITLE_LOGIC': 'Logic',
	'TITLE_OUTPUT_TYPE': 'Output Type',
	'TITLE_QUESTION': 'Question',
	'TRUE_FALSE_PLACEHOLDER': 'Enter true or false',
	'TYPE': 'Type',
	'TYPED_DEF_PROPERTIES': 'Typed Definition Properties',
	'TYPE_DELETE_CONFIRMATION': 'Are you sure you want to delete this type definition?',
	'UNIQUE_HITPOLICY_DESC': 'The Unique hit policy is used when at most 1 rule can match the input',
	'URL': 'URL',
	'USAGE_TIPS': 'Usage Tips',
	'VALUE': 'value',
	'VALUES': 'Values',
	'WHERE_KEYWORD': 'where',
	'YES': 'Yes',
	'NEVER_END_WITH_SPACE': 'Space at the end is not allowed',
	'SPACE_NOT_ALLOWED': 'Space not allowed',
	'AVAILABLE_TYPES': 'Available Types',
	'TYPE_LISTING': 'Types',
	'NEW_TYPE': 'New Type',
	'NEW_TYPE_ATTRIBUTE': 'New Type Attribute',
	'EDIT_TYPE_ATTRIBUTE': 'Edit Type Attribute',
	'TYPE_NAME': 'Name',
	'TYPE_MODE': 'Mode',
	'NUMBER': 'Number',
	'TEXT': 'Text',
	'MAKE_LIST': 'Make a list',
	'BACK': 'Back',
	'ENTER_LIST_VALUES': 'Enter comma (,) separated values',
	'ENTER_LIST_VALUES_MULTILINE': 'Press enter after each value',
	'SWITCH_TO_LIST_MODE': 'Switch to list mode',
	'SWITCH_TO_COMMA_SEPARATED_MODE': 'Switch to comma separated mode',
	'LIST_VIEW': 'List view',
	'COMMA_SEPARATED_VIEW': 'Comma separated view',
	'DECISION_SERVICE': 'Decision Service',
	'OPEN_DECISION_SERVICE': 'Open Decision Service',
	'PAN_MODE': 'Pan Mode',
	'SELECTION_MODE': 'Selection Mode',
	'MAXIMIZE_VIEW': 'Maximize view',
	'MINIMIZE_VIEW': 'Minimize view',
	'ZOOM_TO_FIT': 'Zoom To Fit',
	'ZOOM_IN': 'Zoom In',
	'ZOOM_OUT': 'Zoom Out',
	'SHOW_TYPEDEF_LIST': 'Show type definition list',
	'SELECT_PARAMETER_TYPE': 'Select parameter type',
	'PROPERTIES': 'Properties',
	'ENTER_ALLW_VAL': 'Enter Allowed Values',
	'ADVANCED': 'Advanced',
	'VALUE_LABEL': 'Value',
	'UNDO': 'Undo',
	'REDO': 'Redo',
	'KEY': 'Key',
	'ADD_PARAMETER': 'Add Parameter',
	'PARAMETER_NAME': 'Parameter Name',
	'WARNING': 'Warning',
	'ONLY_NODE': 'Only node',
	'BOTH_NODE_LOGIC': 'Both node & logic',
	'DECISION': 'Decision',
	'OR': 'or',
	'CANVAS_AREA_HELPTEXT': 'Drag and drop elements from the Diagram palette to model your decisions',
	'LEARN_MORE': 'Learn more about the diagrams',
	'ADD_RESULT': 'Add Result',
	'IDENTIFIER_NAME': 'Identifier:',
	'SERVICE_DELETE_CONFIRMATION': 'Are you sure you want to delete this service?',
	'DESCRIPTION_LABEL': 'Description',
	'REFRESH_APP': 'Please click "OK" to continue, as there is a more recent update available.\n This will refresh your application with the most recent changes.',
	'JSON_SCHEMA': 'Schema',
	'JSON_SAMPLE': 'Sample',
	'JSON_MODEL': 'Model',
	'NEXT': 'Next',
	'IMPORT_JSON': 'Import from sample',
	'IMPORT_SCHEMA': 'Import from schema',
	'IMPORT_TYPE': 'Import type',
	'SEARCH_PLACEHOLDER': 'Search node in canvas',
	'SEARCH': 'Search',
	'DISABLE_HIGHLIGHT_MODE': 'Disable highlight mode',
	'ENABLE_HIGHLIGHT_MODE': 'Enable highlight mode',
	'RESET_VIEW': 'Reset view',
	'COLLAPSE_OVERVIEW': 'Collapse overview',
	'EXPAND_OVERVIEW': 'Expand overview',
	'LOADING': 'Loading ...',
	'LOADING_DESCRIPTION': 'Fetching {0} content',
	"SELECT_VALID_TYPE": "Please select or enter the valid type name",
	'DRAG': 'Drag',
	"HITPOLICY_UNIQUE": "Unique (U)",
	"HITPOLICY_ANY": "Any (A)",
	"HITPOLICY_FIRST": "First (F)",
	"HITPOLICY_PRIORITY": "Priority (P)",
	"HITPOLICY_COLLECT": "Collect (C)",
	"HITPOLICY_SUM": "Collect Sum (C+)",
	"HITPOLICY_MIN": "Collect Min (C<)",
	"HITPOLICY_MAX": "Collect Max (C>)",
	"HITPOLICY_COUNT": "Collect Count (C#)",
	"MAXIMIZE": "Maximize",
	"MINIMIZE": "Minimize"
});