define({
	PROCESS: 'Workflow',
	FORM: 'Form',
	ADD: 'Add',
	ADD_PROCESS: 'Add Workflow',
	CREATE_PROCESS: 'Create Workflow',
	CLONE_PROCESS: 'Clone Workflow',
	ACTIVATE_PROCESS: 'Activate workflow',
	ACTIVATE_FORM: 'Activate form',
	CREATE_VERSION: 'Create new version',
	CREATE_FORM: 'Create Form',
	VERSION: 'Version',
	ENTER_DETAILS: 'Enter details',
	CHOOSE_PROCESS_TEMPATE_DESCRIPTION: 'Choose pattern',
	CANCEL: 'Cancel',
	CLOSE: 'Close',
	CREATE: 'Create',
	IMPORT: 'Import',
	BACK_TEXT: 'Back',
	LABEL_NAME: 'Name',
	LABEL_IDENTIFIER: 'Identifier',
	LABEL_VERSION: 'Version',
	UPDATED_BY: 'Updated by',
	CREATED: 'Created',
	CREATED_BY: 'Created by',
	PLACEHOLDER_NAME: 'Type a name',
	PLACEHOLDER_IDENTIFIER: 'Type an identifier',
	PLACEHOLDER_VERSION: 'Type a version',
	PLACEHOLDER_DESCRIPTION: 'A brief description will help others to understand this workflow',
	PROCESS_ASSET_SUCCESS: 'Workflow <b>{0}</b> was <b>{1}</b> successfully.',
	PROCESS_PLACEHOLDER_CARD_DESC: 'Create an OIC Workflow',
	FORM_PLACEHOLDER_CARD_DESC: 'Create an OIC Form',
	VIEW_ALL_PROCESS: 'View all {0} workflows',
	VIEW_ALL_FORM: 'View all {0} forms',
	DELETE_PROCESS_HEADER: 'Delete workflow',
	DELETE_PROCESS_DESC: 'Are you sure you want to delete <b>{0}</b>?',
	PROCESS_DELETE_SUCCESS: 'Workflow <b>{0}</b> was marked as deleted successfully.',
	PROCESS_CLONE_SUCCESS: 'Workflow <b>{0}</b> was cloned successfully.',
	PROCESS_VERSION_SUCCESS: 'Workflow <b>{0}</b> was versioned successfully.',
	PROCESS_ACTIVATE_SUCCESS: 'Workflow <b>{0}</b> was activated successfully.',
	PROCESS_DEACTIVATE_SUCCESS: 'Workflow <b>{0}</b> was deactivated successfully.',
	FORM_CLONE_SUCCESS: 'Form <b>{0}</b> was cloned successfully.',
	FORM_VERSION_SUCCESS: 'Form <b>{0}</b> was versioned successfully.',
	FORM_ACTIVATE_SUCCESS: 'Form <b>{0}</b> was activated successfully.',
	PROCESS_ACTIVATE_FAILED: 'Failed to <b>{0}</b> workflow <b>{1}</b>.',
	FORM_ACTIVATE_FAILED: 'Failed to <b>{0}</b> form <b>{1}</b>.',
	ACTIVATE_PROCESS_OVERRIDE_CONFIRMATION:
		'Activating workflow <b>{0} ({1})</b> requires deactivating workflow <b>{0} ({2})</b>.<br>Are you sure you want to deactivate workflow <b>{0} ({2})</b>?',
	ACTIVATE_FORM_OVERRIDE_CONFIRMATION:
		'Activating form <b>{0} ({1})</b> requires deactivating form <b>{0} ({2})</b>.<br>Are you sure you want to deactivate form <b>{0} ({2})</b>?',
	PROCESS_ACTIVATE_IN_PROGRESS: 'Process <b>{0}</b> has been submitted for activation.',
	PROCESS_DEACTIVATE_IN_PROGRESS: 'Process <b>{0}</b> has been submitted for deactivation.',
	FORM_ACTIVATE_IN_PROGRESS: 'Form <b>{0}</b> has been submitted for activation.',
	FORM_DEACTIVATE_IN_PROGRESS: 'Form <b>{0}</b> has been submitted for deactivation.',
	FORM_DEACTIVATE_SUCCESS: 'Form <b>{0}</b> was deactivated successfully.',
	INTERNAL_SERVER_ERROR_DESCRIPTION: 'This issue might be temporary. Please try again later.',
	NAME: 'Name',
	IDENTIFIER_NAME: 'Identifier:',
	STATUS: 'Status',
	SELECT_OR_DROP_FILE: 'Select a file or drop one here',
	UPLOAD_PROCESS_FILE: 'Upload an expx file',
	IMPORT_PROCESS: 'Import workflow',
	SHOW_ALL_PROCESS: 'Showing {0} workflow(s)',
	SHOW_ALL_FORM: 'Showing {0} form(s)',
	PROCESS_FETCH_FAILED: 'Failed to fetch the workflow list.',
	PROCESS_DETAILS_FETCH_FAILED: 'Failed to fetch the workflow details.',
	FORM_FETCH_FAILED: 'Failed to fetch the form list.',
	DRAFT: 'Draft',
	ACTIVE: 'Active',
	ACTIVATED: 'Active',
	CONFIGURED: 'Configured',
	ACTIVATION: 'Activation',
	DEACTIVATION: 'Deactivation',
	ACTIVATION_IN_PROGRESS: 'Activation in progress',
	DEACTIVATION_IN_PROGRESS: 'Deactivation in progress',
	VALIDATION_IN_PROGRESS: 'Validation in progress',
	EDIT: 'Edit',
	VIEW: 'View',
	CLONE: 'Clone',
	DELETE: 'Delete',
	PROCESS_LIST_HEADER: 'Workflows',
	FORM_LIST_HEADER: 'Forms',
	FORM_DELETE_HEADER: 'Delete form',
	PROCESS_DELETE_HEADER: 'Delete workflow',
	PROCESS_DELETE_DESC: 'Are you sure you want to delete <b>{0}</b>?',
	FORM_DELETE_DESC: 'Are you sure you want to delete <b>{0}</b>?',
	DESCRIPTION: 'Description',
	PROCESS_DETAILS: 'Workflow details',
	FORM_DETAILS: 'Form details',
	PROPERTIES: 'Properties',
	PROCESS_DATA: 'Workflow Data',
	PROCESS_INPUT: 'Input',
	PROCESS_OUTPUT: 'Output',
	DATA_OBJECTS: 'Data Objects',
	DATA_OBJECT_DEFAULT_NAME: 'dataObject',
	DATA: 'Data',
	ACTIVITY: 'Activity',
	DESCRIPTION_LABEL: 'Description',
	INSTANCE: 'Instance',
	INSTANCE_DESCRIPTION_STP: 'Define properties for instances of this process.',
	TITLE: 'Title',
	TITLE_PLACEHOLDER: 'Enter a title',
	ENTER_EXPRESSION: 'Enter an expression.',
	INPUT_EXPRESSION_HELP: 'Enter a simple expression',
	BUSINESS_KEY: 'Business key',
	EXPRESSION_VALIDATION_ERROR: 'Invalid expression',
	EXPRESSION_VALIDATION_ANY_TYPE: "Cannot assign '{0}' to '{1}'.",
	VIEW_FUNCTIONS: 'View functions',
	DEFAULT_ARGUMENT_NAME_INPUT: 'input',
	DEFAULT_ARGUMENT_NAME_OUTPUT: 'output',
	USERS_AND_CLIENTS_WITH_USE_PERMISSION: 'Role members with at least use permission',
	ALL_USERS_AND_CLIENTS: 'All users and external applications',
	USERS_WITH_USE_PERMISSION: 'Users with Use permission',
	ALL_USERS: 'All Users',
	PARTICIPANT_TYPE: 'Who can run this activity?',
	BACKGROUND_COLOR: 'Background Color',
	ROLE: 'Role',
	PREDEFINED_VARIABLES: 'Predefined Variables',
	ACTIVITY_LOOP: 'Activity Loop',
	CREATE_DATA_OBJECT: 'Create Data Object',
	DELETE_DATA_OBJECT: 'Delete Data Object',
	EDIT_DATA_OBJECT: 'Edit Data Object',
	DATA_TYPE: 'Data Type',
	SIMPLE: 'Simple',
	BUSINESS: 'Business',
	UNKNOWN: 'Unknown',
	VALIDATIONS: 'Validations',
	PROCESS_ACTIVATED: 'Workflow <b>{0}</b> has been activated.',
	PROCESS_DEACTIVATED: 'Workflow <b>{0}</b> has been deactivated.',
	PROCESS_ASSET_FAILED: 'Failed to <b>{0}</b> workflow <b>{1}</b>.',
	ACTIVATION_DEACTIVATION_TIMEOUT_DESCRIPTION:
		'{0} may still succeed. Wait a few minutes and reload this page to check the status of your application.',
	ACTIVATE: 'Activate',
	DEACTIVATE: 'Deactivate',
	VIEW_ONLY: 'View only',
	ASSIGNEES: 'Assignees',
	POLICY: 'Policy',
	ANY_SINGLE_ASSIGNEE: 'Any Single Assignee',
	ALL_ASSIGNEES_IN_PARALLEL: 'All Assignees in Parallel',
	ALL_ASSIGNEES_IN_SEQUENCE: 'All Assignees in Sequence',
	MANAGEMENT_CHAIN_IN_SEQUENCE: 'Management Chain in Sequence',
	PERCENTAGE_REQUIRED: 'Percentage Required',
	DEFAULT_OUTCOME: 'Default Outcome',
	NUMBER_OF_LEVELS: 'Number of Levels',
	SKIP_APPROVAL: 'Skip Approval',
	SELECT_PARTICIPANTS: 'Select Participants',
	ASSIGN_TO: 'Assign to',
	EXCLUDE_FOLLOWING_PARTICIPANTS: 'Exclude the Following',
	CREATOR: 'Creator',
	CREATOR_DESC: 'The user who started the workflow.',
	EXPRESSION: 'Expression',
	TASK_SUMMARY: 'Summary',
	TASK_SUMMARY_PLACEHOLDER: 'Enter a summary',
	END_USER_DISPLAY: 'End User Display',
	ASSIGN_PREVIOUS_TASK_APPROVER: 'Assign to previous task approver in current lane',
	ACTIONS: 'Actions',
	SYSTEM_ACTIONS: 'System actions',
	CUSTOM_ACTIONS: 'Custom actions',
	ENTER_CUSTOM_ACTION: 'Enter custom action',
	SELECT_SYSTEM_ACTIONS: 'Select system action',
	ACTIONS_WITH_COMMENTS: 'Mandate comments on action',
	SELECT_ACTIONS_WITH_COMMENTS: 'Select custom action',
	SYSTEM_ACTIONS_WARNING:
		'Users with manage permission on the application will have all system actions available.',
	PRIORITY: 'Priority',
	LEVEL: 'Level',
	LOW: 'Low',
	NORMAL: 'Normal',
	HIGH: 'High',
	PRIORITY_LOW: 'Low (3)',
	PRIORITY_NORMAL: 'Normal (2)',
	PRIORITY_HIGH: 'High (1)',
	DUE_ON: 'Due on',
	DUE_ON_PLACEHOLDER: 'What is due date?',
	PRESENTATION: 'Presentation',
	SELECT_FORM: 'Select UI',
	DEFAULT_PRESENTATION: 'Default Presentation',
	DATA_BINDING_REFERENCE: 'Data Binding Reference: {0}',
	REMINDER: 'Reminder',
	NO_REMINDER: 'No Reminder',
	REMIND_ONCE: 'Remind Once',
	REMIND_TWICE: 'Remind Twice',
	REMIND_THREE_TIMES: 'Remind Three Times',
	WHEN: 'When',
	BEFORE_EXPIRATION: 'Before Expiration',
	AFTER_ASSIGNMENT: 'After Assignment',
	BEFORE_DUE_DATE: 'Before Due Date',
	IMPLEMENTATION: 'Implementation',
	INTERVAL: 'Interval',
	INTERVAL_HELP: 'How long before the task expires?',
	INTERVAL_RENEWAL_HELP: 'How long before each task assignment expires?',
	MAXIMUM_RENEWALS: 'Maximum Renewals',
	ESCALATION_EXPIRATION_QUESTION: 'Do you want to expire or escalate the user task?',
	NEVER_EXPIRE: 'Never Expire',
	EXPIRE: 'Expire',
	RENEW: 'Renew',
	DISABLE_NOTIFICATION: 'Disable Notification',
	SEND_EMAIL_TITLE: 'Send an e-mail',
	SEND_EMAIL_TO_LABEL: 'To',
	SEND_EMAIL_TO_PLACEHOLDER: 'Send To',
	SEND_EMAIL_CC_LABEL: 'Cc',
	SEND_EMAIL_CC_PLACEHOLDER: 'CC To',
	SEND_EMAIL_BCC_LABEL: 'Bcc',
	SEND_EMAIL_BCC_PLACEHOLDER: 'BCC To',
	SEND_EMAIL_REPLY_LABEL: 'Reply',
	SEND_EMAIL_REPLY_PLACEHOLDER: 'Reply To',
	SEND_EMAIL_SUBJECT_LABEL: 'Subject',
	SEND_EMAIL_SUBJECT_PLACEHOLDER: 'Email Subject',
	SEND_EMAIL_BODY_LABEL: 'Body',
	SEND_EMAIL_BODY_PLACEHOLDER: 'Email Body',
	EMAIL_ERROR_TITLE: 'Email Error',
	EMAIL_ERROR_DETAIL: 'Please add valid email address(es).',
	ON_ASSIGN: 'On Assign',
	ON_ASSIGN_SUBJECT: 'Task {0} created by {1} needs your attention',
	ON_COMPLETE: 'On Complete',
	ON_COMPLETE_SUBJECT: 'Task {0} created by {1} completed successfully',
	ON_ERROR: 'On Error',
	ON_ERROR_SUBJECT: 'Task {0} created by {1} encountered an error',
	DEFAULT_NO_ACTIONS: 'Default',
	DEFAULT_WITH_ACTIONS: 'Default (With Actions)',
	USE_PARENT_TEMPLATE: 'Use Parent Template',
	SELECT_EMAIL_TEMPLATE_HEADER:
		'Select an Email Template for Notifications, Reminders, Escalation/Expiration',
	EMAIL_TEMPLATE: 'Email Template',
	SELECT_EMAIL_SUBJECT_HEADER: 'Specify when email is sent & customize its template and subject',
	INCLUDE_AS_EMAIL_ATTACHMENTS: 'Include form in email attachments as',
	MANAGE_EMAIL_TEMPLATES: 'Manage Email Templates',
	DELETE_EMAIL_TEMPLATES_CONFIRMATION_MSG: 'Delete {0}?',
	DELETE_CONFIRMATION_WARNING_TEXT:
		'This will delete the template for entire application. Are you sure you want to delete the template?',
	PROPOSED_TEMPLATE_NAME: 'EmailTemplate',
	EDITING_TEMPLATE_LOCKED_MSG:
		'This template is currently being edited by {0}. You will be able to modify the template once {0} finishes.',
	TEMPLATE_LOCKED_MSG: 'Template {0} is locked by {1}.',
	DEFAULT: 'Default',
	DOWNLOAD: 'Download',
	COPY: 'Copy',
	LOAD_MORE: 'Load more',
	CONDITIONAL_FLOW: 'Conditional Flow',
	CONDITION: 'Condition',
	CONDITION_TEXT:
		'Marking a transition as default will make the default condition as conditional and remove the condition expression.',
	ESCALATE: 'Escalate',
	ESCALATION_EXPIRATION: 'Escalation and Expiration',
	ESCALATION_COMMENT_TITLE: 'Comment',
	ESCALATION_COMMENT:
		'This task has been escalated as no action was taken within the pre-defined expiry period.',
	TASK_ATTACHMENTS: 'Task Attachments',
	SELECTED: 'Selected',
	MEMBERS: 'Users',
	ROLES: 'Roles',
	GROUPS: 'Groups',
	EXPRESSIONS: 'Expressions',
	IDENTITY_SEARCH_PLACEHOLDER: 'Search users, roles, organizations',
	CREATE_EXPRESSION: 'Create Expression',
	EDIT_EXPRESSION: 'Edit Expression',
	APPLY: 'Apply',
	ARGUMENTS_DEFINITION_TITLE: 'Input Payload Definition',
	CONFIGURE: 'Configure',
	ENTER_JSON_OPTION_DELIMETER: '-OR-- enter sample JSON',
	INLINE: '<<<inline>>>',
	SELECTED_FILE: 'Selected files:',
	CREATE_AN_EMAIL_TEMPLATE: 'Create an Email Template',
	EDIT_EMAIL_TEMPLATE: 'Edit Email Template',
	PREVIEW_EMAIL_TEMPLATE: 'Preview Email Template',
	EMPTY_TEMPLATE_CONTENT_MESSAGE: 'Email template content must not be empty.',
	ERROR_TEMPLATE_NAME_EXISTS: 'Email template name already exists.',
	ERROR_TEMPLATE_INVALID_NAME:
		"Enter a name using letters (A-Z), numbers (0-9), periods (.), hyphen(-) and underscore(_). Begin the name with a letter (A-Z), and make sure it's not longer than 110 characters and should not contain consecutive hyphens(--) or underscores(__).",
	PREVIEW: 'Preview',
	PREVIOUS: 'Previous',
	NOTIFICATIONS: 'Notifications',
	EMAIL_TEMPLATE_PLACEHOLDER: 'Add email template HTML here...',
	FINISH: 'Finish',
	INVALID_FILE_CONTENT: 'Invalid file content',
	AUTOCOMPLETE_RESULTS: 'Autocomplete results',
	AUTOCOMPLETE_NO_RESULTS: 'No results',
	EXPRESSION_SEARCH_DISABLED: 'Search is not allowed here',
	EXPRESSION_SEARCH_MINIMUM: 'Enter a minimum of 3 characters to perform the search',
	ADVANCED_EXPRESSION_AUTO: 'Auto',
	ADVANCED_EXPRESSION_PROCESS_DATA: 'Process',
	ADVANCED_EXPRESSION_ACTIVITY_DATA: 'Activity',
	ADVANCED_EXPRESSION_GLOBAL_DATA: 'Global',
	EXPRESSION_REQUIRED_SUMMARY: 'Value is required',
	EXPRESSION_REQUIRED_DETAIL: 'Expression can not be empty',
	EXPRESSION_INTERVAL_SUMMARY: 'Format is incorrect',
	EXPRESSION_INTERVAL_DETAIL:
		'Format should match the expression: (0-9M)(0-9D)(0-9d)(0-9H)(0-9h)(0-9m)(0-9S)(0-9s)',
	LITERAL_MODE: 'Literal mode enabled',
	EXPRESSION_MODE: 'Expression mode enabled',
	REQUEST_FOR_INFO: 'Request Info',
	REASSIGN: 'Reassign',
	RELEASE: 'Release',
	WITHDRAW: 'Withdraw',
	SEARCH: 'Search',
	ASSOCIATE: 'Associate',
	UI: 'UI',
	SEARCH_OIC_FORM: 'Search OIC form',
	OIC_PROJECT: 'OIC project',
	instanceList: {
		ASSET_NAME: 'Instances',
		VIEW_AUDIT: 'View audit',
		SEARCH_INPUT_PLACEHOLDER_TEXT: 'Search by process name, title, created by',
		STATUS: 'Status',
		ALL: 'All',
		IN_PROGRESS: 'In progress',
		COMPLETED: 'Completed',
		TERMINATED: 'Terminated',
		SUSPENDED: 'Suspended',
		FAULTED: 'Faulted',

		CREATED_DATE: 'Created date',
		DATE_RANGE: 'Date range',
		TIME_WINDOW: 'Time window',
		LAST_1_HOUR: 'Last 1 hour',
		LAST_6_HOUR: 'Last 6 hour',
		LAST_1_DAY: 'Last 1 day',
		LAST_2_DAYS: 'Last 2 days',
		LAST_3_DAYS: 'Last 3 days',
		LAST_8_DAYS: 'Last 8 days',
		LAST_32_DAYS: 'Last 32 days',

		CREATED_BY: 'Created by',
		ENTER_USERNAME: 'Enter username',
		PROCESS_NAME: 'Process name',
		ENTER_PROCESS_NAME: 'Enter process name',
		PROCESS_TITLE: 'Process title',
		ENTER_PROCESS_TITLE: 'Enter process title',

		INSTANCE_ID: 'Instance id',
		TITLE: 'Title',
		CREATED_ON: 'Created on',

		actions: {
			TERMINATE: 'Terminate',
			SUSPEND: 'Suspend',
			ALTER_FLOW: 'Alter flow',
			RETRY: 'Retry',
			RESUME: 'Resume',
		},

		errorMessages: {
			genericError: {
				title: 'Something went wrong',
				description: 'The issue might be temporary. Try again later.',
			},
			badRequestError: {
				title: 'Bad query',
				description:
					'There seems to be an issue with task list query. Kindly check the query and try again.',
				actionText: '',
			},
			invalidAuthenticationError: {
				title: 'You are not authorized to view task list',
				description: 'Authorization failed - Unauthorized',
			},
			forbiddenPermissionError: {
				title: "You don't have access to view task list",
				description: 'Authorization failed - Permission Denied',
			},
			searchInvalidSyntaxParseError: {
				title: "Couldn't run your search",
				description: 'Review your filters and try again.',
			},
			searchServiceUnavailableError: {
				title: 'Business Search Unavailable',
				description: 'Search is Unavailable right now. Try again later.',
				actionText: '',
			},
			searchServiceServerConnectionError: {
				title: 'Business Search cannot connect with server',
				description: 'Search service cannot connect to server. Try again later.',
				actionText: '',
			},
			searchServiceInvalidFieldNameError: {
				title: 'Invalid field name',
				description:
					'Invalid field name provided in query. Please refer to documentation for the supported field names',
				actionText: '',
			},
		},
	},

	instanceAudit: {
		instanceIdCopiedMsg: 'Instance id copied !',
		copyInstanceIdMsg: 'Copy instance id',
		instanceId: 'Instance id',
		navigateWorkspace: 'Open in workspace',
		activityStream: 'Activity stream',
		payloadText: 'Payload',
		details: 'Details',
		humanTask: 'Human task',
		inProgress: 'In progress',
		fetchProcessDetailErrorMsg: 'Error in fecting process detail.',
		fetchErrorMsg: 'Error occurred while getting the audit details of the instance {0}',
		fetchMultiInstanceDetailsErrorMsg:
			'Error occurred while getting the audit details of the multi instance activity.',
		start: 'Start',
		draft: 'Draft',
		end: 'End',
		serialtaskstatus: 'Serial {0} out of {1} done',
		paralleltaskstatus: 'Parallel {0} out of {1} done',
		managementChainTaskStatus: 'Management Chain {0} out of {1} done',
		singleassignee: 'Single assignee',
		exclusivegateway: 'Exclusive gateway-{0}',
		startevent: 'Start activity-{0}',
		endevent: 'End activity-{0}',
		usertask: 'User task',
		formStartEvent: 'Start form',
		stage: 'Stage',
		milestone: 'Milestone',
		multiInstanceBody: 'Multi Instance Activity',
		notificationTask: 'Notification task',
		usertaskactivity: 'User task activity-{0}',
		multiInstanceTask: 'Multi instance user task',
		multiInstancetaskactivity: 'Multi instance user task activity-{0}',
		multiinstanceactivity: 'Multi instance activity-{0}',
		multiInstanceActivity: 'Multi instance activity',
		userTaskActivity: 'User task activity',
		multiInstanceTaskActivity: 'Multi instance user task activity',
		startactivity: 'Start activity',
		errorStartEvent: 'Error start event',
		messagestartactivity: 'Start message activity',
		starttimeractivity: 'Start timer activity',
		signalstartactivity: 'Start signal activity',
		endactivity: 'End activity',
		callBackEndEvent: 'Call back end activity',
		errorEndEvent: 'Error end event',
		terminateEndEvent: 'Terminate end event',
		callactivity: 'Call activity',
		processactivity: 'Process activity',
		servicetask: 'Service Task',
		uploadform: 'Upload Form',
		integrationActivity: 'Integration activity',
		exclusivegatewayactivity: 'Exclusive gateway',
		inclusivegatewayactivity: 'Inclusive gateway',
		parallelgatewayactivity: 'Parallel gateway',
		complexgatewayactivity: 'Complex gateway',
		subprocessactivity: 'Sub process',
		adhocsubprocessactivity: 'Adhoc sub process',
		errorsubprocessactivity: 'Error sub process',
		businessRuleTask: 'Decision service',
		intermediateTimer: 'Timer catch event',
		boundaryTimer: 'Boundary timer event',
		boundaryError: 'Boundary error',
		intermediateCatchEvent: 'Timer catch event',
		intermediateTimerEndsIn: 'due {0}',
		receiveTask: 'Receive task',
		sendTask: 'Send task',
		activity: 'Activity',
		dataMapper: 'Data mapper',
		payloadHeader: '{0} - {1}',
		inputPayloadHeader: 'Activity Input',
		outputPayloadHeader: 'Activity Output',
		headerLabel: 'Input and Output',
		input: 'View input',
		inputoutput: 'View input and output',
		outputunavailable: 'No output available yet.',
		inputunavailable: 'No input available yet.',
		view: 'View',
		showActivityDetails: 'Show activity details',
		hideActivityDetails: 'Hide activity details',
		alteredflow: 'Altered flow',
		alterflowstatuswithdate:
			'Alter flow was performed by {0} and moved the activity to the target activity {1} {2}',
		alterflowstatus:
			'Alter flow was performed by {0} and moved the activity to the target activity {1} on {2}',
		alterflowcomments: 'Comments: {0}',
		activityFetchErrorMsg: 'Error in fecting audit activities.',
		noErrorActivityMsg: 'No error activity is recorded for this process.',
		activitystate: {
			completed: 'Completed',
			terminated: 'Terminated',
			failed: 'Failed',
		},
		taskstatus: {
			assigned: 'Assigned to {0}, updated on {1}',
			assignedwithdate: 'Assigned to {0}, updated {1}',
			reassigned: 'Reassigned to {0} by {1}, updated on {2}',
			inforequestedwithdate: 'More Information requested to {0} by {1}, updated {2}',
			inforequested: 'More Information requested to {0} by {1}, updated on {2}',
			infoprovidedwithdate: 'Submitted requested information to {0} by {1}, updated {2}',
			infoprovided: 'Submitted requested information to {0} by {1}, updated on {2}',
			reassignedwithdate: 'Reassigned to {0} by {1}, updated {2}',
			available: 'Available for {0} to be acquired',
			approvedwithdate: 'Approved {0} by {1}',
			approved: 'Approved by {0} on {1}',
			completedwithdate: 'Completed {0} by {1}',
			completed: 'Completed by {0} on {1}',
			rejectedwithdate: 'Rejected {0} by {1}',
			rejected: 'Rejected by {0} on {1}',
			submittedwithdate: 'Submitted {0} by {1}',
			submitted: 'Submitted by {0} on {1}',
			withdrawnwithdate: 'Withdrawn {0} by {1}',
			withdrawn: 'Withdrawn by {0} on {1}',
			escalatedwithdate: 'Escalated to {0} by {1}, updated {2}',
			escalated: 'Escalated by {0} on {1}, updated on {2}',
			expiredwithdate: 'Expired {0} by {1}',
			expired: 'Expired by {0} on {1}',
			moreinforequested: 'More information requested to {0} on {1}',
			faulted: 'Faulted, {0}',
			faultedwithdate: 'Faulted on {0}',
		},
		jobs: {
			recoverable: 'Recoverable',
			jobsFetchErrorMsg: 'Error in fecting process jobs.',
		},
		payload: {
			input: 'Input',
			output: 'Output',
			payloadUnavailable: 'No payload available',
		},
		userTaskDetail: {
			approvalPolicy: 'Approval policy',
			singleAssignee: 'Single assignee',
			history: 'History',
			fetchTaskHistoryErrorMsg: 'Error in fecting human task history.',
			taskhistory: {
				assigned: 'Assigned to {0}',
				acquired: 'Acquired by {0}',
				approved: 'Approved by {0}',
				withdrawn: 'Withdrawn by {0}',
				rejected: 'Rejected by {0}',
				released: 'Released by {0}',
				suspended: 'Suspended by {0}',
				customaction: 'Task completed by {0}, with outcome {1}',
				resumed: 'Resumed by {0}',
				escalated: 'Escalated to {0} by {1}',
				delegated: 'Delegated to {0} by {1}',
				reassigned: 'Reassigned to {0} by {1}',
				updated: 'Task details updated by {0}',
				created: 'Task created by {0}',
				outofoffice:
					'{0} has configured out of office for {1}. Task assignment changed as per settings.',
				addcomment: 'Comment added by {0}',
				taskexpiration: 'Task expired by {0}',
				inforeq: 'Requested more information from {0} by {1}',
				infores: '{0} provided information requested by {1}',
				docadd: 'Document uploaded by {0}',
				docupdate: 'Document updated by {0}',
				docremove: 'Document deleted by {0}',
				priorityupdated: 'Task priority updated by {0}',
				notaskhistoryfound: 'No records found.',
				payloadcreated: 'Task data created by {0}',
				payloadupdated: 'Task data updated by {0}',
				faulted: 'Task is faulted, please contact the administrator.',
				fetchErrorTaskHistory: 'Error occurred while retrieving the history of task {0}',
				commentText: "Comment: '{0}'",
			},
		},
	},
});
