/*eslint max-lines: 0 */
define({
	'DEFAULT_CURRENCY': 'USD',
	'CURRENCY_PATTERN': '¤ ##,##0.00########',
	'TEXT_NO_IMAGE': 'No Image',
	'TEXT_NO_IMAGE_BASE64': 'Image in Base64 format can only be seen in Preview mode',
	'PHONE_FORMAT_INTERNATIONAL': 'International',
	'PHONE_FORMAT_US': 'US',
	'DEFAULT_PHONE_FORMAT': 'US',
	'FORMAT_ERROR_MESSAGE_US': 'You must enter proper phone number in US format.',
	'FORMAT_ERROR_MESSAGE_INTERNATIONAL': 'You must enter proper phone number in International format.',
	'FAILED_TO_LOAD_FORM_CONTENT': 'Failed to load form content',
	'REQUIRED_VALIDATION_MESSAGE_SUMMARY': 'Value is required.',
	'REQUIRED_VALIDATION_MESSAGE_DETAIL': 'You must enter a value.',
	'MIN_LENGTH_VALIDATION_MESSAGE_SUMMARY': 'Min length validation failure',
	'MIN_LENGTH_VALIDATION_MESSAGE_DETAIL': 'Please enter a minimum of these number of characters: ',
	'MAX_LENGTH_VALIDATION_MESSAGE_SUMMARY': 'Max length validation failure',
	'MAX_LENGTH_VALIDATION_MESSAGE_DETAIL': 'Please enter a maximum of these number of characters: ',
	'PATTERN_VALIDATION_MESSAGE_SUMMARY': 'Format is incorrect.',
	'PATTERN_VALIDATION_MESSAGE_DETAIL': 'Please follow this regex pattern while entering the value: ',
	'LABEL_BACKGROUND_COLOR': 'Background Color',
	'LABEL_COLOR': 'Color',
	'LABEL_FONT_SIZE': 'Font Size',
	'LABEL_FONT_SIZE_XSMALL': 'x-small',
	'LABEL_FONT_SIZE_SMALL': 'small',
	'LABEL_FONT_SIZE_NORMAL': 'normal',
	'LABEL_FONT_SIZE_LARGE': 'large',
	'LABEL_FONT_SIZE_XLARGE': 'x-large',
	'LABEL_THEME': 'Theme',
	'LABEL_THEME_NONE': 'None',
	'LABEL_THEME_STANDARD': 'Standard',
	'LABEL_THEME_MODERN': 'Modern',
	'LABEL_THEME_SIMPLE': 'Simple',
	'LABEL_THEME_INDENT': 'Indent',
	'LABEL_THEME_DEFAULT': 'Default',
	'LABEL_THEME_INNER_BORDERS': 'Inner Borders',
	'LABEL_TEXT_ALIGN': 'Text Alignment',
	'LABEL_TEXT_ALIGN_LEFT': 'Left',
	'LABEL_TEXT_ALIGN_CENTER': 'Center',
	'LABEL_TEXT_DEFAULT': 'Text',
	'LABEL_TEXT_ALIGN_RIGHT': 'Right',
	'LABEL_TEXT_ALIGN_TOP': 'Top',
	'LABEL_TEXT_ALIGN_BOTTOM': 'Bottom',
	'LABEL_BORDER_COLOR': 'Border Color',
	'LABEL_BORDER_WIDTH': 'Border Width',
	'LABEL_BORDER_STYLE': 'Border Style',
	'LABEL_BORDER_RADIUS': 'Border Radius',
	'LABEL_SOLID': 'Solid',
	'LABEL_DOTTED': 'Dotted',
	'LABEL_DASHED': 'Dashed',
	'LABEL_CONTROL_ALIGNMENT': 'Control Alignment',
	'LABEL_SIMPLE_TEXT_VERTICAL_ALIGNMENT': 'Vertical Alignment',
	'LABEL_LABEL_COLOR': 'Label Color',
	'LABEL_LABEL_SIZE': 'Label Size',
	'LABEL_LABEL_STYLE': 'Label Style',
	'LABEL_STYLE_NORMAL': 'Normal',
	'LABEL_STYLE_BOLD': 'Bold',
	'LABEL_STYLE_ITALIC': 'Italic',
	'LABEL_CONTROL_CLASS_NAME': 'Control Class Name',
	'LABEL_TABLE_WIDTH': 'Table Width',
	'LABEL_TABLE_COLUMNS_WIDTH': 'Table Columns Width',
	'LABEL_WIDTH': 'Width',
	'LABEL_HEIGHT': 'Height',
	'LABEL_STROKE_COLOR': 'Stroke Color',
	'LABEL_STROKE_WIDTH': 'Stroke Width',
	'FORM_DEFINITION_TYPE_SEPARATOR': ':',
	'LAYOUT_HORIZONTAL': 'Horizontal',
	'LAYOUT_VERTICAL': 'Vertical',
	'MESSAGE_TYPE_PARAGRAPH': 'Paragraph',
	'MESSAGE_TYPE_HEADING1': 'Heading 1',
	'MESSAGE_TYPE_HEADING2': 'Heading 2',
	'MESSAGE_TYPE_HEADING3': 'Heading 3',
	'MESSAGE_TYPE_HEADING4': 'Heading 4',
	'MESSAGE_TYPE_HEADING5': 'Heading 5',
	'MESSAGE_TYPE_HEADING6': 'Heading 6',
	'MESSAGE_TYPE_INLINE_HTML': 'Inline HTML',
	'TARGET_TYPE_PARENT': 'In Current Tab',
	'TARGET_TYPE_NEWTAB': 'In New Tab',
	'MESSAGE_INVALID_URL': 'Please enter a valid URL.',
	'MESSAGE_INVALID_EMAIL': 'Please enter a valid e-mail.',

	'DO_NOTHING': '',
	'LABEL_TYPE': 'Type',
	'LABEL_VALUE': 'Value',
	'ARRAY_VALUE': 'Array Value',
	'APPEND_ARRAY_VALUE': 'Append Array Value',
	'INSERT_ARRAY_VALUE': 'Insert Array Value',
	'CLEAN_ARRAY_VALUE': 'Clean Array',
	'DELETE_ARRAY_VALUE': 'Delete Array Value',
	'LABEL_PRESENTATION': 'Presentation',
	'IDENTITY_VALUE': 'Identities',
	'LABEL_HIDE': 'Hide',
	'LABEL_REQUIRED': 'Required',
	'LABEL_READONLY': 'Read only',
	'LABEL_LABEL': 'Label',
	'MESSAGE': 'Message',
	'IMAGE_URL': 'Image Url',
	'LABEL_SOURCE_URL': 'Source Url',
	'LABEL_ALT_TEXT': 'Alternative Text',
	'LABEL_HINT': 'Hint',
	'LABEL_HELP': 'Help',
	'LABEL_MIN_VALUE': 'Min Value',
	'LABEL_MAX_VALUE': 'Max Value',
	'LABEL_MIN_LENGTH': 'Min Value',
	'LABEL_MAX_LENGTH': 'Max Value',
	'LABEL_PATTERN_VALUE': 'Pattern',
	'LABEL_PLACEHOLDER': 'Placeholder',
	'SHOW': 'Show',
	'SELECT': 'Select',
	'ENABLE': 'Enable',
	'DISABLE': 'Disable',
	'OPTIONAL': 'Optional',
	'EXPAND': 'Expand',
	'COLLAPSE': 'Collapse',
	'EDITABLE': 'Editable',
	'CONSTANT': 'Constant',
	'DATA_DEFINITION': 'Data Definition',
	'CONTROL': 'Control',
	'FUNCTION': 'Function',
	'CONNECTOR_DATA': 'Connector Data',
	'FILTER': 'Filter',
	'FILTER_RESULT': 'filter result',
	'HIDDEN': 'Hidden',
	'LABEL_EXPANDED': 'Expanded',
	'LABEL_DISABLED': 'Disabled',
	'HAS_CLASS': 'Has Class',
	'SELECTED': 'Selected',
	'SELECTED_LABEL': 'Selected Label',
	'SELECTED_PROPERTY': 'Selected Property',
	'OUTCOME': 'Outcome',
	'ON_LOAD': 'On Load',
	'ON_CHANGE': 'On Change',
	'ON_FOCUS': 'On Focus',
	'ON_BLUR': 'On Blur',
	'ON_EXPAND_TOGGLE': 'On Expand Toggle',
	'ON_COLLAPSE': 'On Collapse',
	'ON_EXPAND': 'On Expand',
	'ON_CLICK': 'On Click',
	'ON_SUBMIT': 'On Submit',
	'ON_SAVE': 'On Save',
	'ON_SELECTED': 'On Selected',
	'ON_UNSELECTED': 'On Unselected',
	'ON_SELECTION_CHANGE': 'On Selection Change',
	'ON_ADD_ROW': 'On Row Add',
	'ON_REMOVE_ROW': 'On Row Remove',

	'EQUALS': 'is equal to',
	'NOT_EQUALS': 'is not equal to',
	'IS_TRUE': 'is True',
	'IS_FALSE': 'is False',
	'IS_GREATER': 'is greater than',
	'IS_GREATER_EQUALS': 'is greater than or equal to',
	'IS_NOT_GREATER': 'is not greater than',
	'IS_LESS': 'is less than',
	'IS_LESS_EQUALS': 'is less than or equal to',
	'IS_NOT_LESS': 'is not less than',
	'IS_EMPTY': 'is empty',
	'IS_NOT_EMPTY': 'is not empty',
	'MATCHES': 'matches',
	'MATCHES_FUNCTIONS': 'Matches',
	'SUBSTRING': 'Substring',
	'MEDIA_SMALL': 'Small Devices',
	'MEDIA_MEDIUM': 'Medium Devices',
	'MEDIA_LARGE': 'Large Devices',
	'MEDIA_EXTRA_LARGE': 'Extra Large Devices',
	'MEDIA_ALL': 'ALL Devices',
	'STATIC_LABEL': 'Static',
	'DYNAMIC_LABEL': 'From Data',
	'CONNECTOR_LABEL': 'Connector',
	'LAST_LABEL': 'Last',
	'FIRST_LABEL': 'First',
	'FAILED_TO_FETCH_CONNECTOR': 'Failed to fetch options from connector',
	'FAILED_TO_FETCH_REST': 'Failed to fetch data from REST API',

	'HEX_COLOR_FORMAT_ERROR_MESSAGE': 'Enter the color in hexadecimal format (e.g. #ffffff)',
	'INVALID_WIDTH': 'Please enter a valid width (e.g. 100px or 100%)',
	'INVALID_HEIGHT': 'Please enter a valid height (e.g. 20px or 100%)',
	'INVALID_BORDER_WIDTH': 'Please enter a valid border width (e.g. 100px or 100pt)',
	'INVALID_STROKE_WIDTH': 'Please enter a valid stroke width (e.g. 100px or 100pt)',
	'INVALID_BORDER_RADIUS': 'Please enter a valid border radius (e.g. 10px)',
	'INVALID_CLASS_NAME': 'Please enter a valid class name (e.g. \'title-header\')',
	'INCORRECT_FORMAT_MESSAGE': 'Incorrect Format.',
	'URL_FORMAT_ERROR_MESSAGE': 'Incorrect embed url.',
	'NO_ROWS': 'There are no entries.',

	'SELF': 'Self',
	'FIRST': 'First',
	'LAST': 'Last',
	'SELECTED_ROW': 'Selected',
	'SELECT_ROW': 'Select Row',
	'FOR_EACH': 'For Each',
	'CURRENT': 'Current',
	'FOR_EACH_SELECTED': 'For Each Selected',
	'ALL_SELECTED': 'All Selected',
	'CURRENT_ITERATION_ROW': 'Current Iteration Row',
	'ADD_ROW': 'Add Row',
	'APPEND_OPTION': 'Append Option',
	'CLEAR_OPTIONS': 'Clear Options',
	'SORT_OPTIONS': 'Sort Options',
	'LABEL_SORTED': 'Sorted',
	'TOGGLE_CLASS': 'Toggle Class',
	'ADD_CLASS': 'Add Class',
	'REMOVE_CLASS': 'Remove Class',
	'REFRESH_CONNECTOR': 'Refresh Connector',
	'SET_OPTIONS': 'Set Options',
	'SELECT_ALL_VALUES': 'Select All Values',
	'UNSELECT_ALL_VALUES': 'Unselect All Values',
	'CLEAR_VALUE': 'Clear Value',
	'REMOVE_ROW': 'Remove Row',
	'OPTIONS': 'Options',
	'THROW_ERROR': 'Throw Error',
	'CLEAR_ERROR': 'Clear Error',
	'DISABLE_EVENTS': 'Disable Events',
	'ENABLE_EVENTS': 'Enable Events',
	'IS_VALID': 'Is Valid',
	'ENABLED_ADD_REMOVE_ROWS': 'Enabled Add/Remove Rows',
	'ENABLE_ADD_REMOVE_ROWS': 'Enable Add/Remove Rows',
	'DISABLE_ADD_REMOVE_ROWS': 'Disable Add/Remove Rows',
	'CONTROL_RICH_TEXT_EDITOR': 'Rich Text Editor',
	'CONTROL_DIVIDER': 'Divider',
	'CREATE_UUID': 'Create UUID',
	'CREATE_UUID_SUMMARY': 'CreateUUID',
	'CURRENT_DATE': 'Current Date',
	'CURRENT_TIME': 'Current Time',
	'CURRENT_DATE_TIME': 'Current Date Time',
	'CURRENT_DATE_SUMMARY': 'CurrentDate',
	'CURRENT_TIME_SUMMARY': 'CurrentTime',
	'CURRENT_DATE_TIME_SUMMARY': 'CurrentDateTime',
	'ADD_SECONDS': 'Add Seconds',
	'ADD_MINUTES': 'Add Minutes',
	'ADD_HOURS': 'Add Hours',
	'ADD_DAYS': 'Add Days',
	'ADD_MONTHS': 'Add Months',
	'ADD_YEARS': 'Add Years',
	'FORMAT_DATE': 'Format Date',
	'ADD_SECONDS_SUMMARY': 'AddSeconds',
	'ADD_MINUTES_SUMMARY': 'AddMinutes',
	'ADD_HOURS_SUMMARY': 'AddHours',
	'ADD_DAYS_SUMMARY': 'AddDays',
	'ADD_MONTHS_SUMMARY': 'AddMonths',
	'ADD_YEARS_SUMMARY': 'AddYears',
	'FORMAT_DATE_SUMMARY': 'FormatDate',
	'SUM': '+',
	'SUMMATION': 'Summation',
	'SUMMATION_SUMMARY': 'Sum',
	'SUB': '-',
	'MULTIPLY': '*',
	'DIVISION': '/',
	'INTEGER_DIVISION': 'Integer Division',
	'INTEGER_DIVISION_SUMMARY': 'Int',
	'MODULO': 'Modulo',
	'AND': 'And',
	'OR': 'Or',
	'NOT': 'Not',
	'INLINE_IF': 'Inline If',
	'INLINE_IF_SUMMARY': 'If',
	'EQUAL': '=',
	'GREATER': '>',
	'LESS': '<',
	'GREATER_EQUAL': '≥',
	'LESS_EQUAL': '≤',
	'MIN': 'Min',
	'MAX': 'Max',
	'COUNT': 'Count',
	'AVERAGE': 'Avg',
	'CONCAT': 'Concat',
	'CONCAT_ARRAY': 'Concat Arrays',
	'INDEX_OF': 'Index Of',
	'INDEX_OF_SUMMARY': 'indexOf',
	'AT_INDEX': 'At Index',
	'AT_INDEX_SUMMARY': 'atIndex',
	'TRIM': 'Trim',
	'CONTAINS': 'Contains',
	'TO_LOWERCASE': 'To Lowercase',
	'TO_LOWERCASE_SUMMARY': 'Lowercase',
	'TO_UPPERCASE': 'To Uppercase',
	'TO_UPPERCASE_SUMMARY': 'Uppercase',
	'LENGTH': 'Length',
	'REPLACE': 'Replace',
	'JOIN': 'Join',
	'SPLIT': 'Split',
	'DURATION_MINUTES': 'Duration in minutes',
	'DURATION_HOURS': 'Duration in hours',
	'DURATION_DAYS': 'Duration in days',
	'DURATION_MONTHS': 'Duration in months',
	'DURATION_YEARS': 'Duration in years',
	'MINUTES': 'Minutes',
	'HOURS': 'Hours',
	'DAYS': 'Days',
	'MONTHS': 'Months',
	'YEARS': 'Years',
	'DAY_VALUE': '{0} day',
	'DAYS_VALUE': '{0} days',
	'MONTH_VALUE': '{0} month',
	'MONTHS_VALUE': '{0} months',
	'YEAR_VALUE': '{0} year',
	'YEARS_VALUE': '{0} years',
	'CANCELED_MESSAGE': 'The form couldn\'t be submitted because an event prevented the submit.',
	'INVALID_FORM_MESSAGE': 'The form couldn\'t be submitted because there are validation errors.',
	'CONVERT_TO_JSON': 'Convert to JSON',
	'PARSE_FROM_JSON': 'Parse from JSON',
	'GET_PROPERTY': 'Get Property',
	'CURRENT_USER_ID': 'Current user\'s ID',
	'CURRENT_USER_FIRSTNAME': 'Current user\'s first name',
	'CURRENT_USER_MIDDLENAME': 'Current user\'s middle name',
	'CURRENT_USER_LASTNAME': 'Current user\'s last name',
	'CURRENT_USER_EMAIL': 'Current user\'s email',
	'CURRENT_USER_MANAGER_ID': 'Current user\'s manager\'s ID',
	'CURRENT_USER_MANAGER_FIRSTNAME': 'Current user\'s manager\'s first name',
	'CURRENT_USER_MANAGER_MIDDLENAME': 'Current user\'s manager\'s middle name',
	'CURRENT_USER_MANAGER_LASTNAME': 'Current user\'s manager\'s last name',
	'CURRENT_USER_MANAGER_EMAIL': 'Current user\'s manager\'s email',
	'CURRENT_BROWSER_LANGUAGE': 'Current browser language',
	'GET_APPLICATION_NAME': 'Get application name',

	'TOO_MANY_ROWS': 'Too many rows. Showing {0} of {1}.',
	'SCOPE_ALL': 'All',
	'SCOPE_USER': 'User',
	'SCOPE_GROUP': 'Group',
	'SCOPE_ROLE': 'Role',
	'SCOPE_MEMBER': 'Member',
	'IDENTITY_NO_MATCHES_FOUND': 'No identity(ies) found',
	'IDENTITY_SELECT_ALL': 'Select All',
	'REST_LABEL': 'Rest',

	'ROW': 'Row',
	'INDEX': 'Index',
	'ROW_COUNT': 'Row count',
	'SET_DATA': 'Set Data',
	'TRIGGER_OUTCOME': 'Trigger Outcome',
	'PREVENT_SUBMIT': 'Prevent Submit',
	'CHANGE_PRESENTATION': 'Change Presentation',
	'PRINT_PRESENTATION': 'Print',

	'WIDTH_INLINE_HELP': 'As an alternative to auto adjusting, set an absolute width for the control, such as 2in (inches), 5cm (centimeters), 100px (pixels), or 25% (percent).',
	'HEIGHT_INLINE_HELP': 'As an alternative to auto adjusting, set an absolute height for the control, such as 1in (inches), 1cm (centimeters), 25px (pixels), or 20% (percent).',
	'CONTROL_CLASS_NAME_INLINE_HELP': 'Apply a css class to the control by selecting a class name from properties defined in the form’s selected stylesheet.',
	'REFRESH_GLOBAL_CONNECTOR': 'Refresh Global Connector',
	'NEED_MORE_ROWS': 'Number of rows added is less than allowed minimum',
	'HIDE_COLUMN': 'Hide Column',
	'SHOW_COLUMN': 'Show Column',

	'UPDATED_COMPUTED_VALUE': 'Computed Value Updated',
	'EXECUTING_CONNECTOR': 'executed',
	'EXECUTING_CONTROL_CONNECTOR': ': connector executed',
	'FINISHED_CONNECTOR': 'finished',
	'FINISHED_CONTROL_CONNECTOR': ': connector finished',
	'LOOP_LOG': 'Looping:',
	'X_OF_X': '{0} of {1}',
	'LOOP': 'Loop',
	'LOOP_INDEX': 'Loop\'s Index',
	'LOOP_POSITION': 'Loop\'s Position',
	'LOOP_VALUE': 'Loop\'s Value',
	'OPTION_TRANSLATION_METADATA_LABEL': 'Option {0}',
	'LOOP_ISFIRST': 'Is First Position in the loop?',
	'LOOP_ISLAST': 'Is Last Position in the loop?',

	'EVALUATED_IF': 'Evaluating Conditional: <b>{0}</b>',
	'EVENT_ERROR': 'Error executing Event: <b>{0}</b>',
	'CONNECTOR_ERROR': 'Error executing Connector Call: "<b>{0}</b>": {1}',
	'RESOLVER_CONNECTOR_ERROR': 'Error executing Connector in Control: "<b>{0}</b>": {1}',
	'EXECUTED_ACTION': '<b>{0}</b> executed on <b>{1}</b>',
	'EXECUTED_ACTION_WITH_VALUE': '<b>{0}</b> executed on <b>{1}</b> with value "<b>{2}</b>"',

	'PREVENT_SUBMIT_CONNECTOR_ERROR': 'Submit prevented due to a connector error.',

	'SHOW_ACTION_LOGS': 'Show Action Logs',
	'SHOW_EVENT_LOGS': 'Show Event Logs',
	'SHOW_COMPUTED_LOGS': 'Show Computed Value Logs',
	'SHOW_CONNECTORS_LOGS': 'Show Connector Logs',
	'SHOW_LOOP_LOGS': 'Show Loop Information',
	'SHOW_ERROR_LOGS': 'Show Error Logs',
	'SHOW_REUSABLE_LOGS': 'Show Reusable Logs',
	'SHOW_FILTER_LOGS': 'Show Filter Logs',
	'REUSABLE_LOG_START': 'Start Reusable Snippet',
	'REUSABLE_LOG_END': 'End Reusable Snippet',
	'CUSTOMIZE_FROM': 'Customized from',
	'PRESENTATION_ID_TITLE': 'Presentation Id: {0}',
	'UPLOAD_FAIL': 'Couldn\'t upload file.',
	'UPLOADING': 'Uploading...',
	'HIDDEN_CONTROL_MESSAGE': '{0} is hidden',
	'DEFAULT_VALIDATION_ERROR_MSG': 'Validation error.',
	'ERROR_MSG': 'Error Message',
	'NO_MATCH_FOUND': 'No matches found',
	'ERROR_BANNER_HEADER_MSG': 'Some errors need your attention.',
	'ERROR_BANNER_NO_ERROR_HEADER_MSG': 'No more validation errors.',
	'ERROR_BANNER_NAV_LINK_TEXT': 'View {0}',
	'FILE_SIZE_KB': '{0}KB',
	'FILE_SIZE_MB': '{0}MB',
	'FILE_LIST_CREATED_BY_AND_ON': 'Created by {0} on {1}',
	'FILE_LIST_CREATED_BY': 'Created by {0}',
	'FILE_LIST_CREATED_ON': 'Created on {1}',
	'NO_FILES_MESSAGE': 'Your files will appear here',
	'ON_UPLOAD': 'On Upload',
	'ON_UPLOAD_ERROR': 'On Error',
	'ON_LIST_REFRESH': 'On List Refresh',
	'ON_DOWNLOAD': 'On Download',
	'ON_DOWNLOAD_ERROR': 'On Download Error',
	'ON_DELETE': 'On Delete',
	'ON_DELETE_ERROR': 'On Delete Error',
	'FILE_DOWNLOAD_SUCCESS': '{0} has been downloaded',
	'FILE_DELETE_SUCCESS': '{0} has been deleted',
	'FILE_DOWNLOAD_ERROR': 'Failed to download {0}',
	'FILE_DELETE_ERROR': 'Failed to delete {0}',
	'FILE_LIST_ERROR': 'Failed to fetch list from the connector',
	'DELETE_FILE_CONFIRM_TITLE': 'Delete File Confirmation',
	'DELETE_FILE_CONFIRM_MESSAGE': 'Are you sure you want to delete the file {0}?',
	'DELETE': 'Delete',
	'CANCEL': 'Cancel',
	'LABEL_CONNECTOR_ERROR': 'Connector Error',
	'LABEL_MAX_HEIGHT': 'Max Height',
	'MAX_HEIGHT_INLINE_HELP': 'As an alternative to auto adjusting, set maximum height for the control, such as 1in (inches), 1cm (centimeters), 25px (pixels), or 20% (percent).',
	'ENABLE_DOWNLOAD': 'Enable Download',
	'DISABLE_DOWNLOAD': 'Disable Download',
	'ENABLE_DELETE': 'Enable Delete',
	'DISABLE_DELETE': 'Disable Delete',
	'LAST_UPLOADED_FILE_NAME': 'Last uploaded file name(s)',
	'LAST_UPLOADED_FILE': 'Last uploaded file content',
	'MAX_UPLOAD_COUNT_ERROR_MESSAGE': 'You can upload only {0} files at a time.',
	'SINGLE_UPLOAD_MAX_SIZE_ERROR_MESSAGE': 'Upload a file smaller than {0} KB.',
	'MULTIPLE_UPLOAD_MAX_SIZE_ERROR_MESSAGE': 'You can upload up to {0} KB at a time.',
	'MULTIPLE_FILES_UPLOAD_SUCCESS': 'Uploaded files',
	'SINGLE_FILE_UPLOAD_SUCCESS': 'Uploaded file',
	'CONNECTOR_RESPONSE': 'Connector Response',
	'AUTOMATIC_HEIGHT': 'Automatic Height',
	'FIXED_HEIGHT': 'Fixed Height',
	'RESIZABLE': 'Resizable',
	'NON_RESIZABLE': 'Non Resizable',
	'HIDE_IMAGE_PREVIEW': 'Hide image preview',
	'SHOW_IMAGE_PREVIEW': 'Show image preview',
	'HIDE_EMPTY_CONTROLS': 'Hide fields with no data',
	'SHOW_EMPTY_CONTROLS': 'Show all fields',
	'HIDE_CONFIDENCE_WARNINGS': 'Hide low confidence warnings',
	'SHOW_CONFIDENCE_WARNINGS': 'Show low confidence warnings',
	'DOWNLOAD_ON_DEMAND': 'Enable download document on demand',
	'AUTOMATIC_DOWNLOAD': 'Enable download document automatically',
	'DU_IMAGE_ALT_TEXT': 'Uploaded document will show up here',
	'DU_PRIMARY_TEXT': 'Drag and drop',
	'DU_SECONDARY_TEXT': 'Drop document here for scanning',
	'DU_SUCCESS_DEFAULT_MESSAGE': 'Document analysed successfully.',
	'DU_MISMATCHED_DOC_TYPE_DEFAULT_MESSAGE': 'The document type you uploaded does not match with the configured document type.',
	'DU_UNRECOGNIZED_DOCUMENT_TYPE_MESSAGE': 'Uploaded document could not be recognized.',
	'DU_LOW_CONFIDENCE_DEFAULT_MESSAGE': 'The uploaded document is below the configured confidence value threshold.',
	'DU_INVALID_RESPONSE_DEFAULT_MESSAGE': 'Something went wrong. Please try again.',
	'DU_LOW_CONFIDENCE_WARNING': 'Value has been populated with low confidence score',
	'DU_NO_DOC_TYPE_SELECTED_ERROR': 'Document type not selected.',
	'HIDDEN_CONTROLS_HEADER': 'Fields with no data are hidden.',
	'DOCUMENT_LOAD_ERROR': 'Error loading the document. Please retry.',
	'SUCCESSFULLY_ANALYSED_AND_UPLOADED_MESSAGE': 'Document analysed and saved successfully',
	'SUCCESSFULLY_ANALYSED_MESSAGE': 'Document analysed successfully',
	'SUCCESSFULLY_UPLOADED_MESSAGE': 'Document saved successfully',
	'UPLOAD_FAILED_SUMMARY_MESSAGE': 'Failed to save document',
	'ANALYSIS_FAILED_SUMMARY_MESSAGE': 'Failed to analyse document',
	'ANALYSIS_IN_PROGRESS_MESSAGE': 'Document is being analysed',
	'UPLOAD_IN_PROGRESS_MESSAGE': 'Document is being saved',
	'UPLOAD_FAILED_DETAIL_MESSAGE': 'Please retry or try with another document.',
	'RETRY_ACTION_LABEL': 'Retry',
	'DOWNLOAD_ACTION_LABEL': 'Download',
	'ANALYSIS_IN_PROGRESS_ERROR': 'Document analysis in progress.',
	'SAVE_IN_PROGRESS_ERROR': 'Document save in progress.',
	'CREATE': 'Create',
	'PERFORM_DOCUMENT_ANALYSIS': 'Perform document analysis',
	'INVALID_STYLESHEET': 'Stylesheet does not exist',
	'CYCLIC_DEPENDENCY_DETECTED': 'Cannot render this form reference as it contains a cyclic dependency.'
});
