define({
	PRINT: 'Print',
	CANNOT_DROP_OUTSIDE_THE_CANVAS: 'Invalid Location.',
	CANNOT_DROP_EVENT_SUBPROCESS_INSIDE_EVENT_SUBPROCESS: 'Invalid Location.',
	CUSTOM_PROPERTIES_DIALOG_PROPERTY_DESCRIPTION: 'Description',
	CORRELATIONS: 'Correlations',
	CHANGE_TYPE: 'Change Type',
	MULTIPLE_OUTGOING_TRANSITIONS: 'You can only have one outgoing sequence flow.',
	HUMAN: 'Human',
	FAILED: 'Failed',
	ERROR_BOUNDARY: 'Error Boundary',
	OPEN_DATA_ASSOCIATION: 'Open Data Association',
	CORRELATIONS_POPUP_SUBTITLE_2: 'You can initiate or use them in your activities.',
	ERROR: 'Error',
	INCLUSIVE_GATEWAY: 'Inclusive',
	MESSAGE_START: 'Message Start',
	TIMER_START: 'Timer Start',
	REDO_COMMAND_FAILED:
		"The action can't be redone due to a server failure. The process will reload.",
	CUT: 'Cut',
	REFRESH_PLAYER: 'Refresh Player',
	PASTE_COMMAND_FAILED: 'The paste operation failed on the server.',
	SEARCH: 'Search',
	INVALID_CHARS_CUSTOM_PROPERTY_ERROR:
		'Property name cannot have special characters except underscore(_)',
	SHOW_GRID: 'Show Grid',
	ERROR_END: 'Error End',
	ZOOM_IN: 'Zoom In',
	COMMAND_EXECUTION_FAILED:
		"The action can't be done due to a Server Failure. The process will reload.",
	OML: 'Machine Learning',
	FAST_FOWRWARD: 'Fast Forward Animation',
	CORRELATION_KEYS: 'Keys',
	DEFAULT_CUSTOM_PROPERTY_NAME: 'Property',
	CUSTOM_PROPERTIES_DIALOG_SUBTITLE: 'Properties are reusable within process activities',
	CAN_NOT_DELETE_LANE_WITH_NONE_START_OR_END:
		'You cannot delete a lane with a None Start or End Event.',
	MESSAGE_END: 'Message End',
	AS_BOUNDARY: 'As Boundary',
	CALL: 'Call',
	DMN: 'Decision Service',
	OPEN_PROPERTIES: 'Open Properties',
	SHOW_GRID_TOGGLE: 'Show/Hide Grid',
	ZOOM_150: '150%',
	MESSAGE_CATCH: 'Message Catch',
	CAN_NOT_DELETE_ONLY_START_EVENT: 'You cannot delete the only Start Event.',
	DEFAULT_READ_ONLY_ACTION: 'Invalid Action in Read-Only mode.',
	DELETE: 'Delete',
	CUSTOM_PROPERTIES_DIALOG_PLACEHOLDER_PROPERTY_NAME: 'Enter a property name',
	DOCUMENT_START: 'Document Start',
	FOLDER_START: 'Folder Start',
	CORRELATION_KEY_DELETE_CONFIRMATION: 'Are you sure you want to delete "{0}"?',
	PLAY_THE_PROCESS: 'Play the Process',
	UPDATE: 'Update',
	HELP: 'Help',
	CHANGE_LANE_BACKGROUND_COLOR: 'Change Lane Background Color',
	INVALID_KEY_MESSAGE: 'The following keys have one or more unknown properties:',
	EVENT_BASED_GATEWAY_ONLY_TO_EVENTS: 'Event Based Gateways can only be connected to events.',
	OPEN_FORM: 'Open UI',
	BOT_ACTIVITY: 'Bot Activity',
	COPY: 'Copy',
	CORRELATION_PROPERTIES_OBJECTIVE: 'Properties models concepts of your application',
	FORM_START: 'Form Start',
	BPMN: 'BPMN',
	OTHER: 'Other',
	CUSTOM_PROPERTIES_DIALOG_PLACEHOLDER_DESCRIPTION: 'Enter a description',
	RESET_VIEW: 'Reset View',
	SAVE_MODEL_CONFIRMATION_QUESTION: 'Are you sure do you want to save the model?',
	DATA_OBJECTS: 'Data Objects',
	SUBMIT: 'Submit',
	CANCEL: 'Cancel',
	EMPTY_CUSTOM_PROPERTY_ERROR: 'Property cannot be empty',
	CUSTOM_PROPERTIES_DIALOG_PROPERTY_NAME: 'Property Name',
	TOUR: 'Tour',
	SYSTEM: 'System',
	SNAP_TO_GRID: 'Snap to Grid',
	HIDE_PALETTE: 'Hide Palette',
	REBUILD_PROCESS_EDITOR_FAILED: "The process can't be reloaded due to a Server Failure.",
	ADD: 'Add',
	CUSTOM_PROPERTIES: 'Custom Properties',
	DELETE_KEY: 'Delete',
	DECISION: 'Decision',
	PARALLEL_GATEWAY: 'Parallel',
	EVENTS: 'Events',
	CORRELATION_KEY_DELETE_USAGES: 'The following artifacts are still using it: ',
	BUILD_PROCESS_EDITOR_FAILED:
		"The Design tab can't be loaded due to a Server Failure. You will be redirected to Discover page",
	SAMPLE_HELP: 'Sample Help',
	SYNC_COMMAND_STACK_FAILED:
		'A Server Failure happened when trying to retrieve information about the last made actions. The process will reload.',
	COLUMN: 'Column',
	SHIFT_KEY: 'Shift',
	SHOW_PALETTE: 'Show Palette',
	OPEN_DECISION: 'Open Decision',
	CORRELATIONS_POPUP_SUBTITLE:
		'Define correlation keys to identify an instance with one or more properties.',
	OPEN_PROCESS: 'Open Process',
	RECEIVE: 'Receive',
	MESSAGE_THROW: 'Message Throw',
	DELETE_CORRELATION_KEY: 'Delete Correlation Key',
	HIDE_GRID: 'Hide Grid',
	SAVE_MODEL_CONFIRMATION_LABEL_2: 'This may render correlation keys in other processes invalid.',
	SAVE_MODEL_CONFIRMATION_LABEL_1: 'One or more properties had been modified/removed.',
	REPEATED_CUSTOM_PROPERTY_ERROR: 'Property name cannot be repeated',
	SERVICE: 'Service',
	GATEWAYS: 'Gateways',
	TERMINATE_END: 'Terminate End',
	CALLBACK_END: 'Callback End',
	DELETE_PLAYER_INSTANCE: 'Delete Player Instance',
	ZOOM_125: '125%',
	CUSTOM_PROPERTIES_DIALOG_TITLE: 'Define custom properties and assign values in the activities.',
	CTRL_KEY: 'Ctrl',
	OPEN_PROCESS_OVERLAY: 'Help',
	APPROVE: 'Approve',
	ZOOM_OUT: 'Zoom Out',
	SEND: 'Send',
	ZOOM_RESET: 'Reset Zoom And Pan',
	DEFAULT_VALID_ACTION: 'Valid Action.',
	NAME: 'Name',
	END_EVENT: 'End Event',
	OPEN_DATA_OBJECTS: 'Open Data Objects',
	CREATE_NEW_LANE: 'Create New Lane',
	ZOOM_50: '50%',
	ROW: 'Row',
	UNDO_COMMAND_FAILED:
		"The last action can't be undone due to a server failure. The process will reload.",
	TOGGLE_SNAP_TO_GRID: 'Toggle Snap to Grid',
	LOADING: 'Loading...',
	ALREADY_HAS_NONE_START: 'You can only have one None Start Event per process or subprocess.',
	ALREADY_HAS_START: 'You can only have one Start Event per process.',
	SUBPROCESS: 'Sub-Process',
	NO: 'No',
	UNDO: 'Undo',
	PREPARING_PROCESS_FLOW: 'Preparing process flow, please wait ...',
	DATA_ASSOCIATION: 'Data Association',
	YES: 'Yes',
	TOGGLE_GRID: 'Toggle Grid',
	BOUNDARY_EVENT_ON_PROCESS: 'Boundary Events must be dropped on other tasks.',
	ERROR_BOUNDARY_INVALID_DROP: 'Cannot drop error boundary event here.',
	ABSTRACT: 'Abstract',
	CORRELATION_KEY_OBJECTIVE: 'A key groups properties to identify instances',
	PALETTE_TOGGLE: 'Show/Hide Palette',
	CHANGE_SEQUENCE_FLOW_TYPE: 'Change Sequence Flow Type',
	NOTIFY: 'Notify',
	LOAD_PROCESS_FAILED: "The process can't be loaded due to a Server Failure.",
	EXCLUSIVE_GATEWAY: 'Exclusive',
	NOTE: 'Note',
	REDO: 'Redo',
	DYNAMIC_PROCESS: 'Dynamic Process',
	RULE: 'Rule',
	DEFAULT_INVALID_ACTION: 'Invalid Action.',
	OK: 'OK',
	CHANGE_ICON: 'Change Icon',
	INTEGRATIONS: 'Integrations',
	APPLY_CORRELATIONS_MODEL: 'Apply Correlations Model',
	CANNOT_CREATE_START_IN_SUBPROCESS: 'Cannot create a start node inside a subprocess.',
	DATA_MAPPER: 'Data Mapper',
	KEYBOARD_SHORTCUT: 'Keyboard Shortcuts',
	ZOOM_100: '100%',
	TIMER_CATCH: 'Timer Catch',
	CAN_NOT_DELETE_ONLY_END_EVENT: 'You cannot delete a the only End Event.',
	ICS_SERVICE: 'Integration',
	START_EVENTS_INCOMING_TRANSITION: 'Start Events do not have incoming sequence flows.',
	PASTE: 'Paste',
	APPLY: 'Apply',
	ZOOM_75: '75%',
	CORRELATION_PROPERTIES: 'Properties',
	POCESS_PROPERTIES: 'Process Properties',
	START: 'Start',
	DEFAULT: 'Default',
	EVENT_BASED_GATEWAY: 'Event Based',
	PROCESS_USAGES: 'Process Usages',
	VALIDATION_ISSUES: 'There are validation issues in this node properties.',
	SEQUENTIAL_MULTI_INSTANCE: 'Sequential Multi-instance',
	PARALLEL_MULTI_INSTANCE: 'Parallel Multi-instance',
	ZOOM_LEVEL: 'Zoom level',
	PALETTE_SEARCH: 'Palette search',
	FIX: 'Fix',
});
