/**
 * @license
 * Copyright (c) 2014, 2021, Oracle and/or its affiliates.
 * Licensed under The Universal Permissive License (UPL), Version 1.0
 * as shown at https://oss.oracle.com/licenses/upl/
 * @ignore
 */
define({
	'SUSPENDED_INSTANCES': 'Suspended<br/>Instances',
	'RECOVERABLE_INSTANCES': 'Recoverable<br/>Instances',
	'ALERTED_TASKS': 'Alerted<br/>Tasks',
	'MAX_METRIC_VALUE': '99+',
	'MONITOR_SECTION': 'Monitor section',
	'ACTIONS_SECTION_DEFAULT_TITLE': 'Actions',
	'ALERT_TITLE': 'Alert',
	'MORE': 'More',
	'RECENTS': 'Recents',
	'NO_DESCRIPTION': 'No description.',
	'NO_ACTIONS': 'No actions available',
	'WELCOME_TITLE': 'Welcome to Oracle Integration',
	'WHAT_IS_INTEGRATION_CLOUD': 'What is Oracle Integration?',
	'INTEGRATION_CLOUD_EXPLAINED': 'Maximize the value of your investments in SaaS and on-premise applications by using our best cloud-based tools in a simple and powerful unified interface. Oracle Integration features <b>Integrations</b> to design, monitor, and manage connections between your applications, <b>Processes</b> to automate and manage business workflows, and <b>Analytics</b> to gain business insight.',
	'SUITE_TITLE': 'Home',
	'SETTINGS': 'Settings',
	'REGISTRATION': 'Registration',
	'NEW_REQUEST': 'New request',
	'SUITE_DESCRIPTION': 'Integrate. Automate. Analyze.',
	'TOUR': 'Take the tour',
	'WATCH_VIDEOS': 'Watch videos',
	'VIEW_VIDEOS': 'View videos',
	'WATCH_AND_LEARN': 'Want to watch and learn?',
	'OPEN_TASKS': 'Open',
	'ON_TRACK': 'On track',
	'DUE_TASKS': 'Due',
	'OVERDUE_TASKS': 'Overdue',
	'ESCALATED_TASKS': 'Escalated',
	'REGISTER_BUTTON': 'Register',
	'REGISTER_TITLE': 'Registration',
	'REGISTER_LOCAL_FEATURES_TITLE': 'Current instance features',
	'UNREGISTER': 'Unregister',
	'UNREGISTER_CONFIRMATION': 'Are you sure you want to unregister?',
	'FEATURE_LOGO_ALT': 'Feature icon',
	'REGISTER_DIALOG_TITLE': 'Register OIC instance',
	'REGISTER_DIALOG_SUITE_INSTANCE_URL': 'OIC instance URL',
	'REGISTER_DIALOG_FEATURES_DISCOVERED': '{0} feature(s) discovered',
	'INSTANCE_AT': 'Added instance features at {0}',
	'REGISTER_DIALOG_URL': ' URL',
	'REGISTER_DIALOG_NAME': ' Name',
	'REGISTER_DIALOG_DISCOVER': ' Discover',
	'REGISTER_DIALOG_REGISTER': ' Register',
	'USER_CREDENTIALS_TITLE': ' Administrator credentials',
	'USER_CREDENTIALS_TITLE_HELP': 'Enter the endpoint URL exposed by the instance you wish to register.',
	'USERNAME_CREDENTIALS': ' Username',
	'PASSWORD_CREDENTIALS': ' Password',
	'OK': 'OK',
	'YES': 'Yes',
	'NO': 'No',
	'INTEGRATION': 'Integration',
	'ANALYTICS_STREAMS': 'Analytics streams',
	'REGISTER_DIALOG_BACK': 'Back',
	'REGISTRY_ERROR': 'Registry error',
	'SERVICE_UNAVAILABLE': 'Registry service unavailable. Please contact the administrator',
	'LOCAL_FEATURES_UNAVAILABLE': 'No features available in the current instance.',
	'ERROR_REASON': 'Reason:',
	'UNABLE_TO_REGISTER': 'Unable to register integration instances.',
	'UNABLE_TO_DISCOVER': 'Unable to discover integration instances.',
	'UNABLE_TO_UNREGISTER': 'Unable to unregister instance.',
	'UNABLE_TO_RENAME': 'Unable to rename instance.',
	'ENTER_VALID_URL': 'Please enter a valid URL',
	'ONLY_ANALYTICS_SUPPORT_ERROR': 'Current instance only supports analytics instance registration.',
	'NO_FEATURES_AVAILABLE': 'There are no features available.',
	'UNKNOWN_ALREADY_REGISTERED_SUITE': 'One or more features are unknown.',
	'ALREADY_REGISTERED_SUITE': 'The following features are already registered: \n{0}.',
	'CHECK_CREDENTIALS': 'User or Password are incorrect.',
	'CHECK_URL': 'Invalid URL.',
	'UNEXPECTED_ERROR': 'Unexpected server error.',
	'PCS_DESCRIPTION': 'Build and activate process applications',
	'VBCS_DESCRIPTION': 'Create mobile and web applications.',
	'ICS_DESCRIPTION': 'Connect your applications into a continuous business flow',
	'STREAMS_DESCRIPTION': 'Get real-time analytics and time-sensitive processing on streaming data',
	'FILETRANSFER_DESCRIPTION': 'Configure secure file transfers for integrations and applications',
	'FILES_DESCRIPTION': 'Configure secure files server for applications',
	'ANALYTICS_INSIGHT': 'Insight',
	'ANALYTICS_ACTIONS_CREATE_MODEL': 'Create a model',
	'ANALYTICS_ACTIONS_MANAGE_DASHBOARDS': 'View dashboards',
	'ANALYTICS_ACTIONS_DESC': 'Gain insight into process applications and integrations',
	'ANALYTICS_MODEL_METRICS_TITLE': 'Insight',
	'ANALYTICS_MODEL_METRICS_NO_ACTIVATED': 'No active consoles',
	'ANALYTICS_MODEL_METRICS_NO_ACTIVATED_MODELS': 'No activated models',
	'ANALYTICS_MODELS_DRAFTS': 'Draft models',
	'ANALYTICS_MODEL_DRAFTS': 'Draft model',
	'ANALYTICS_MODELS_DEACTIVATED': 'Deactivated models',
	'ANALYTICS_MODEL_DEACTIVATED': 'Deactivated model',
	'ANALYTICS_MODELS_ACTIVE': 'Activated models',
	'ANALYTICS_MODEL_ACTIVE': 'Activated model',
	'ANALYTICS_CONSOLES_ACTIVE': 'Activated consoles',
	'ANALYTICS_CONSOLE_ACTIVE': 'Activated console',
	'ANALYTICS_CONSOLES_INACTIVES': 'In-active consoles',
	'ANALYTICS_CONSOLE_INACTIVE': 'In-active console',
	'ANALYTICS_DASHBOARD_TITLE': 'Insight models',
	'ANALYTICS_DASHBOARD_TOOLTIP': 'Analyze your processes and integrations',
	'ANALYTICS_DASHBOARD_MODELS_ADD': 'Models',
	'ANALYTICS_DASHBOARD_INST_ACTIVE': 'Active',
	'ANALYTICS_DASHBOARD_INST_COMPLETED': 'Completed',
	'ANALYTICS_DASHBOARD_INST_HEALTHY': 'Healthy',
	'ANALYTICS_DASHBOARD_INST_RECOVERABLE': 'Recoverable',
	'ANALYTICS_DASHBOARD_INST_ERRORS': 'Errors',
	'ANALYTICS_DASHBOARD_INST_FAILED': 'Failed',
	'ANALYTICS_DASHBOARD_INST_SUCCESS': 'Successful',
	'ANALYTICS_DASHBOARD_NO_MODELS': 'You have no dashboards to monitor',
	'ANALYTICS_DASHBOARD_NO_MODELS_DETAILS': 'Go to the models catalog to import, create, complete, and activate additional Insight models.',
	'ANALYTICS_DASHBOARD_NO_MORE_MODELS_DETAILS': 'You have no more dashboards to monitor. To add summary cards for additional dashboards, activate new models.',
	'ANALYTICS_DASHBOARD_LOADING_CONTENT': 'Loading console content ...',
	'ANALYTICS_DASHBOARD_INACTIVE': 'Deactivated',
	'ANALYTICS_MODEL_METRICS_NO_DATA': 'No data for last 5 days',
	'ANALYTICS_MODEL_METRICS_NO_DATA_TOOLTIP': 'No events happened for last 5 days, or the data was purged. This also can happen if an application from which this data is coming has stopped responding',

	'VBCS_BUILDER': 'Visual Builder',
	'VBCS_APPS': 'Visual Apps',
	'ALL_APPS': 'Applications',
	'DEVELOPED_APPS': 'under development',
	'STAGED_APPS': 'staged',
	'PUBLISHED_APPS': 'published',
	'VIEW_APPLICATIONS': 'View applications',
	'CREATE_APPLICATION': 'Create application',

	'METRIC_ERROR': 'This metric isn\'t displaying properly. Try refreshing the page or signing in again',
	'FATAL_ERROR_LOADING': 'This page isn\'t displaying properly. Try refreshing the page or sign in again. If the error persists please contact the administrator.',

	'STREAMS_ACTIONS_DESC': 'Get real-time analytics and time-sensitive processing on streaming data',
	'STREAMS_CATALOG_LINK': 'Go to catalog',

	'LAST_24_HOURS': 'Last 24 hours',
	'LAST_48_HOURS': 'Last 48 hours',
	'LAST_7_DAYS': 'Last 7 days',

	'SETTINGS_DESCRIPTION': 'Download logs and change logging levels',
	'SEARCH_PLACEHOLDER': 'Search...',
	'CLEAR_SEARCH': 'Clear search',
	'FILTERS_MENU': 'Open filters menu',
	'REMOVE_FILTER': 'Remove filter',
	'CLEAR_ALL': 'Clear all',
	'SAVE': 'Save',
	'RESET': 'Reset',
	'REVERT': 'Revert',
	'REVERT_TO_DEFAULT': 'Revert all to default levels',
	'REVERT_TO_DEFAULT_EXPLANATION': 'This action can not be undone and it may take some time.',
	'REVERT_TO_DEFAULT_TEXT': 'Are you sure you want to revert all to default levels?',
	'CONFIRM': 'Confirm',
	'DISCARD_AND_EXIT': 'Discard and exit',
	'SAVE_AND_EXIT': 'Save and exit',
	'SAVE_AND_RETURN': 'Save and return',
	'SAVE_AND_EXIT_TITLE': 'Save changes and exit?',
	'SAVE_CHANGES_TITLE': 'Save changes?',
	'SAVE_AND_EXIT_EXPLANATION': 'There are unsaved changes.',
	'SAVE_AND_EXIT_TEXT': 'Do you want to save your changes before exiting?',
	'CANCEL': 'Cancel',
	'SAVE_LOG_SUCCESS': '{0} logging levels successfully saved.',
	'SAVE_LOG_ERROR': 'An error occurred when trying to save {0} logging levels.',
	'REVERT_TO_DEFAULT_LOG_SUCCESS': '{0} logging levels successfully reverted to its default values.',
	'RELOAD_LOG_PACKAGES_ERROR': 'An error occurred when trying to reload the logging levels.',
	'LAST_SAVED_CONFIGURATION': 'Last saved configuration',
	'LOG_CONFIGURATION': 'Logging',
	'LOG_CONFIGURATION_DESCRIPTION': 'Use caution when changing logging levels because increasing logging levels can affect performance. Reset logging levels back to default settings after troubleshooting.',
	'DOWNLOAD_LOGS': 'Download logs',
	'DOWNLOAD_LOGS_ERROR': 'An error occurred when trying to download the log files.',
	'INSIGHT_SETTINGS': 'Insight settings',
	'INSIGHT_METRICS_RETENTION_PERIOD': 'Data retention period (days)',
	'INSIGHT_METRICS_RETENTION_PERIOD_EXPLANATION': 'Insight retains data for all consoles for the number of days you specify. Data older than this is deleted the next time a nightly purge job is run.',
	'INSIGHT_LIFECYCLE_ACTION_WAITTIME': 'Model operation wait period (seconds)',
	'INSIGHT_LIFECYCLE_ACTION_WAITTIME_EXPLANATION': 'When you activate, deactivate, or delete a model, Insight listens for a response for the number of seconds you specify. Insight marks lifecycle operations that do not return a "Failed" status during this period as successfully completed.',
	'INSIGHT_SETTINGS_SAVE_SUCCESS': 'Insight settings successfully saved.',
	'INSIGHT_SETTINGS_SAVE_PROGRESS': 'Started save operation ...',
	'INSIGHT_SETTINGS_SAVE_ERROR': 'An error occurred while saving Insight settings.',
	'INSIGHT_SETTINGS_INST_PURGE_TITLE': 'Purge instance metrics',
	'INSIGHT_SETTINGS_INST_PURGE_ACTION': 'Purge now',
	'INSIGHT_SETTINGS_INST_PURGE_CONFIG_LABEL': 'Older than',
	'INSIGHT_SETTINGS_INST_PURGE_CONFIG_SUFFIX': 'days',
	'INSIGHT_SETTINGS_INST_PURGE_CONFIG_DESC': 'This will purge metrics across models, which are older than time period specified.',
	'INSIGHT_SETTINGS_PURGE_SUCCESS': 'Metrics purge succeeded',
	'INSIGHT_SETTINGS_PURGE_ERROR': 'An error occurred while purging the metrics.',
	'INSIGHT_PURGE_DUR_VAL_MESS': 'Enter an integer representing number of days',
	'INSIGHT_PURGE_DUR_VAL_HINT': 'Enter an integer',
	'INSIGHT_TIMEOUT_DUR_VAL_MESS': 'Enter an integer representing number of seconds',
	'INSIGHT_TIMEOUT_DUR_VAL_HINT': 'Enter an integer',
	'NAME': 'Name',
	'STATUS': 'Status',
	'EXPIRATION': 'Expiration',
	'DURATION': 'Duration',
	'START_TIME': 'Start time',
	'LOGGING_LEVEL': 'Logging level',
	'INHERITED_LEVEL': '{0} - Inherited',
	'DESCENDANTS_COUNT': '({0} Collapsed loggers)',
	'DECREASED': 'Decreased',
	'INCREASED': 'Increased',
	'DEFAULT': 'Default',
	'DECREASED_FROM': 'Decreased from',
	'INCREASED_FROM': 'Increased from',
	'AT_DEFAULT': 'At Default',
	'UNSAVED': 'Unsaved change',
	'OFF': 'Off',
	'INCIDENT_ERROR': 'Incident error',
	'ERROR': 'Error',
	'WARNING': 'Warning',
	'INFO': 'Info',
	'CONFIG': 'Config',
	'NOTIFICATION': 'Notification',
	'NOTIFICATIONS': 'Notifications',
	'DATABASE': 'Database',
	'RECOMMENDATIONS': 'Recommendations',
	'API_PLATFORM': 'API Platform',
	'TRACING': 'Tracing',

	'FINE': 'Fine',
	'FINER': 'Finer',
	'FINEST': 'Finest',
	'ALL': 'All',
	'ANYONE': 'Anyone',
	'NONE': 'None',
	'SHOW_ONLY': 'Show only:',
	'OIC_ONLY': 'Oracle Integration',
	'LATEST_CHANGES_ONLY': 'Unsaved changes',
	'MAIN_LEVELS_ONLY': 'Top containers',
	'RETENTION_PERIODS': 'Retention periods',
	'BAM_RETENTION_PERIOD': 'BAM retention period',
	'BAM_RETENTION_PERIOD_EXPLANATION': 'Retention period of the Insight metrics captured as part of BAM data objects',
	'EVENT_STORE_RETENTION_PERIOD': 'Event store retention period',
	'EVENT_STORE_RETENTION_PERIOD_EXPLANATION': 'Controls the retention period of the Insight raw events captured in SOA-INFRA schema',

	'ICS_CONNECTIONS_TITLE': 'Connections',
	'ICS_CONNECTIONS_TOTAL': 'total',
	'ICS_CONNECTIONS_USED': 'used',
	'ICS_CONNECTIONS_USED_IN_ACTIVE': 'used in active',
	'ICS_INTEGRATIONS_TITLE': 'Integrations',
	'ICS_INTEGRATIONS_TOTAL': 'total',
	'ICS_INTEGRATIONS_ACTIVE': 'active',
	'ICS_INTEGRATIONS_SCHEDULED': 'scheduled',
	'ICS_RUNTIME_MESSAGES_LAST_ONE_HOUR': 'Last 1 hour',
	'ICS_RUNTIME_MESSAGES_LAST_THREE_DAYS': 'Last 3 days',
	'ICS_RUNTIME_MESSAGES_NORMAL': 'Acceptable',
	'ICS_RUNTIME_MESSAGES_ADVERSE': 'Adverse',
	'ICS_RUNTIME_MESSAGES_SEVERE': 'Severe',
	'ICS_RUNTIME_SUCCESS_RATE_MESSAGES': 'MESSAGES',
	'ICS_RUNTIME_SUCCESS_RATE_SUCCESSFUL': 'SUCCESSFUL',
	'ICS_RUNTIME_MESSAGES_NO': 'No <br/> Messages <br/> Processed',
	'ICS_RUNTIME_MESSAGES': 'Messages',
	'ICS_RUNTIME_MESSAGES_PROCESSED': 'Processed',
	'ICS_RUNTIME_MESSAGES_SUCCESSFUL': 'Successful',
	'ICS_RUNTIME_MESSAGES_RECEIVED': 'Received',
	'ICS_RUNTIME_MESSAGES_FAILED': 'Failed',
	'ICS_RUNTIME_MESSAGES_SUCCESS_RATE': 'Success rate',

	'ICS_TIME_YEARS': 'years',
	'ICS_TIME_MONTHS': 'months',
	'ICS_TIME_DAYS': 'days',
	'ICS_TIME_HOURS': 'hours',
	'ICS_TIME_MINUTES': 'minutes',
	'ICS_TIME_SECONDS': 'seconds',
	'ICS_TIME_YEARS_AGO': 'years ago',
	'ICS_TIME_MONTHS_AGO': 'months ago',
	'ICS_TIME_DAYS_AGO': 'days ago',
	'ICS_TIME_HOURS_AGO': 'hours ago',
	'ICS_TIME_MINUTES_AGO': 'minutes ago',
	'ICS_TIME_SECONDS_AGO': 'seconds ago',
	'ICS_TIME_IN': 'in',
	'ICS_CONNECTION_LBL': 'Connection',
	'ICS_INTEGRATION_LBL': 'Integration',
	'ICS_AUDIT_ACTION_CREATED': 'created',
	'ICS_AUDIT_ACTION_UPDATED': 'updated',
	'ICS_AUDIT_ACTION_DELETED': 'deleted',
	'ICS_AUDIT_ACTION_ACTIVATED': 'activated',
	'ICS_AUDIT_ACTION_DEACTIVATED': 'deactivated',
	'ICS_AUDIT_ACTION_IMPORTED': 'imported',
	'ICS_AUDIT_ACTION_CLONED': 'cloned',
	'ICS_AUDIT_ACTION_CREATED_NEW_VERSION': 'new version created',
	'ICS_USER_BY': 'by',
	'MONITOR': 'Monitor',
	'DEVELOP': 'Develop',

	'TASKS': 'My Tasks',
	'PROCESS_APPLICATIONS': 'Processes',
	'PROCESS_CATEGORY': 'Processes',
	'APPLICATIONS': 'Process applications',
	'APPLICATION': 'Process application',
	'ANALYTICS': 'Insight',
	'STREAMS': 'Streams',
	'INTEGRATIONS': 'Design',
	'FILETRANSFER': 'File transfer',
	'FILES': 'Files',
	'FILE_SERVER': 'File Server',
	'PROCESS_WAREHOUSE': 'Process warehouse',
	'VBCS': 'Visual builder',
	'INTEGRATIONS_HEALTH': 'Integrations health',
	'CONNECTIONS': 'Connections',
	'CONNECTION': 'Connection',
	'CREATE_CONNECTIONS': 'Create connections',
	'CREATE_INTEGRATIONS': 'Create integrations',
	'CREATE_PROJECT': 'Start a new project',
	'MONITORING': 'Observability',
	'BROWSE_ADN_CREATE': 'Create applications',
	'QUICK_START_APPS': 'Use QuickStart',
	'INSTANCES': 'Process health',
	'DASHBOARD': 'Dashboard',
	'DASHBOARDS': 'Dashboards',
	'RUNS': 'Runs',
	'DESIGN_TIME_METRICS': 'Design time metrics',
	'ACTIVITY_STREAM': 'Activity stream',
	'TRACKING': 'Instances',
	'SCHEDULE_PARAMS': 'Schedule parameters',
	'SCHEDULE_DEFINITION': 'Schedule definition',
	'SCHEDULE_OVERVIEW': 'Schedule overview',
	'ASSERTER_RECORDINGS': 'Asserter recordings',
	'TEST_INTEGRATION': 'Test',
	'WORK_WITH_DASHBOARDS': 'Work with dashboards',
	'CREATE_MODEL': 'Create model',
	'HOME': 'Home',
	'WELCOME': 'Welcome',
	'LEARN_MORE': 'Learn',
	'CHECK_DASHBOARD': 'Ready to view your dashboard?',
	'OPEN_HOME': 'Open home',
	'MORE_VIDEOS': 'More videos',
	'LEARN_MORE_SUB': 'Explore how to create integrated solutions',
	'SUITE': 'Integration',
	'SUITE_EXPLAINED_TITLE': 'What is Oracle Integration?',
	'SUITE_EXPLAINED_SUBTITLE': 'Learn how to empower your business',
	'ANALYTICS_WELCOME_SUBTITLE': 'Gain insight',
	'DEFINE_WORKFLOWS': 'Define your workflows',
	'DEFINE_WORKFLOWS_SUBTITLE': 'Learn how to automate processes',
	'DEFINE_INTEGRATIONS_SUBTITLE': 'Design and activate your integrations',
	'WHAT_IS_NEW': 'What\'s new in this release?',
	'WHAT_IS_NEW_SUBTITLE': 'Deep dive into all the new features',
	'DEFINE_INTEGRATIONS': 'Define your integrations',
	'NO_FEATURES': 'No features registered into this instance',
	'CONTACT_ADMIN': 'If the problem persists contact the administrator',
	'REGISTER_ADMIN': 'To register a new integration instance go to Registration',
	'LOOKUPS': 'Lookups',
	'LOOKUP': 'Lookup',
	'PACKAGES': 'Packages',
	'AGENTS': 'Agents',
	'ADAPTERS': 'Adapters',
	'LIBRARIES': 'Libraries',
	'LIBRARY': 'Library',
	'CONNECTIVITY_CLOUD': 'Connectivity cloud',
	'ERRORS': 'Errors',
	'CONFIGUREINTEGRATION': 'Configure integration',
	'CONFIGUREPACKAGE': 'Configure package',
	'SIGN_OUT': 'Sign out',
	'REPORT_INCIDENT': 'Report incident',
	'REPOSITORY': 'Repository',
	'DESIGNER': 'Designer',
	'CONFIGURATOR': 'Configurator',

	'GET_STARTED': 'Get started',
	'WHATS_NEW': "What's new",
	'TUTORIALS': 'Tutorials',
	'VIDEOS': 'Videos',
	'SERVICE_LIMITS': 'Service limits',
	'PAGE_LEVEL_HELP': 'Help for this page',
	'GET_SAMPLES': 'Get samples',
	'GET_BTN_LABEL': 'Get',
	'GET_SAMPLES_INFO_INTEGRATION': 'If you already have sample integrations/accelerators, getting new ones will overwrite existing integrations with the same name and version. However, if a sample integration is active or locked, it will not be overwritten. Get sample integrations and accelerators?',
	'CANNOT_FIND': 'Can\'t find what you\'re looking for?',
	'CHECK_DOCUMENTATION': 'Check the documentation',
	'FORUM_HELP': 'Have a technical question?',
	'HELP_TITLE': 'Help',
	'OPEN_FORUM': 'Try the forum',
	'NO_RECENT': 'There are no recent items.',
	'TOGGLE_NAV': 'Show / Hide navigation menu',
	'REFRESH': 'Refresh',
	'NO_DATA': 'No data available to display',
	'NUMBER_OF_TASKS': 'Number of tasks',
	'CURRENT_TASKS': 'Current tasks',
	'LOGO_ALT': 'Oracle logo',
	'EDIT_SUITE_NAME': 'Edit suite instance name',
	'NAVIGATE_TO_SUITE_SETTINGS_PAGE': 'Navigate to suite instance settings page',
	'SUITE_URL': 'Suite URL',
	'UNREGISTER_SUITE_ALT': 'Unregister suite instance',
	'REGISTRY_INTRO': 'Register additional instances to your current instance to use their features together',
	'SUITE_URL_PLACEHOLDER': 'https://example.oracle.com/',
	'ACTION_DESCRIPTION_TOOLTIP': '{0} - {1} - {2}',

	'PAGE_EXPIRED_WARNING': 'Still there?',
	'PAGE_EXPIRED_WARNING_MSG': "You've been away for a while. For your security, we'll close this session in 5 minutes.",
	'SIGN_OUT_NOW': 'Sign out now',
	'CONTINUE_WORKING': 'Continue working',
	'PAGE_EXPIRED': 'Page expired',
	'PAGE_EXPIRED_MSG': 'The page has expired. Click OK to continue.',
	'INITIATE_REQUEST': 'Initiate request',
	'WORKSPACE': 'Workspace',
	'PURGE_DB': 'Change data retention',

	'ERROR_PAGE_SUBTITLE': 'We\'ve detected a problem',
	'NOT_FOUND_PAGE_TITLE': 'Page not found',
	'NOT_FOUND_SUMMARY': 'We can\'t find the page you\'re looking for',
	'NOT_FOUND_DESCRIPTION': 'This page may no longer exist, or may have been moved.\nTry re-entering the URL before you give up.',
	'UNAUTHORIZED_TITLE': 'Page not accessible',
	'UNAUTHORIZED_SUMMARY': 'The page requested cannot be accessed.',
	'UNAUTHORIZED_DESCRIPTION': 'We are unable to take you to this page.\nTry contacting your administrator for help.',
	'CUSTOMER_STOP_MODE_TITLE': 'Service instance stopped',
	'CUSTOMER_STOP_MODE_SUMMARY': 'Service instance has been stopped and is unavailable at this time.',
	'CUSTOMER_STOP_MODE_DESCRIPTION': 'Please contact your service instance administrator for additional information.',
	'RETURN_HOME': 'Home',
	'ERROR_PAGE_MESSAGE': 'An error has occurred{0}. Wait a moment and retry. If the problem continues, contact your administrator.',
	'ERROR_PAGE_TITLE': 'Issue detected',
	'QUIESCE_PAGE_SUBTITLE': 'We\'ve detected a serious problem with your storage capacity',
	'QUIESCE_PAGE_MESSAGE': 'Use data retention settings to manage your database space and purge unneeded data to increase available capacity.',
	'QUIESCE_PAGE_2_MESSAGE': 'Contact your administrator to manage your database space (using data retention settings) and purge unneeded data to increase available capacity.',

	// about dialog properties
	'ABOUT': 'About',
	'PCAR_VERSION': 'Version:',
	'GATEWAY_IP': 'Outbound IP:',
	'INBOUND_IP': 'Inbound IP:',
	'IDENTITY_DOMAIN': 'Identity domain:',
	'SERVICE_NAME': 'Service instance:',
	'SERVICE_TYPE': 'Service type:',
	'MESSAGE_PACKS': 'Number of message packs:',
	'BYOL': 'Bring your own license (BYOL):',
	'COPY_RIGHT': 'Oracle &copy; 2015, {toyear}, Oracle and/or its affiliates. All rights reserved.',
	'ABOUT_ORACLE': 'About Oracle',
	'CONTACT_US': 'Contact Us',
	'LEGAL_NOTICE': 'Legal Notice',
	'TERM_OF_USE': 'Term of Use',
	'PRIVACY_RIGHTS': 'Privacy Rights',
	'CLOSE': 'Close',

	// Announcements ui
	'ANNOUNCEMENTS': 'Announcements',
	'ANNOUNCEMENT': 'Announcement',
	'ANNOUNCEMENT_CAPS': 'ANNOUNCEMENT',
	'ANNOUNCEMENT_EVENTTIME': 'Event time',
	'ANNOUNCEMENT_STARTTIME': 'Start time',
	'ANNOUNCEMENT_ENDTIME': 'End time',
	'ANNOUNCEMENT_UPCOMING_LABEL': 'Upcoming',
	'ANNOUNCEMENT_DESC': 'Description',
	'ActionRecommended': 'Recommended action',
	'ActionRequired': 'Required action',
	'EmergencyChange': 'Emergency change',
	'EmergencyMaintenance': 'Emergency maintenance',
	'EmergencyMaintenanceComplete': 'Emergency maintenance completed',
	'EmergencyMaintenanceExtended': 'Emergency maintenance extended',
	'EmergencyMaintenanceRescheduled': 'Emergency maintenance rescheduled',
	'Information': 'Information',
	'PlannedChange': 'Planned change',
	'PlannedChangeComplete': 'Planned change completed',
	'PlannedChangeExtended': 'Planned change extended',
	'PlannedChangeRescheduled': 'Planned change rescheduled',
	'ProductionEventNotification': 'Production event',
	'ScheduledMaintenance': 'Scheduled maintenance',
	'ANNOUNCEMENT_LINK': 'Link',
	'ALL_UPCOMING_LINK': 'See all New & Upcoming',
	'ANNOUNCEMENT_PUBLISHTIME': 'Publish time',
	'ANNOUNCEMENT_MARK_AS_READ': 'Mark as read',
	'ANNOUNCEMENT_MARK_AS_UNREAD': 'Mark as unread',
	'ANNOUNCEMENT_SUMMARY': 'Summary',
	'ANNOUNCEMENT_TYPE_LABEL': 'Type',
	'ANNOUNCEMENT_ACTIONS_LABEL': 'Actions',
	'ANNOUNCEMENT_UPCOMING_EVENTS_COUNT_LABEL': 'Upcoming events count',
	'ANNOUNCEMENT_UPCOMING_EVENT_LABEL': 'Upcoming event',
	'ANNOUNCEMENT_GO_BACK_LABEL': 'Go back',
	'ANNOUNCEMENT_BACK': 'Back',
	'ANNOUNCEMENT_ZERO_CONTENT_TITLE': 'New announcements will appear here.',
	'ANNOUNCEMENT_ZERO_CONTENT_DESC': 'Check back later for important events and issues for your Oracle Integration instances. <br>Your administrator may need to enable announcements for this instance.</br>',
	'ANNOUNCEMENT_UPCOMING_EVENTS_LABEL': 'Upcoming events',
	'ANNOUNCEMENT_READ': 'Read announcement',
	'ANNOUNCEMENT_UNREAD': 'Unread announcement',
	'ANNOUNCEMENT_GET_STARTED_LINK': 'Get started with announcements',

	'METERING': 'Metering',

	'CREATE': 'Create',
	'CREATE_ASSET': 'Create {0}',
	'CONTENT_LOADING': 'Loading',
	'PLEASE_WAIT': 'Please wait while we load your content',
	'SPACES': 'Spaces',
	'DECISIONS': 'Decision models',
	'DECISION': 'Decision model',

	'CREATION_DATE': 'Creation date',
	'OWNER': 'Owner',
	'DELETE': 'Delete',
	'CLONE': 'Clone',
	'SPACE': 'Space',
	'BY_SPACE_NAME': 'Space name',
	'ACTIVATION': 'Activate',
	'LOCKED': 'Locked',
	'LOCKED_BY': 'Locked by {0}',
	'UNLOCK': 'Unlock',
	'TAKEOVER': 'Takeover',
	'DOWNLOAD': 'Download',
	'NEW_SPACE': 'New Space',
	'NEW_SPACE_OPTION': '$[New Space$]',

	'BROWSE_QUICK_START': 'Start with a QuickStart',
	'IMPORT_PROCESS': 'Import an application',
	'IMPORT_DECISION': 'Import a decision model',
	'SAMPLE_DECISION': 'Start with a sample',
	'SAMPLE_DECISION_DESCRIPTION': 'Browse samples and select any sample to create decision model',
	'NEW_SPACE_TITLE': 'Create a space',
	'NEW_DECISION_TITLE': 'Create a decision model',
	'NEW_PROCESS_TITLE': 'Create an application',

	'IMPORT_FILE': 'File',
	'DESCRIPTION': 'Description',

	'ADMINISTRATION': 'Administration',

	'PROCESSES_BOILERPLATE_TITLE': 'Looks like you haven’t created any process applications yet.',
	'PROCESSES_BOILERPLATE_DESCRIPTION': 'Not sure where to begin? Click <a href="{0}" target="_blank">Learn More</a> for a step-by-step tutorial.<br/>Or, click <b>Create</b> to jump right in and build your first process application.',

	'DECISIONS_BOILERPLATE_TITLE': 'Looks like no decision models have been created yet.',
	'DECISIONS_BOILERPLATE_DESCRIPTION': 'This page will list all the decision models that you have created or<br/>that others have shared with you.<br/>Not sure where to begin? Click <b>Learn More</b> for a step-by-step tutorial.<br/>Or, click <b>Create</b> to build your first decision model.',

	'SPACES_BOILERPLATE_TITLE': 'Sharing is a good thing. So is organization.',
	'SPACES_BOILERPLATE_DESCRIPTION': 'Use spaces to group your process applications and<br/>decision models, and then share them with others in your<br/>organization. Click <b>Create</b> to make your first space.',
	'SPACE_PERMISSION_CHANGE_ERROR': 'You cannot change or remove member access to this space because an application in this space is locked.',
	'SINGLE_USER_INSUFFICIENT_RIGHTS': 'The user {0} has insufficient privileges. Review the user\'s roles and permissions.',
	'MULTI_USER_INSUFFICIENT_RIGHTS': 'The users below have insufficient privileges. Review the user\'s roles and permissions. {0}',

	'SELECT_ALL': 'Select all',
	'IDENTITY_NO_MATCHES_FOUND': 'No identity matches found',
	'VIEWER': 'Viewer',
	'EDITOR': 'Editor',
	'SPECIFY_USERS': 'Specify users',
	'SELECT_ROLE': 'Select role',
	'REMOVE': 'Remove',
	'SHARE': 'Share',
	'SHARE_SPACE': 'Share space',
	'SPACE_MEMBERS': 'Space members',
	'SHARED_SPACE_TITLE': 'This is a shared space',
	'SHARED_SPACE_DESCRIPTION': 'You are viewer of this space, so you cannot change any permissions or see who is member',
	'EDIT_SPACE': 'Edit space',
	'SUGGESTED_SPACE_NAME': 'My space {0}',
	'DELETE_DENIED': 'Unable to delete',
	'DELETE_DENIED_DESCRIPTION': 'The space {0} cannot be deleted, only owners can remove a space.',
	'USER_ALREADY_ADDED_TITLE': 'User already added',
	'USER_ALREADY_ADDED_DESCRIPTION': 'Try modifying the user role from the list.',

	'PCS_CREATE_TITLE': 'Select an option',
	'NEW_PROCESS_DESCRIPTION': 'We\'ll guide you through the main steps',
	'NEW_DECISION_DESCRIPTION': 'We\'ll guide you through the main steps',
	'NEW_SPACE_DESCRIPTION': 'Use spaces to house and share applications and models',
	'CLONE_PROCESS_TITLE': 'Clone an application',
	'CLONE_PROCESS_DESCRIPTION': 'Copy the process application, and all of its components, and assign it a new name',
	'NEW_PROCESS_QUICK_START_DESCRIPTION': 'Choose a ready-to-activate app and customize it as needed',
	'IMPORT_PROCESS_DESCRIPTION': 'Select an exported (.exp) file to import and edit',
	'IMPORT_DECISION_DESCRIPTION': 'Select an exported .dmn file to import and edit',
	'IMPORT': 'Import',
	'EXPORT': 'Export',
	'BROWSE': 'Browse',
	'GENERIC_ERROR_MESSAGE': 'There was an error. If the error persist, please contact the administrator',
	'DELETE_CONFIRMATION': 'Are you sure you want to delete {0}? This operation cannot be undone',
	'DMN_DELETE_CONFIRMATION': 'The model can not be deleted because is active. There might be applications consuming it. Do you want to force the deletion anyway?',
	'UNLOCK_CONFIRMATION': 'Are you sure you want to unlock {0}? Any unpublished changes will be lost',
	'TAKEOVER_CONFIRMATION': 'Are you sure you want to takeover {0}? This operation will not discard unpublished changes',
	'CREATED_BY': 'Created by',
	'CREATED': 'Created',
	'LAST_UPDATED': 'Last updated',
	'LAST_UPDATED_BY': 'Last updated by',
	'SHARED': 'Shared',
	'PRIVATE': 'Private',
	'OWNED_BY_ME': 'Owned by me',
	'SHARED_WITH_ME': 'Shared with me',
	'INVALID_NAME': 'Invalid name',
	'INVALID_NAME_DETAIL': 'Only special characters \'-\', \'_\', \'.\' and spaces are allowed.',
	'SUGGESTED_DECISION_NAME': 'Decision model {0}',
	'SUGGESTED_PROCESS_APP_NAME': 'Application{0}',
	'DUPLICATED_DECISION_NAME': 'Invalid decision model name',
	'DUPLICATED_PROCESS_APP_NAME': 'Invalid process application name',
	'DUPLICATED_PROCESS_APP_EXPLAINED': 'A process application with the same name already exists',
	'DUPLICATED_DECISION_NAME_EXPLAINED': 'A decision model with the same name already exists',
	'MASTER_PROCESS_APP': 'QuickStart master',
	'DERIVED_PROCESS_APP': 'QuickStart app',
	'REGULAR_PROCESS_APP': 'Process application',
	'PROCESS_APP_TYPE': 'Type',
	'PROCESS_APP_STATUS': 'Status',
	'INVALID_EXP': 'Invalid EXP file',
	'INVALID_EXP_EXPLANATION': 'Verify that the EXP file is a valid process application and try importing again',
	'FILE_REQUIRED_SUMMARY_MSG': 'File is required',
	'FILE_REQUIRED_DESC_MSG': 'Please select a file and try importing again',
	'INVALID_DMN': 'Invalid DMN file',
	'FAILED_TO_ACTIVATE_DMN': 'Failed to activate the decision model',
	'FAILED_TO_ACTIVATE_DMN_DETAILS': 'There was a problem while activating the decision Model. Try to activate it manually',
	'INVALID_DMN_EXPLANATION': 'Verify that the DMN is a valid decision model and try importing again',
	'OPEN_IMMEDIATELY': 'Open immediately',
	'ACTIVATE_DMN_MODEL': 'Activate the model',
	'MAX_LENGTH_CHARS': 'There are too many characters.',
	'MAX_LENGTH_CHARS_DETAIL': 'Enter {0} or fewer characters, not more.',
	'J_LAST_TIME_CAPTURED': 'Last time captured',
	'J_LAST_CAPTURED': 'Last captured',
	'J_SERVICE_STOPPED': 'Service stopped',
	'J_METERING_MSG_PACK_CONFIGURED': 'Configured',
	'J_METERING_MSG_PACK_USED': 'Configured',
	'J_METERING_BILLED_MSGS': 'Billable messages',
	'J_METERING_TOTAL_BILLED_MSGS': 'Usage',
	'J_METERING_PROCESS_BILLED_MSGS': 'Process',
	'J_METERING_INTEGRATION_BILLED_MSGS': 'Integration',
	'J_METERING_OVERAGE_USED': 'Within configuration',
	'J_METERING_MESSAGE_PACK_TITLE': 'Excess usage',
	'J_METERING_SUMMARY_TILE_MESSAGE_PACK_TITLE': 'Message packs',
	'J_METERING_SUMMARY_TILE_MESSAGES_TITLE': 'Messages',
	'J_METERING_OVERAGE_USED_PACKS': 'Excess packs',
	'J_METERING_CONFIGURED_PACKS': 'Configured packs',
	'J_METERING_OVERAGE_USED_EXCESS': 'Excess usage',
	'J_METERING_NO_ACTIVITY': 'No activity',
	'J_METERING_SERVICE_STOP': 'Service stop',
	'J_METERING_DAILY_MSG_PACK_USAGE': '1 week usage',
	'J_METERING_DAILY_OVERAGE_USAGE': '1 week excess usage',
	'J_METERING_MONTHLY_MSG_PACK_USAGE': '30 days usage',
	'J_METERING_MONTHLY_OVERAGE_USAGE': '30 days excess usage',
	'J_METERING_YEARLY_MSG_PACK_USAGE': '12 months usage',
	'J_METERING_YEARLY_OVERAGE_USAGE': '12 months excess usage',
	'J_BYOL_LABEL': 'BYOL account',
	'J_METERING_HOURLY_MSG_PACK_USAGE': '{0}',
	'J_METERING_MSG_PACK_USED_OVERRAGES': 'Excess usage',
	'J_METERING_SUMMARY_MSG_METRICS_TITLE': 'Summary of message metrics for {0}',
	'J_METERING': 'Usage metrics',
	'J_METERING_OVERAGE_VIEW_BTN': 'Excess usage',
	'J_METERING_AVG_VIEW_BTN': 'Average usage',
	'J_METERING_PREV_BTN': 'Previous',
	'J_METERING_NEXT_BTN': 'Next',
	'J_METERING_MSG_PACK_YAXIS1_TITLE': 'Message packs / Hour',
	'J_METERING_MSG_PACK_YAXIS2_TITLE': 'Billable messages per hour',
	'J_METERING_MSG_PACK_HOURLY_YAXIS1_TITLE': 'Message packs',
	'J_METERING_MSG_PACK_HOURLY_YAXIS2_TITLE': 'Billable messages',
	'J_METERING_SUMMARY_MAX_MSG_HEADER_TITLE': 'Max # of Msgs/Hour',
	'J_METERING_SUMMARY_EXCESS_USAGE_MSG_HEADER_TITLE': 'Msg pack excess usage',
	'J_METERING_SUMMARY_EXCESS_USAGE_HOURS_HEADER_TITLE': 'Total excess usage hours',
	'J_METERING_OVER_LABEL': 'Over',
	'J_METERING_OVERAGE_PANEL_HOURS_LABEL': 'Hours',
	'J_METERING_OVERAGE_PANEL_EXCESS_HOURS': 'Excess hours',
	'J_METERING_OVERAGE_PANEL_DATE_LABEL': 'Date',
	'J_METERING_OVERAGE_TOOLTIP_TIME': 'Time',
	'J_METERING_OVERAGE_TOOLTIP_MSG_PACK': 'Message packs: ',
	'J_METERING_OVERAGE_TOOLTIP_WITHIN_CONFIG': 'Within configuration: ',
	'J_METERING_OVERAGE_TOOLTIP_EXCESS_USAGE': 'Excess usage: ',
	'J_METERING_EXCESS_USAGE_DESC': 'Excess packs are message packs that are consumed beyond hourly subscribed value',
	'J_METERING_WEEKLY_VIEW_TEXT': 'Week',
	'J_METERING_MONTHLY_VIEW_TEXT': 'Month',
	'J_METERING_YEARLY_VIEW_TEXT': 'Year',
	'J_METERING_DAILY_VIEW_TEXT': 'Day',
	'J_METERING_MESSAGES': 'Messages',
	'J_METERING_EXPORT_METRICS_DLG_TITLE': 'Export usage metrics',
	'J_METERING_EXPORT_METRICS_FROM_DATE': 'Start date',
	'J_METERING_EXPORT_METRICS_TO_DATE': 'End date',
	'J_METERING_EXPORT_METRICS_BTN_LABEL': 'Export',
	'J_METERING_VBCS_METRICS_EXCLUDED_DESC': 'Billable messages shown in the chart do not include Visual Builder usage',
	'J_METERING_EXPORT_INVALID_DATE_ERR_TITLE': 'Invalid date',
	'J_METERING_EXPORT_EMPTY_DATE_ERR_MSG': 'Please select start date.',
	'J_METERING_EXPORT_INVALID_DATE_ERR_MSG': 'Start date should not be greater than end date.',
	'J_METERING_EXPORT_ERROR': 'An error occurred when trying to download the csv file.',
	'J_METERING_EXPORT_STARTED': 'Downloading usage metrics csv file has been started. Please check your browser\'s downloads list for progress and to access the file.',
	'DB_SPACE': 'Data retention',
	'DB_KEEP_LIVE_INSTANCES': 'Keep live instances open for max',
	'DB_KEEP_RECENT_INSTANCES': 'Keep recently closed instances for',
	'DB_DAYS': 'Days',
	'DB_HOURS': 'Hours',
	'DB_NOTE_CRAWLER': 'Note: OIC uses a continuous crawler job to auto clean data based on above retention',
	'DB_OIC_LOW_SPACE': 'If/when OIC starts to run low on space, OIC will',
	'DB_OIC_LOW_SPACE_GENERIC_MESAGE': 'If/when OIC becomes critically low on space, OIC will reject incomming messages and stop schedule flows.',
	'DB_NOTE': 'Control how Oracle Integration retains your transactional data. Runtime instances of active integrations and processes are purged to free up space for the newer data. Specify how long to keep the older data normally - as well as when the space starts getting low. When the space reaches a Critical state, the system rejects incoming requests and stops all processes and integrations from running until more space becomes available. ',
	'DB_LONG_INSTANCES': 'How long to keep runtime instances',
	'DB_KEEP_LIVE': 'Keep live instances',
	'DB_KEEP_LIVE_NOTE': 'Live  instances are waiting, running, or with a recoverable fault',
	'DB_KEEP_CLOSED': 'Keep closed instances',
	'DB_KEEP_CLOSED_NOTE': 'Closed instances are completed successfully or faulted without possibility of recovery',
	'DB_LOW_SPACE': 'If space starts getting low',
	'DB_LOW_SPACE_NOTE': 'When the data reaches a warning state, it begins to manage the space more aggressively, and a notification email is sent to the recipient email address(es) configured in the notification section. The system begins to use these alternate retention period settings when purging runtime data. It is required to set them lower than standard settings.',
	'DB_STANDARD_NOTE': 'The system uses these standard retention period settings when purging runtime data.',
	'DB_ALTERNATE_PERIOD_LABEL': 'Alternate (Low space) settings',
	'DB_STANDARD_PERIOD_LABEL': 'Standard settings',
	'DB_SYSTEM_SETTINGS_LABEL': 'Use system defaults',
	'DB_USER_SETTINGS_LABEL': 'Use my settings',
	'DB_ADVANCED_NOTE': 'You can designate and run a custom process or integration recipe for advanced resource management options.',
	'DB_CUSTOM_RECIPE_LABEL': 'Run custom recipe',
	'DB_EMERGENCY': 'In case of emergency',
	'DB_EMERGENCY_NOTE': 'When the data reaches a Critical state, the system rejects incoming requests and stops all scheduled recipes from running until more space becomes available.',
	'DB_RETENTION_SETTINGS_LABEL': 'Retention settings',
	'DB_SYSTEM_SETTINGS_DIALOG_LABEL': 'Use the settings currently in use by the system',
	'DB_USER_SETTINGS_DIALOG_LABEL': 'Use my one-time settings',
	'DB_PURGE': 'Purge now',
	'DB_PURGE_LIVE': 'Purge live instances older than',
	'DB_PURGE_TERMINATED': 'Purge terminated instances older than',
	'DB_PURGE_HEADER': 'Purge runtime data',
	'DB_PURGE_NOTE': 'Immediately purge older instances of integrations and processes. This is a one-off procedure and <b>cannot be undone.</b> Automated purges will continue to run.',
	'DB_PURGE_SUCCESS_MSG': 'Manual purge has been initiated successfully',
	'DB_PURGE_ERROR_MSG': 'Data retention settings purge failed',
	'DB_SAVE_SUCCESS_MSG': 'Data retention settings saved successfully',
	'DB_SAVE_ERROR_MSG': 'Data retention settings save failed',
	'DB_REVERT_SUCCESS_MSG': 'Data retention settings reverted successfully',
	'DB_REFRESH_ERROR_MSG': 'Error occurred while refreshing data settings',
	'DB_PREFERENCES_TITLE': 'Data retention preferences',
	'DB_PREFERENCES_STATUS': 'Data retention status',
	'DB_PAGE_TITLE': 'Data retention',
	'DB_SETTINGS_PURGE_ACTION': 'Perform manual purge',
	'DB_STATUS_GOOD': 'The system has enough space to keep your runtime data at least as long as specified by your data retention settings.',
	'DB_STATUS_WARNING': 'Very little room is left for new instances. Runtime data grows faster than it is purged. If this trend continues, the system will stop accepting incoming requests until more space is available.',
	'DB_STATUS_CRITICAL': 'We are sorry, but there is no more room left for new data. The system will no longer accept incoming requests until more space becomes available.',
	'DB_STATUS_RESOURCES_NOTE': 'How to request more resources',
	'DB_STATUS_LIST_TITLE': 'What you can do',
	'DB_STATUS_LIST_ITEM1': 'Reduce retention times so that more data can be purged regularly.',
	'DB_STATUS_LIST_ITEM2': 'Purge data manually ("Purge Now") using shorter retention times for this one-off purge.',
	'DB_STATUS_LIST_ITEM3': 'Check the dashboard for the recipes that recently have generated the most instances and temporarily deactivated all or some of those recipes.',
	'DB_STATUS_LIST_ITEM4': 'Request to have some more space added to your Oracle Integration.',
	'DB_STATUS': 'Status',
	'DB_DISTRIBUTION_LIST': 'Notifications',
	'DB_DISTRIBUTION_NOTE': 'When the data reached a warning or critical state a notification email is sent to these people.',
	'DB_INVALID_INPUT': 'Invalid data retention settings. Please fix the error before proceeding to save.',
	'DB_INVALID_EMAIL': 'Invalid email address entered.',
	'DB_EMAIL_PLACEHOLDER': 'Enter a set of comma-separated email addresses',
	'DB_REFRESH_TITLE': 'Refresh settings',
	'DB_RETENTION_INVALID': 'Invalid value',
	'DB_RETENTION_INVALID_DESC': 'Enter value lesser than standard instances',
	'DB_RETENTION_LIVE_VALUE_INVALID_DESC': 'Enter value greater than closed instances',
	'DB_EMAIL_HINT': 'A set of comma seprated emails',
	'DB_EMAIL_HINT_MSG': 'Not a valid email format',
	'DB_INPUT_NUMBER_INVALID': 'Not a valid number, enter a number without decimals',
	'DB_RETENTION_NEVER_PURGE_OPTION_LABEL': 'Keep all live instances',
	'DB_RETENTION_SET_PURGE_OPTION_LABEL': 'Keep live instances',
	'DB_RETENTION_PROCESS_AGGRESIVE_DESCRIPTION': 'Process settings above are also used for low space settings',
	'DB_MANUAL_PURGE_HEADER': 'Manual purge',
	'DB_MANUAL_PURGES_WARNING_MESSAGE': 'Manual purges happens instantly and cannot be undone.',
	'DB_DISTRIBUTION_EMAIL_RECIPIENTS': 'Recipient email address(es)',
	
	'VIEW_ALL': 'Browse store',
	'ALL_CAUGHT_UP': 'You are all caught up!',
	'EXPECTING_TO_SEE_ASSIGNED': 'Expecting to see assigned tasks?',

	'CERTIFICATES': 'Certificates',
	'CERTIFICATE': 'Certificate',
	'CERTIFICATES_CONFIGURATION': 'Certificates',
	'UPLOAD': 'Upload',
	'UPDATE': 'Update',
	'VIEW': 'View',
	'PREINSTALLED': 'System',
	'USER': 'User',
	'UPLOADED': 'Uploaded',
	'DELETE_CERTIFICATE': 'Delete',
	'DELETE_CERTIFICATE_DIALOG_TITLE': 'Delete certificate',
	'DELETE_CERTIFICATE_DIALOG_EXPLANATION': 'Are you sure you want to delete certificate?',
	'SORT_BY': 'Sort by',
	'TYPE': 'Type',
	'CATEGORY': 'Category',
	'KEY_STORE': 'Key store',
	'UPLOAD_CERTIFICATE_DIALOG_TITLE': 'Upload certificate',
	'UPDATE_CERTIFICATE_DIALOG_TITLE': 'Update certificate',
	'UPLOAD_CERTIFICATE_DIALOG_NOTE': 'Enter a certificate alias name and select a certificate file. Certificate allows Oracle Integration to connect with external services. If the external service/endpoint needs a specific certificate, request the certificate and then import it into Oracle Integration.',
	'CERTIFICATE_TYPE_LABEL': 'Type',
	'CERTIFICATE_ID': 'Identifier',
	'CERTIFICATE_ALIAS_LABEL': 'Alias name',
	'CERTIFICATE_DESCRIPTION_LABEL': 'Description',
	'CERTIFICATE_FILE_LABEL': 'File (.cer/.crt/..)',
	'CERTIFICATE_FILE_IDENTITY_LABEL': 'Select keystore file (.jks)',
	'CERTIFICATE_FILE_PGP_LABEL': 'PGP file',
	'CERTIFICATE_KEYSTORE_PASSWORD_LABEL': 'Keystore password',
	'CERTIFICATE_KEY_ALIAS_LABEL': 'Key alias mame(s)',
	'CERTIFICATE_KEY_PASSWORD_LABEL': 'Key password(s)',
	'CERTIFICATE_PASSPHRASE_LABEL': 'PGP private key password',
	'CERTIFICATE_ASCII_ALGORITHM_LABEL': 'ASCII-Armor encryption format',
	'CERTIFICATE_CIPHER_ALGORITHM_LABEL': 'Cipher algorithm',
	'CERTIFICATE_CATEGORY_LABEL': 'Category',
	'CERTIFICATE_INSALL_BY_LABEL': 'Installed by',
	'CERTIFICATE_ALIAS_HINT': 'Enter a name using letters (A-Z a-z), numbers (0-9) and  special characters ( _ - ). It cannot be longer than 50 characters and  must start with a letter.',
	'CERTIFICATE_ALIAS_MESSAGE': 'Invalid alias name',
	'CERTIFICATE_DELETE_SUCCESSFUL': 'Certificate was deleted successfully with alias name {0}',
	'CERTIFICATE_UPLOAD_SUCCESSFUL': 'Certificate was uploaded successfully with alias name {0}',
	'CERTIFICATE_UPDATE_SUCCESSFUL': 'Certificate was updated successfully with alias name {0}',
	'CERTIFICATE_REPLACE_SUCCESSFUL': 'Certificate was imported and replaced successfully with alias name {0}',
	'CERTIFICATE_UPDATE_IDENTITY_NOT_ALLOWED': 'Identity certificate can not be updated, please delete and upload again.',
	'TRUST': 'Trust',
	'OWSM': 'Message protection',
	'IDENTITY': 'Identity',
	'PUBLIC': 'Public',
	'REPLACE_CERTIFICATE_DIALOG_TITLE': 'Replacing existing certificate?',
	'REPLACE_CERTIFICATE_DIALOG_NOTE': 'A certificate with the same alias name and type already exists. It will be replaced when the new certificate {0} is imported.',
	'IMPORT_AND_REPLACE': 'Import and replace',
	'CERTIFICATE_DETAIL_ALIAS': 'Alias',
	'CERTIFICATE_DETAIL_ALIAS_NAME': 'Alias name',
	'CERTIFICATE_DETAIL_SUBJECT': 'Subject',
	'CERTIFICATE_DETAIL_COMMON_NAME': 'Common name',
	'CERTIFICATE_DETAIL_ORGANIZATION_USAGE': 'Organization usage',
	'CERTIFICATE_DETAIL_ORGANIZATION': 'Organization',
	'CERTIFICATE_DETAIL_TOWN': 'Town',
	'CERTIFICATE_DETAIL_STATE': 'State',
	'CERTIFICATE_DETAIL_COUNTRY': 'Country',
	'CERTIFICATE_DETAIL_ISSUED_BY': 'Issued by',
	'CERTIFICATE_DETAIL_ISSUED': 'Issued',
	'CERTIFICATE_DETAIL_EXPIRES': 'Expires',
	'CERTIFICATE_DETAIL_VALIDITY': 'Validity',
	'CERTIFICATE_SORT_DSC': 'Expiration date (later)',
	'CERTIFICATE_SORT_ASC': 'Expiration date (sooner)',
	'CERTIFICATE_SEARCH_PLACEHOLDER': 'Type name...',
	'CERTIFICATE_NAME_PLACEHOLDER': 'Type a name',
	'CERTIFICATE_DESC_PLACEHOLDER': 'What does it do?',
	'CERTIFICATE_PASSWORD_PLACEHOLDER': '*******',
	'CERTIFICATE_EXPIRED': 'Expired',
	'CERTIFICATE_EXPIRES': 'Expires in {0}',
	'CERTIFICATE_EXPIRES_IN': 'In {0}',
	'CERTIFICATE_VALID_FROM': 'From {0}',
	'CERTIFICATE_YEARS': '{0} Years',
	'CERTIFICATE_MONTHS': '{0} Months',
	'CERTIFICATE_DAYS': '{0} Days',
	'CERTIFICATE_ALIAS_REQUIRED': 'Required',
	'CERTIFICATE_ALIAS_REQUIRED_MSG': 'Please enter a valid value',
	'CERTIFICATE_DETAILS': 'Certificate details',
	'CERTIFICATE_TYPE_X509': 'X.509 (SSL transport)',
	'CERTIFICATE_TYPE_SAML': 'SAML (Authentication and authorization)',
	'CERTIFICATE_TYPE_PGP': 'PGP (Encryption and decryption)',
	'CIPHER_CAST5': 'CAST5',
	'CIPHER_TDES': 'TDES',
	'CIPHER_AES128': 'AES128',
	'CIPHER_AES192': 'AES192',
	'CIPHER_AES256': 'AES256',
	'CONFIGURED': 'Configured',
	'INPROGRESS': 'Draft',
	'CERTIFICATE_IN_USE_TITLE': 'Certificate is in use',
	'CERTIFICATE_UPDATE_USAGE_WARNING': 'Certificate in is use by {0} integrations. Updating it will impact these integrations.',
	'CERTIFICATE_UPDATE_USAGE_NOT_ALLOWED': 'Certificate cannot be updated at this time because <b>{0}</b> active integrations are using it. Deactivate the integration and then update the certificate. Then reactivate the integration to use it.',
	'CERTIFICATE_DELETE_USAGE_NOT_ALLOWED': 'Certificate cannot be deleted at this time because <b>{0}</b> integrations are using it. Deleting the certificate would invalidate these integrations. Active integrations would stop running. Remove the certificate from the integrations and then delete the certificate.',
	'CERTIFICATE_INTEGRATION_USAGE_COUNT': 'Integrations using this certificate: {0}',
	'INTEGRATION_ACTIVE': 'Active: {0}',
	'INTEGRATION_INACTIVE': 'Inctive: {0}',

	'FEATURE_FLAG_LIST': 'Enabled features',
	'FEATURE_FLAG_REFRESH_BUTTON': 'Refresh features',

	'TRY_A_RECIPE': 'Try a recipe',
	'START_WITH_SOLUTIONS': 'Start with one of these solutions:',
	'USE_AS_STARTING_POINT': 'You can use this recipe as a starting point for your applications.',
	'RUN_DEMO': 'Run demo',
	'WATCH_AGAIN': 'Watch again',

	'LEARN': 'Learn',
	'RECENT': 'Recent',
	'DASHCARDS': 'Dashcards',
	'SUMMARY': 'Summary',

	'IN_PROGRESS': 'In progress',
	'IN_ERROR': 'In error',
	'COMPLETED': 'Completed',
	'TOTAL_RECEIVED': 'Total received',
	'FAILED': 'Failed',
	'SUCCESSFUL': 'Successful',

	'GOOD': 'Good',
	'CRITICAL': 'Critical',

	'OPPORTUNITY_TO_ORDER': 'Employee onboarding',
	'INTEGRATION_RECIPE': 'Integration recipe',
	'OPPORTUNITY_SALES': 'Watch OIC orchestrating an employee onboarding process.',
	'ORDER_SUCCESSFUL': 'Order successful!',

	'INSTANCE_1': 'Instance',
	'N_INSTANCES': 'Instances',
	'MESSAGE_1': 'Message',
	'N_MESSAGES': 'Messages',
	'FAILED_ACTIVATIONS': 'Failed activations',
	'TOTAL_TASKS': 'Total Tasks',

	'TRAVEL_APPROVAL': 'Travel approval',
	'PROCESS_RECIPE': 'Process recipe',
	'TRAVEL_REQUEST': 'Watch an employee submit a travel request for approval.',
	'REQUEST_SUCCESSFUL': 'Request approved!',

	'ABOUT_INTEGRATIONS': 'About integrations',

	'EXPLORE_ADAPTERS': 'Explore adapters',
	'DEVELOP_WITH_APIS': 'Develop with APIs',
	'BROWSE_SOLUTIONS': 'Browse solutions',
	'CREATE_A_WEB_APPLICATION': 'Create a web application',

	'GO_TO_HELP_CENTER': 'Go to Help Center',
	'SEE_WHATS_NEW': 'See what\'s new',
	'VIEW_ALL_VIDEOS': 'View all videos',
	'CONNECT_WITH_EXPERTS': 'Connect with experts',

	'START_AN_APPLICATION': 'Start an application',
	'HOW_DO_I_WORK_ON_TASKS': 'How do I work on tasks?',
	'CAN_I_REASSIGN_TASKS': 'Can I reassign my tasks to someone else?',
	'HOW_DO_I_ADD_DOCUMENT': 'How do I add a document to a task?',

	'PREFERENCES_USER_MENU': 'Preferences',
	'TIMEZONE_SETTINGS_TITLE': 'Time zone settings',
	'SELECT_TIMEZONE_LABEL': 'Time zone',
	'TIMEZONE_SELECT_PLACEHOLDER': 'Select preferred timezone',
	'HEALTH_CHECK_AGENTS': 'Agents',
	'HEALTH_CHECK_EMAIL': 'Email service',
	'INT_VLE_ERROR': 'String size limit',
	'ACTIVE_INT': 'Active integrations',
	'HEALTH_CHECK_DATABASE': 'Service Instance quiesced',

	'B2BDOCUMENTS': 'B2B Documents',
	'B2BSCHEMAS': 'B2B Schemas',
	'B2BMETADATA': 'B2B Metadata',
	'B2BSCHEMAEDITOR': 'B2B SchemaEditor',
	'B2B': 'B2B',

	'HealthcareDOCUMENTS': 'Healthcare Documents',
	'HealthcareSCHEMAS': 'Healthcare Schemas',
	'HealthcareMETADATA': 'Healthcare Metadata',
	'HealthcareSCHEMAEDITOR': 'Healthcare SchemaEditor',
	'Healthcare': 'Healthcare',

	'POD_MIGRATION': 'Import/Export',
	'CLONE_JOBS': 'Import/Export jobs',
	'IMPORT_JOB_TITLE': 'Create import job',
	'IMPORT_JOB_TEXT': 'Start a job to import a saved archive into the current instance from your allocated storage area.',
	'EXPORT_JOB_TITLE': 'Create export job',
	'EXPORT_JOB_TEXT': 'Start a job to export the current instance to an archive file in your allocated storage area.',
	'CLONE_JOB_NAME': 'Job name',
	'CLONE_IMPORT_MODE': 'Import mode',
	'CLONE_ARCHIVE_FILENAME': 'Archive Filename',
	'IMPORT_JOB_BTN': 'Start import job',
	'EXPORT_JOB_BTN': 'Start export job',
	'EXPORT_SECURITY_ARTIFACTS': 'Export security artifacts',
	'IMPORT_SECURITY_ARTIFACTS': 'Include security artifacts',
	'START_SCHEDULES_SELECT': 'Start schedules',
	'STARTING': 'Starting',
	'IMPORT_ONLY': 'Import',
	'IMPORT_ACTIVATE': 'Import and activate',
	'ACTIVATE_ONLY': 'Activate',
	'START_SCHEDULES_ONLY': 'Start schedules',
	'STORAGE_CONFIGURATION': 'Storage',
	'STORAGE_CONFIGURATION_NAME_PLACEHOLDER': 'Name for instance storage',
	'INSTANCE_STORAGE_TITLE': 'Instance storage',
	'USER_NAME': 'User name',
	'INSTANCE_STORAGE_SWIFT_URL': 'Swift URL',
	'INSTANCE_STORAGE_SWIFT_URL_PLACEHOLDER': 'Storage URL, http://oraclecloud.com/v1/passdevoic/swift',
	'INSTANCE_STORAGE_HEADING': 'An existing object storage bucket instance is required to export and import archive jobs on the Import/Export page. Provide the location and credentials of your object storage bucket instance.',
	'INSTANCE_STORAGE_EMPTY': 'You must first set up where to store and retrieve your archives',
	'NO_INSTANCE_JOBS': 'You have no Import/Export jobs',
	'GET_MORE_INFO': 'Get more information',
	'INSTANCE_ZERO_DAY_DESC': 'Generate a new archive of this integration instance, or import a previously saved archive in to this integration instance.',
	'INSTANCE_STORAGE_CONFIG': 'Configure instance storage',
	'CONFIGURE_NOW': 'Configure now',
	'JOB_SUMMARY': 'Job summary',
	'JOB_TYPE': 'Job type',
	'EXPORT_JOB_STARTED_SUCCESS': 'Export job has been successfully started',
	'IMPORT_JOB_STARTED_SUCCESS': 'Import job has been successfully started',
	'STORAGE_DOES_NOT_EXIST': 'No instance storage available. Please configure your storage.',
	'GET_ARCHIVES_ERROR': 'Some error occurred while getting archive files for storage: {0}',
	'NO_INSTANCE_STORAGE': 'No instance storage configured',
	'STORAGE_SAVED_SUCCESS': 'Storage {0} changes saved successfully',
	'STORAGE_UPDATE_SUCCESS': 'Storage {0} changes updated successfully',
	'STORAGE_RESET_SUCCESS': 'Storage {0} changes reset successful',
	'EXPORT_DESC_PLACEHOLDER': 'Add a description',
	'totalResourceCount': 'Number of total resources',
	'resourceImportCount': 'Number of resources imported',
	'totalActivationCount': 'Number of resources to activate',
	'activationSuccessCount': 'Number of resources activated',
	'resourceCount': 'Number of total resources',
	'errorMessage': 'Error message',
	'FAILURE_MESSAGE': 'Failure message',
	'ARCHIVE_NAME': 'Archive name',
	'COMPONENT_NAME': 'Component name',
	'COMPONENTS_HEADING': 'Components',
	'PERCENTAGE': 'Percentage',
	'DOWNLOAD_REPORT': 'Download detailed report',
	'SECURITY_ARTIFACT': 'Security artifacts',
	'COMPLETED_WITH_WARNINGS': 'Completed with warnings',
	'IMPORT_OPTIONS': 'Import options',
	'RESET_STORAGE_DIALOG_TITLE': 'Reset storage',
	'RESET_STORAGE_DIALOG_EXPLANATION': 'Are you sure you want to reset storage?',
	'RESET_STORAGE_ERROR': 'Storage does not exist.',
	'SAVE_STORAGE_FORM_INVALID': 'Please fill all the details.',
	'URL_VALIDATION_HINT': 'The URL is invalid. Enter a valid URL. The URL must start with http or https, followed by fully qualified hostname or IP address and optionally port and query parameter. Special characters need to be encoded.',
	'URL_VALIDATION_MESSAGE': 'URL is invalid',
	'STORAGE_ALIAS_MESSAGE': 'Storage name is invalid',

	'SERVER_SETTINGS': 'Settings',
	'USERS': 'Users',
	'GROUPS': 'Groups',
	'FOLDERS': 'Folders',
	'PERMISSIONS': 'Permissions',

	'OPTIN_HEADER': 'Controlled features',
	'FEATURE_NAME': 'Feature name',
	'FEATURE_PAGE_DESCRIPTION': 'The following controlled features are available for self-service enablement. Please be aware that feature flags in general availability stage are not shown in this list.',
	'FEATURE_PAGE_DESCRIPTION_LINK': 'For more details please visit our blog for <a href="https://blogs.oracle.com/integration/enabling-the-future-today-feature-flags-in-oracle-integration-cloud" target="_blank">Controlled Features</a>.',
	'ENABLE_FEATURE_BTN': 'Enable',
	'ENABLE_FEATURE_DIALOG_TITLE': 'Enable feature',
	'ENABLE_FEATURE_DIALOG_EXPLANATION': 'Once this feature is enabled, you can only disable it by contacting Oracle customer support. Please note that after disabling the feature, artifacts built using the feature are not automatically removed. Do you want to enable this feature?',
	'ENABLE_FEATURE_DIALOG_HIGHER_PCAR_EXPLANATION': 'The feature is not available in your current instance yet. Your instance version is {0} and the feature is available in {1}. It will be available in your instance when your instance is upgraded to future release.',
	'ENABLE_FEATURE_SUCCESS_MSG': 'Feature flag {0} was successfully enabled.',
	'ENABLE_FEATURE_ERROR_MSG': 'Failed to enable feature flag {0}. Cause: {1}',

	'SCHEDULE_UPGRADE': 'Schedule upgrade',
	'SCHEDULE_UPGRADE_MSG': 'The upgrade of this Oracle Integration instance is currently scheduled for <b>{0}</b>. After this upgrade, expect faster performance, greater reliability, and our latest features.',
	'UPGRADE_NOT_SCHEDULED': 'Upgrade not yet scheduled',
	'UPGRADE_SCHEDULED': 'Your upgrade is scheduled',
	'UPGRADE_CONFIRMED': 'Upgrade request confirmed',
	'HOW_DOES_IT_WORK': 'How does it work?',
	'UPGRADE_GUIDE_FIRST_LINE': 'Each Oracle Integration instance must be individually scheduled for upgrade. You <a href="{0}" target="_blank">create a new compartment in the OCI console</a> and then list the compartment\'s OCID value in the field below.',
	'UPGRADE_GUIDE_SECOND_LINE': 'During the upgrade, your metadata and inflight instances are moved to the new instance. Your new Gen 2 instance retains the same URL.',
	'UPGRADE_WINDOW': 'Upgrade window',
	'UPGRADE_WINDOW_TEXT': 'Choose an upgrade window, enter your compartment\'s OCID value, and a contact email. ',
	'UPGRADED_WINDOW_TEXT': 'If you need to make changes, click Cancel Request first. When done ',
	'COMMON_UPGRADE_WINDOW_TEXT': 'Click <b>Submit Request</b> so Oracle can schedule your upgrade and send you a confirmation email. Questions? <a href="{0}" target="_blank">See the FAQ</a>',
	'COMPARTMENT_OCID': 'Compartment OCID',
	'CONTACT_EMAIL': 'Contact email(s)',
	'SUBMIT_REQUEST': 'Submit request',
	'CHANGE_REQUEST': 'Change request',
	'CANCEL_REQUEST': 'Cancel request',
	'COMPARTMENT_PLACEHOLDER': 'Enter the OCID that identifies your new compartment',
	'EMAIL_PLACEHOLDER': 'Enter a email address or list of comma-separated email addresses to contact you about this instance\'s upgrade',
	'SELECT_UPGRADE_WINDOW': 'Select an upgrade window',
	'OCID_VALUE_INVALID': 'Not a valid ocid value. It should start with \'ocid\' followed by numbers or alphabets or special character- "."',
	'COMPLETE_PREREQUISITES': 'Complete prerequisites',
	'WHITELIST_IP': 'If needed, whitelist your instance’s IP addresses.',
	'WHITELIST_TEXT': 'New ingress and egress IP addresses will be provided below before the upgrade.',
	'INGRESS_IP': 'Ingress IP address(es)',
	'EGRESS_IP': 'Egress IP address(es)',
	'ENTERING_ORACLE_INTEGRATION': 'Entering Oracle Integration',
	'EXITING_ORACLE_INTEGRATION': 'Exiting Oracle Integration',
	'CONFIGURE_IDENTITIES': 'Configure identities for Oracle Integration Generation 2',
	'USER_FEDERATION': 'Perform user federation',
	'PERMISSION_POLICIES': 'Create permission policies',
	'WAIT_FOR_SCHEDULED_UPGRADE': 'Wait for your scheduled upgrade',
	'WAIT_SCHEDULED_TEXT': 'Then use your Oracle Integration Generation 2 instance available in your cloud account.',
	'INSTANCE_DELETE_SUCCESSFUL': 'Upgrade request is cancelled successfully',
	'DATA_REFRESHED': 'Upgrade data is refreshed',
	'INSTANCE_CREATE_SUCCESSFUL': 'Upgrade request submitted successfully',
	'UPGRADE_BANNER_TITLE': 'Schedule your Oracle Integration upgrade now',
	'UPGRADE_BANNER_IST_LINE': 'Get the benefits of Oracle\'s latest cloud infrastructure with Oracle Integration Generation 2. ',
	'INSTANCE_UPDATE_SUCCESSFUL': 'Instance updated successfully',
	'SCHEDULE': 'Schedule',
	'FIND_ACCELERATOR_LABEL': 'Search all',
	'INSTALLED_LABEL': 'INSTALLED',
	'UPDATE_LABEL': 'UPDATE',
	'ACCELERATOR_BUILT_BY': 'Built by ',
	'BA_LABEL': 'Business accelerator',
	'TA_LABEL': 'Technical accelerator',
	'R_LABEL': 'Recipe',
	'BA_NAME': 'BA',
	'TA_NAME': 'TA',
	'R_NAME': 'R',
	'ACCELERATOR_LABEL': 'ACCELERATOR',
	'RECIPE_LABEL': 'RECIPE',
	'PREMIUM_LABEL': 'premium',
	'TECHNICAL_LABEL': 'technical',
	'SIMPLE_LABEL': 'simple',
	'UPGRADE_BANNER_2ND_LINE': 'your free, automated upgrade now, or <a href="{0}" target="_blank">learn more</a> about the upgrade.',
	'SCHEDULE_UPGRADE_LINK_TEXT': 'Review the details of your upgrade',
	'UPGRADE_GUIDE': 'Each Oracle Integration instance is scheduled for upgrade. During the upgrade, a new Oracle Integration Generation 2 instance is created with the same URL, and all configuration and data are moved to the new instance. The upgrade takes several hours during which inflight instances are paused and no users can access the instance.',
	'UPGRADE_TEXT': 'Your current upgrade information is shown below. <ul><li>If needed, select a different upgrade window.</li><li>Review the <b>Contact Email(s)</b> field and correct or add addresses (comma-separated) as needed. This field identifies where notifications are sent.</li><li>The <b>Compartment OCID</b> identifies the <a href="{0}" target="_blank">OCI compartment</a> in which the new Oracle Integration Generation 2 instance is created. This field is auto-populated with the root compartment’s OCID. However, we recommend creating a dedicated compartment and entering its OCID here instead. See here <a href="{1}" target="_blank"><b>how to create a new OCI Compartment.</b></a></li></ul>If you make changes, be sure to click <b>Update</b>. Questions? <a href="{2}" target="_blank">See the FAQ.</a>',
	'NEXT_STEPS_LABEL': 'What to do next?',
	'UPGRADE_WINDOW_LOCK_LABEL': 'Note the upgrade window lock.',
	'UPGRADE_WINDOW_LOCK_TEXT': 'Your upgrade window locks three weeks before the scheduled upgrade. Once locked, you can’t start/stop or scale up/down your instance or perform other lifecycle operations until the upgrade is complete.<br/>Ensure that your instance is not stopped when your upgrade window locks.',
	'TEST_UPGRADED_INSTANCE_LABEL': 'Sign in to the upgraded instance and test it.',
	'TEST_UPGRADED_INSTANCE_TEXT': 'Once the upgrade is complete, perform regression testing. If you find issues, open a service request. <a href="{0}" target="_blank">Carefully read through these steps in the upgrade documentation.</a>',
	'NOT_ASSIGNED': '{0} will be available on <b>{1}</b>',
	'COPY_TO_CLIPBOARD': 'Copy to clipboard',
	'COPIED_TEXT': 'Copied to clipboard',
	'UPDATE_OCID_DIALOG_TITLE': 'Change compartment OCID',
	'UPDATE_OCID_DIALOG_MSG': 'Identify the OCID of the compartment in which the new Oracle Integration Generation 2 instance will be created. We recommend creating a new compartment and entering the OCID below.',
	'CHANGE_OCID': 'Change OCID',
	'NO_INSTANCE_AVAILABLE': 'Your upgrade is not scheduled yet, please check back later.',
	'REFRESH_ICON_TOOLTIP': 'Click to see if additional information has been added since your last update.',
	'GOTO_LABEL': 'Go to',
	'ORDER_OPPURTUNITY_FOR_SALESFORCE': 'Opportunity to order',
	'ORDER_SALES_SALESFORCE': 'Watch how a sales opportunity in Salesforce triggers a new order in NetSuite.',
	'NEW_USER_CARD_TITLE': 'For the new user card',
	'A_LITTLE_MORE_ADVANCED_CARD_TITLE': 'A little more advanced',
	'SOLUTIONS': 'Solutions',
	'ACCELERATORS_AND_RECIPES': 'Accelerators & Recipes',
	'START_WITH_ONE_OF_THESE_PREASSEMBLED_SOLUTIONS': 'Start with one of these pre-assembled solutions...then make it your own!',
	'AGENTS_UPGRADE_BANNER_TEXT_old': 'Upgraded your instance to Oracle Integration 3 but couldn\'t migrate some connectivity agents. To recover the connectivity with the on-premises network, you must complete post-upgrade tasks.<a href="{0}" target="_blank"> View post-upgrade tasks</a>. Ignore if agents are already configured.',
	'AGENTS_UPGRADE_BANNER_TEXT': 'Upgraded your instance to Oracle Integration 3, but {0} could not be migrated. To recover the connectivity with the on-premises network, you must complete post-upgrade tasks.<a href="{1}" target="_blank"> View post-upgrade tasks</a>. Ignore if agents are already configured.',
	'AGENTS_AND_ENDPOINTS_BANNER_TEXT': 'Upgraded your instance to Oracle Integration 3, but {0} could not be migrated. To recreate the custom endpoint, follow the steps in this document: <a href="{1}" target="_blank">Configure custom endpoint</a>. To recover the connectivity with the on-premises network, you must complete post-upgrade tasks.<a href="{2}" target="_blank"> View post-upgrade tasks</a>. Ignore if agents are already configured.',
	'AGENTS_ONLY_BANNER_TEXT': 'Upgraded your instance to Oracle Integration 3, but {0} could not be migrated. To recover the connectivity with the on-premises network, you must complete post-upgrade tasks.<a href="{1}" target="_blank"> View post-upgrade tasks</a>. Ignore if agents are already configured.',
	'ENDPOINTS_ONLY_BANNER_TEXT': 'Upgraded your instance to Oracle Integration 3, but {0} could not be migrated. To recreate the custom endpoint, follow the steps in this document: <a href="{1}" target="_blank">Configure custom endpoint</a>.',
	'UPGRADE_BANNER_TEXT': 'to Oracle Integration Generation 2. You can make some adjustments to the schedule, or <a href="{0}" target="_blank">learn more</a> about the upgrade.',
	'ONBOARDING_SUCCESSFUL': 'Onboarding successful!',
	'USE_AS_STARTING_POINT_FOR_PROCESS': 'You can use this process as a starting point for your applications.',
	'ORACLE': 'ORACLE',
	'ACCELERATOR_HEADER_SECTION': 'Accelerators are run-ready business integrations or technical patterns you can configure and activate.<br/>Recipes are starter templates that give you a head start. <a href="{0}" target="_blank">Learn More</a> here.',
	'OPPORTUNITY_TO_ORDER_RECIPE_NAME': 'SFDC Opportunity to NS SalesOrder',
	'HCM_TO_OKTA_GENERATE_USERS_RECIPE': 'Oracle HCM Cloud — Okta | Generate Okta Users',
	'SKIP': 'Skip >',
	'CONSOLES': 'Consoles',
	'MODELS': 'Models',
	'VIEW_HELP_CENTER': 'View Help Center',
	'BROWSE_TUTORIALS': 'Browse tutorials',
	'VISIT_ARCHITECTURE_CENTER': 'Visit Architecture Center',
	'VIEW_INTEGRATIONS': 'View integrations',
	'FT_USER_DASH_TITLE': 'Start creating',
	'RT_USER_DASH_TITLE_MONITOR': 'Create and monitor',
	'RT_USER_DASH_TITLE_TRACK': 'Create and track',
	'SINGLE_ERROR': '{0} error',
	'MULTIPLE_ERRORS': '{0} errors',
	'FILTER_BY': 'Filter by:',
	'PICK_A_RECIPE': 'Get started',
	'CREATE_INT_ACTION': 'Create an integration',
	'INT_STATUS_ACTIVATED': 'Active',
	'INT_STATUS_CONFIGURED': 'Configured',
	'INT_STATUS_FAILED': 'Failed',
	'INT_STATUS_IN_PROGRESS': 'Draft',
	'INT_STATUS_ACTIVATION_INPROGRESS': 'Action in progress',
	'INT_STATUS_DEACTIVATION_INPROGRESS': 'Deactivation in progress',
	'TODAY': 'Today',
	'YESTERDAY': 'Yesterday',
	'RECENT_ACTIVITY': 'Recent activity',
	'RECENT_PROJECTS': 'Recent projects',
	'VIEW_ACTIVITY': 'View activity',
	'ERROR_SHOW_MORE': 'Show more>',
	'ERROR_SHOW_LESS': 'Show less>',
	'ERROR_DETAIL_EMPTY': 'N/A',
	'ERROR_DETAIL_TITLE': 'Title',
	'ERROR_STATUS': 'Status',
	'ERROR_TYPE': 'Type',
	'ERROR_DETAIL': 'Detail',
	'UNAUTHORIZED_USER': 'User is not authorized to perform this action.',
	'ERROR_MSG_5XX_TITLE': '<b>Internal Server Error</b>',
	'ERROR_MSG_5XX_DESCRIPTION': 'The server has encountered a situation it doesn\'t know how to handle. Try again maybe fix this issue.',
	'ERROR_MSG_4XX_TITLE': '<b>Bad Request</b>',
	'ERROR_MSG_4XX_DESCRIPTION': 'The server could not understand the request due to invalid syntax.',
	'ERROR_MSG_400_TITLE': '<b>Bad Request</b>',
	'ERROR_MSG_400_DESCRIPTION': 'The server could not understand the request due to invalid syntax.',
	'ERROR_MSG_404_TITLE': '<b>Not Found</b>',
	'ERROR_MSG_404_DESCRIPTION': 'The server can not find requested resource.',
	'PROJECTS': 'Projects',
	'PROJECT': 'Project',
	'KEYBOARD_SHORTCUTS': 'Keyboard shortcuts',
	'GENERATE': 'Generate',
	'CERTIFICATE_EXPIRY_ALERT': 'Certificates',
	'SIGNKEY_CERTIFICATE_PASSPHRASE_LABEL': 'Sign private key password',
	'CERTIFICATE_ALREADY_EXISTS': 'A certificate with the same alias name : {0} and type already exists.',
	'ALREADY_EXISTS':'Already exists',
	'RECIPE_BY':'Recipe by',
	'ACCELERATOR_BY':'Accelerator by',
	'SELECT_PLACEHOLDER_GENERIC': 'Please select',
	'CREATE_INTEGRATION': 'Create integration',
	'CERTIFICATE_INCOMPATIBLE': 'Invalid',
	'INSTANCE_OCID': 'Instance id:',
	"ACCELERATOR_TITLE_BY": '{0} by',
	"ALL_CAUGHT_UP": "All caught up!",
	"NO_RECENT_NOTIFICATIONS": "There has been no recent notifications.",
    "INSTALL_ACCELERATOR_FAILED": "Couldn't get {0}.",
	"INSTALL_ACCELERATOR_SUCCEEDED": "{0} is now available.",
	"INSTALL_ACCELERATOR_INPROGRESS": "Getting {0}.",
    "IMPORT_PROJECT_FAILED": "Couldn't import last uploaded .car file.",
	"IMPORT_PROJECT_SUCCEEDED": "Imported project {0}.",
	"IMPORT_PROJECT_INPROGRESS_WO_NAME": "Importing last uploaded .car file.",
	"IMPORT_PROJECT_INPROGRESS_W_NAME": "Importing project {0}.",
	"DELETE_PROJECT_FAILED": "Couldn't delete the project {0}.",
	"DELETE_PROJECT_SUCCEEDED": "Deleted project {0}.",
	"DELETE_PROJECT_INPROGRESS_W_NAME": "Deleting project {0}.",
    "PUBLISH_API_GATEWAY_FAILED": "Couldn't publish {0} to API gateway.",
	"PUBLISH_API_GATEWAY_SUCCEEDED": "Published {0} to API gateway.",
	"PUBLISH_API_GATEWAY_INPROGRESS": "Publishing {0} to API gateway.",
	"ACTIVATE_INTEGRATION_FAILED": "{0} activation failed.",
	"ACTIVATE_INTEGRATION_ABORTED": "{0} activation was aborted.",
	"ACTIVATE_INTEGRATION_SUCCEEDED": "{0} activation succeeded",
	"ACTIVATE_INTEGRATION_IN_PROGRESS": "Activating {0} .",
	"CLONE_PROJCT_FAILED": "{0} cloned failed.",
	"CLONE_PROJECT_SUCCEEDED": "{0} cloned successfully",
	"CLONE_PROJECT_IN_PROGRESS": "Cloning of {0} is in progress .",
	"EXPORT_PROJECT_FAILED": "Couldn't export project {0}.",
	"EXPORT_PROJECT_SUCCEEDED": "Exported project {0}",
	"EXPORT_PROJECT_IN_PROGRESS": "Exporting project {0}.",
	"TRY_AGAIN": "Try again",
	"SECONDS_AGO": "{0} seconds ago",
	"MINUTES_AGO": "{0} mins ago",
	"MINUTE_AGO": "{0} min ago",
	"HOURS_AGO": "{0} hours ago",
	"HOUR_AGO": "{0} hour ago",
	'CERTIFICATE_KEY_FILE_LABEL': 'Key file',
	'CERTIFICATE_SIGNATURE_FILE_LABEL': 'Signature file',
	'CERTIFICATE_TYPE_SIGNKEY': 'Signing key',
	'CERTIFICATE_TYPE_DIGITALSIGNATURE': 'Digital signature',
	'RESUME_TESTING': 'Resume testing',
	'RESUME_TEST_ERR': 'The integration is no longer active. Please activate it to proceed with testing.',
	'VIEW_FULL_ANNOUNCEMENTS': 'View announcements',
	'VIEW_FULL_ANNOUNCEMENT': 'View full announcement',
	'REVIEW_IMPORTANT_ANNOUNCEMENTS': 'Review important announcements',
	'PE_ONLY_BANNER_SUMMARY': 'OCI private endpoint is active',
	'PE_ONLY_BANNER_DETAIL': 'This instance has been configured to route all outgoing traffic through a private endpoint. Options to use public gateways or certain adapters are not available.',

});
